{
 "title": "Tracking Entities Creation",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(jvm_info,kubernetes_namespace)"
    }
   },
   {
    "name": "nginx_host",
    "query": "{\"find\": \"terms\", \"field\": \"request_host.keyword\"}"
   }
  ]
 },
 "panels": [
  {
   "title": "Each Sync Process Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "Success",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "type:nginx-access AND request_host:\"$nginx_host\" AND nginx.service.name:\"auditservice\" AND source_service_name:\"ejusticehistoricaldataservice\" AND status_code:200",
     "timeField": "@timestamp"
    },
    {
     "alias": "Failure",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "type:nginx-access AND request_host:\"$nginx_host\" AND nginx.service.name:\"auditservice\" AND source_service_name:\"ejusticehistoricaldataservice\" AND (status_code:500 OR status_code:502 OR status_code:503)",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Tracking Entities creation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "Success",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "type:nginx-access AND request_host:\"$nginx_host\" AND nginx.service.name:\"entityservice\" AND source_service_name:\"ejusticehistoricaldataservice\" AND status_code:200 AND (NOT request_uri: *flat*)",
     "timeField": "@timestamp"
    },
    {
     "alias": "Failure",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "type:nginx-access AND request_host:\"$nginx_host\" AND nginx.service.name:\"entityservice\" AND source_service_name:\"ejusticehistoricaldataservice\" AND (status_code:500 OR status_code:502 OR status_code:503) AND (NOT request_uri: *flat*)",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Tacking Entities Creation Failures",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "alias": "Failure",
     "bucketAggs": [
      {
       "field": "request_uri.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "20" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "request_time", "id": "3", "settings": { "percents": [ "99" ] }, "type": "percentiles" },
      { "field": "request_time", "id": "4", "type": "sum" }
     ],
     "query": "type:nginx-access AND request_host:\"$nginx_host\" AND nginx.service.name:\"entityservice\" AND source_service_name:\"ejusticehistoricaldataservice\" AND (status_code:500) AND (NOT request_uri: *flat*)",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}