{
 "title": "System Health Overview",
 "description": "CPU, memory, latency, error rates per service",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(jvm_info,kubernetes_namespace)"
    }
   },
   {
    "name": "nginx_host",
    "query": "{\"find\": \"terms\", \"field\": \"request_host.keyword\"}"
   },
   { "name": "db_server", "query": { "query": "label_values(pg_up,instance)" } },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(elasticsearch_indices_docs,cluster)"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "label_values(elasticsearch_indices_docs{cluster=\"$cluster\", name!=\"\"},instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "# of 2xx requests",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "select field",
       "hide": false,
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "type:nginx-access AND request_host:\"$nginx_host\" AND status_code:2??",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "# of 3xx requests",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "select field",
       "hide": false,
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "type:nginx-access AND request_host:\"$nginx_host\" AND status_code:3??",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "# of 4xx requests",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "select field",
       "hide": false,
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "type:nginx-access AND request_host:\"$nginx_host\" AND status_code:4??",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "# of 5xx requests",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "select field",
       "hide": false,
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "type:nginx-access AND request_host:\"$nginx_host\" AND status_code:5??",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "# of INFO Logs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "select field",
       "hide": false,
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "type:log AND app.environment:\"$namespace\" AND app.loglevel:\"INFO\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "# of WARN Logs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "select field",
       "hide": false,
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "type:log AND app.environment:\"$namespace\" AND app.loglevel:\"WARN\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "# of ERROR Logs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "select field",
       "hide": false,
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "type:log AND app.environment:\"$namespace\" AND app.loglevel:\"ERROR\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Infrastructure Availability",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "K8s-nodes Availability",
     "type": "stat",
     "gridPos": { "h": 4, "w": 5, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg_over_time((count(up{instance=~\".+k8s.+|k8s.+|aks-.+\"} == 1 ) / count(up{instance=~\".+k8s.+|k8s.+|aks-.+\"})) [1h:] )"
      }
     ]
    },
    {
     "title": "Nginx Availability",
     "type": "stat",
     "gridPos": { "h": 4, "w": 5, "x": 5, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg_over_time((sum(up{job=\"nginx-prometheus-exporter\"} ) / count(up{job=\"nginx-prometheus-exporter\"})) [1h:] )"
      }
     ]
    },
    {
     "title": "Vault Availability",
     "type": "stat",
     "gridPos": { "h": 4, "w": 5, "x": 10, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "avg_over_time((sum(up{instance=~\"vault.+:9100\"} ) by (instance) / count(up{instance=~\"vault.+:9100\"})by (instance)) [1h:] ) ",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Active Instances per Service",
     "type": "table",
     "gridPos": { "h": 12, "w": 4, "x": 15, "y": 5 },
     "targets": [
      {
       "expr": "kube_deployment_status_replicas{namespace=~\"$namespace\"}",
       "legendFormat": "{{ deployment }}"
      }
     ]
    },
    {
     "title": "# of Restarts",
     "type": "table",
     "gridPos": { "h": 12, "w": 5, "x": 19, "y": 5 },
     "targets": [
      {
       "expr": "kube_pod_container_status_restarts_total{namespace=\"$namespace\"} > 0"
      }
     ]
    },
    {
     "title": "Rabbitmq Availability",
     "type": "stat",
     "gridPos": { "h": 4, "w": 5, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg_over_time((sum(rabbitmq_up{kubernetes_namespace=~\"$namespace\"} ) / count(rabbitmq_up{kubernetes_namespace=~\"$namespace\"})) [1h:] )"
      }
     ]
    },
    {
     "title": "Elasticsearch Availability",
     "type": "stat",
     "gridPos": { "h": 4, "w": 5, "x": 5, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg_over_time(up{job=\"elasticsearch_exporter\",namespace=~\"$namespace\"} [1h:] )"
      }
     ]
    },
    {
     "title": "Redis Availability",
     "type": "stat",
     "gridPos": { "h": 4, "w": 5, "x": 10, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg_over_time((sum(redis_up{kubernetes_namespace=~\"$namespace\"} ) / count(redis_up{kubernetes_namespace=~\"$namespace\"})) [1h:] )"
      }
     ]
    },
    {
     "title": "Total Services Running",
     "type": "stat",
     "gridPos": { "h": 4, "w": 5, "x": 0, "y": 13 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(up{job=~\".*\", kubernetes_namespace=\"$namespace\"})",
       "legendFormat": "Services Running"
      }
     ]
    },
    {
     "title": "PostgreSQL UP",
     "type": "timeseries",
     "gridPos": { "h": 4, "w": 10, "x": 5, "y": 13 },
     "targets": [
      {
       "expr": "pg_up or cnpg_collector_up{job=\"kubernetes-service-endpoints\"}",
       "legendFormat": "{{environment}} {{service}} {{kubernetes_namespace}} {{kubernetes_name}} "
      }
     ]
    }
   ]
  },
  { "title": "HTTP", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Request Per $__interval",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "rps",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "type:nginx-access  AND  request_host:\"$namespace.synisys.com\" AND nginx.service.name:$service",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "type.keyword:nginx-access AND request_host.keyword:\"$nginx_host\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Response time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "type:nginx-access  AND  request_host:\"$namespace.synisys.com\" AND nginx.service.name:$service",
     "metrics": [
      {
       "field": "request_time",
       "id": "1",
       "meta": {},
       "settings": { "percents": [ "95" ] },
       "type": "percentiles"
      },
      {
       "field": "upstream_response_time",
       "hide": true,
       "id": "3",
       "meta": {},
       "settings": { "percents": [ "95" ] },
       "type": "percentiles"
      }
     ],
     "query": "type.keyword:nginx-access AND request_host.keyword:\"$nginx_host\" AND NOT nginx.service.name.keyword: clientnotifierservice AND NOT request_uri: emitter",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "Total",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "type.keyword:nginx-access AND request_host.keyword:\"$nginx_host\" AND status_code.keyword:[100 TO 599]",
     "timeField": "@timestamp"
    },
    {
     "alias": "Error",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "type.keyword:nginx-access AND request_host.keyword:\"$nginx_host\" AND status_code.keyword:[499 TO 599]",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "HTTP Distribution",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "Status Code Distribution",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 5, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "count" ] } },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "status_code.keyword",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "10" },
         "type": "terms"
        }
       ],
       "expr": "type:nginx-access  AND  request_host:\"$namespace.synisys.com\" AND nginx.service.name:\"$kibana_service\"",
       "metrics": [
        {
         "hide": false,
         "id": "1",
         "type": "count"
        }
       ],
       "query": "type:nginx-access AND request_host:\"$nginx_host\"",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Method Distribution",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 5, "x": 5, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "count" ] } },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "method.keyword",
         "id": "5",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "10" },
         "type": "terms"
        }
       ],
       "expr": "type:nginx-access  AND  request_host:\"$namespace.synisys.com\" AND nginx.service.name:\"$kibana_service\"",
       "metrics": [
        {
         "hide": false,
         "id": "1",
         "type": "count"
        }
       ],
       "query": "type:nginx-access AND request_host:\"$nginx_host\"",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Source Service Distribution",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 7, "x": 10, "y": 8 },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "source_service_name.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "0" },
         "type": "terms"
        },
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "type:nginx-access AND request_host:\"$nginx_host\"",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Target Service Distribution",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 7, "x": 17, "y": 8 },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "nginx.service.name.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "0" },
         "type": "terms"
        },
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "type:nginx-access AND request_host:\"$nginx_host\"",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Fail Requests (Server Errors)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
     "targets": [
      {
       "alias": "{{source_service_name.keyword}} -> {{nginx.service.name.keyword}} ({{status_code.keyword}})",
       "bucketAggs": [
        {
         "field": "source_service_name.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "0" },
         "type": "terms"
        },
        {
         "field": "status_code.keyword",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        {
         "field": "nginx.service.name.keyword",
         "id": "5",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
         "type": "terms"
        },
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "type:nginx-access AND request_host:\"$nginx_host\" AND status_code:5??",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Fail Requests (Client Errors)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
     "targets": [
      {
       "alias": "{{source_service_name.keyword}} -> {{nginx.service.name.keyword}} ({{status_code.keyword}})",
       "bucketAggs": [
        {
         "field": "source_service_name.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "0" },
         "type": "terms"
        },
        {
         "field": "status_code.keyword",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        {
         "field": "nginx.service.name.keyword",
         "id": "5",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
         "type": "terms"
        },
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "type:nginx-access AND request_host:\"$nginx_host\" AND status_code:4??",
       "timeField": "@timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "HTTP Latency by Service",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "Request's Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "bucketAggs": [
        {
         "fake": true,
         "field": "nginx.service.name.keyword",
         "id": "4",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1[95.0]", "size": "20" },
         "type": "terms"
        },
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "expr": "type:nginx-access  AND  request_host:\"$namespace.synisys.com\" AND nginx.service.name:\"$kibana_service\"",
       "metrics": [
        {
         "field": "request_time",
         "id": "1",
         "meta": {},
         "settings": { "percents": [ "95" ] },
         "type": "percentiles"
        }
       ],
       "query": "type.keyword:nginx-access AND request_host.keyword:\"$nginx_host\" AND NOT (\nnginx.service.name.keyword: clientnotifierservice OR\nnginx.service.name.keyword: reportingservice OR\nnginx.service.name.keyword: reportexportservice OR\nnginx.service.name.keyword: notificationservice OR\nnginx.service.name.keyword: auditservice OR\nnginx.service.name.keyword: ejusticedocumentservice OR\nnginx.service.name.keyword: exportservice)",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Request's Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "bucketAggs": [
        {
         "fake": true,
         "field": "nginx.service.name.keyword",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1[95.0]", "size": "20" },
         "type": "terms"
        },
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "expr": "type:nginx-access  AND  request_host:\"$namespace.synisys.com\" AND nginx.service.name:\"$kibana_service\"",
       "metrics": [
        {
         "field": "request_time",
         "id": "1",
         "meta": {},
         "settings": { "percents": [ "95" ] },
         "type": "percentiles"
        }
       ],
       "query": "type.keyword:nginx-access AND request_host.keyword:\"$nginx_host\" AND (\nnginx.service.name.keyword: clientnotifierservice OR\nnginx.service.name.keyword: reportingservice OR\nnginx.service.name.keyword: reportexportservice OR\nnginx.service.name.keyword: notificationservice OR\nnginx.service.name.keyword: auditservice OR\nnginx.service.name.keyword: ejusticedocumentservice OR\nnginx.service.name.keyword: exportservice)",
       "timeField": "@timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "Resource Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Average Usage %",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "avg(rate(process_cpu_seconds_total[$__rate_interval]))*100",
       "legendFormat": "CPU Usage (%)"
      }
     ]
    },
    {
     "title": "Memory Average Usage %",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "avg(node_memory_Active_bytes / node_memory_MemTotal_bytes) * 100",
       "legendFormat": "Memory Usage (%)"
      }
     ]
    },
    {
     "title": "Bandwidth Usage",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "(sum(rate(node_network_receive_bytes_total[$__rate_interval])))",
       "legendFormat": "Data Received"
      },
      {
       "expr": "(sum(rate(node_network_transmit_bytes_total[1m])))",
       "legendFormat": "Data Sent"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "Container Memory &  Swap",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum(container_memory_usage_bytes{namespace=\"$namespace\"})",
       "legendFormat": "Memory"
      },
      {
       "expr": "sum(container_memory_swap{namespace=\"$namespace\"})",
       "legendFormat": "Swap"
      }
     ]
    },
    {
     "title": "GC collection time",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(rate(jvm_gc_collection_seconds_sum{kubernetes_namespace=~\"$namespace\"}[$__rate_interval]))",
       "legendFormat": "collection"
      },
      {
       "expr": "sum(rate(jvm_gc_pause_seconds_sum{kubernetes_namespace=~\"$namespace\"}[$__rate_interval]))",
       "legendFormat": "pause"
      }
     ]
    }
   ]
  },
  {
   "title": "Database",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "PostgreSQL Connections per Instance",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
     "targets": [
      {
       "expr": "sum(dbmon_pg_user_connection_count) by (instance)",
       "legendFormat": "{{server}}"
      }
     ]
    },
    {
     "title": "Total Query Executions per DB Server",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(pg_query_execution_count{instance=~\"$db_server\"}) by (instance)",
       "legendFormat": "{{db_server}}"
      }
     ]
    },
    {
     "title": "Slowest 1% of PG Queries (>200ms) – Service Users",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "pg_query_execution_time_99{instance=~\"$db_server\", user_name=~\".*service.*\"} > 200",
       "legendFormat": "99th {{db_server}} {{db_name}} {{user_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Database Connections Pool",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Max Connections",
     "type": "piechart",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 13 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(hikaricp_max_connections{kubernetes_namespace=\"$namespace\"}) by (pool)",
       "legendFormat": "{{pool}}"
      }
     ]
    },
    {
     "title": "Total Max Possible Connections",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 8, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(hikaricp_max_connections{kubernetes_namespace=\"$namespace\"})"
      }
     ]
    },
    {
     "title": "Total Active Connections",
     "type": "stat",
     "gridPos": { "h": 6, "w": 6, "x": 12, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(hikaricp_active_connections{kubernetes_namespace=\"$namespace\"}) + sum(vertx_pool_in_use{kubernetes_namespace=\"$namespace\", pool_type=\"sql\"})",
       "legendFormat": "active"
      }
     ]
    },
    {
     "title": "Total Pending Threads",
     "type": "stat",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(hikaricp_pending_threads{kubernetes_namespace=\"$namespace\"}) + sum(vertx_pool_queue_pending{kubernetes_namespace=\"$namespace\", pool_type=\"sql\"})",
       "legendFormat": "pending"
      }
     ]
    },
    {
     "title": "Total Idle Connections",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 8, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(hikaricp_idle_connections{kubernetes_namespace=\"$namespace\"})"
      }
     ]
    },
    {
     "title": "SQL Query Execution Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 19 },
     "targets": [
      {
       "expr": "sum(rate(multidatasource_query_execution_seconds_count{kubernetes_namespace=\"$namespace\"}[$__rate_interval] ))",
       "legendFormat": "qps"
      },
      {
       "expr": "sum(rate(vertx_sql_processing_time_seconds_count{kubernetes_namespace=\"$namespace\"}[$__rate_interval]))",
       "legendFormat": "qps (vertx)"
      }
     ]
    },
    {
     "title": "SQL Query Execution Duration",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(multidatasource_query_execution_seconds_bucket{kubernetes_namespace=\"$namespace\"}[$__rate_interval])) by (le))",
       "legendFormat": "95th Percentile"
      }
     ]
    },
    {
     "title": "Database Connections Pool",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(hikaricp_active_connections{kubernetes_namespace=\"$namespace\"})",
       "legendFormat": "active"
      },
      {
       "expr": "sum(hikaricp_idle_connections{kubernetes_namespace=\"$namespace\"})",
       "legendFormat": "idle"
      },
      {
       "expr": "sum(hikaricp_pending_threads{kubernetes_namespace=\"$namespace\"})",
       "legendFormat": "pending"
      },
      {
       "expr": "sum(vertx_pool_in_use{kubernetes_namespace=\"$namespace\", pool_type=\"sql\"})",
       "legendFormat": "in use (vertx)"
      },
      {
       "expr": "sum(vertx_pool_queue_pending{kubernetes_namespace=\"$namespace\", pool_type=\"sql\"})",
       "legendFormat": "pending (vertx)"
      }
     ]
    }
   ]
  },
  {
   "title": "RabbitMQ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "Queued Messages",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
     "targets": [
      {
       "expr": "sum(rabbitmq_queue_messages{kubernetes_namespace=\"$namespace\", queue!=\"messaging-upgraded-services\", queue!~\".*[-]gateway[-].*\"})",
       "legendFormat": "# of messages"
      }
     ]
    },
    {
     "title": "Messages Publish/Deliver Rates",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
     "targets": [
      {
       "expr": "sum(rabbitmq_queue_messages_publish_rate{kubernetes_namespace=\"$namespace\"})",
       "legendFormat": "publish rate"
      },
      {
       "expr": "-sum(rabbitmq_queue_messages_deliver_rate{kubernetes_namespace=\"$namespace\"})",
       "legendFormat": "deliver rate"
      }
     ]
    }
   ]
  },
  {
   "title": "ElasticSearch",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Operations  rate",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(elasticsearch_indices_indexing_index_total{instance=~\"$instance\",cluster=\"$cluster\"}[$__rate_interval])",
       "legendFormat": "{{name}}: indexing"
      },
      {
       "expr": "rate(elasticsearch_indices_search_query_total{instance=~\"$instance\",cluster=\"$cluster\"}[$__rate_interval])",
       "legendFormat": "{{name}}: query"
      },
      {
       "expr": "rate(elasticsearch_indices_search_fetch_total{instance=~\"$instance\",cluster=\"$cluster\"}[$__rate_interval])",
       "legendFormat": "{{name}}: fetch"
      },
      {
       "expr": "rate(elasticsearch_indices_merges_total{instance=~\"$instance\",cluster=\"$cluster\"}[$__rate_interval])",
       "legendFormat": "{{name}}: merges"
      },
      {
       "expr": "rate(elasticsearch_indices_refresh_total{instance=~\"$instance\",cluster=\"$cluster\"}[$__rate_interval])",
       "legendFormat": "{{name}}: refresh"
      },
      {
       "expr": "rate(elasticsearch_indices_flush_total{instance=~\"$instance\",cluster=\"$cluster\"}[$__rate_interval])",
       "legendFormat": "{{name}}: flush"
      },
      {
       "expr": "rate(elasticsearch_indices_get_exists_total{instance=~\"$instance\",cluster=\"$cluster\"}[$__rate_interval])",
       "legendFormat": "{{name}}: get_exists"
      },
      {
       "expr": "rate(elasticsearch_indices_get_missing_total{instance=~\"$instance\",cluster=\"$cluster\"}[$__rate_interval])",
       "legendFormat": "{{name}}: get_missing"
      },
      {
       "expr": "rate(elasticsearch_indices_get_tota{instance=~\"$instance\",cluster=\"$cluster\"}[$__rate_interval])",
       "legendFormat": "{{name}}: get"
      },
      {
       "expr": "rate(elasticsearch_indices_indexing_delete_total{instance=~\"$instance\",cluster=\"$cluster\"}[$__rate_interval])",
       "legendFormat": "{{name}}: indexing_delete"
      }
     ]
    },
    {
     "title": "Total Operations time",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "irate(elasticsearch_indices_indexing_index_time_seconds_total{instance=~\"$instance\",cluster=\"$cluster\"}[$__rate_interval])",
       "legendFormat": "{{name}}: indexing"
      },
      {
       "expr": "irate(elasticsearch_indices_search_query_time_seconds{instance=~\"$instance\",cluster=\"$cluster\"}[$__rate_interval])",
       "legendFormat": "{{name}}: query"
      },
      {
       "expr": "irate(elasticsearch_indices_search_fetch_time_seconds{instance=~\"$instance\",cluster=\"$cluster\"}[$__rate_interval])",
       "legendFormat": "{{name}}: fetch"
      },
      {
       "expr": "irate(elasticsearch_indices_merges_total_time_seconds_total{instance=~\"$instance\",cluster=\"$cluster\"}[$__rate_interval])",
       "legendFormat": "{{name}}: merges"
      },
      {
       "expr": "irate(elasticsearch_indices_refresh_time_seconds_total{instance=~\"$instance\",cluster=\"$cluster\"}[$__rate_interval])",
       "legendFormat": "{{name}}: refresh"
      },
      {
       "expr": "irate(elasticsearch_indices_flush_time_seconds{instance=~\"$instance\",cluster=\"$cluster\"}[$__rate_interval])",
       "legendFormat": "{{name}}: flush"
      },
      {
       "expr": "irate(elasticsearch_indices_get_exists_time_seconds{instance=~\"$instance\",cluster=\"$cluster\"}[$__rate_interval])",
       "legendFormat": "{{name}}: get_exists"
      },
      {
       "expr": "irate(elasticsearch_indices_get_time_seconds{instance=~\"$instance\",cluster=\"$cluster\"}[$__rate_interval])",
       "legendFormat": "{{name}}: get_time"
      },
      {
       "expr": "irate(elasticsearch_indices_get_missing_time_seconds{instance=~\"$instance\",cluster=\"$cluster\"}[$__rate_interval])",
       "legendFormat": "{{name}}: get_missing"
      },
      {
       "expr": "irate(elasticsearch_indices_indexing_delete_time_seconds_total{instance=~\"$instance\",cluster=\"$cluster\"}[$__rate_interval])",
       "legendFormat": "{{name}}: indexing_delete"
      },
      {
       "expr": "irate(elasticsearch_indices_get_time_seconds{instance=~\"$instance\",cluster=\"$cluster\"}[$__rate_interval])",
       "legendFormat": "{{name}}: get"
      }
     ]
    }
   ]
  }
 ]
}