{
 "title": "User Analytics",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "environment",
    "query": {
     "query": "label_values(ejustice_ecase_active_users, kubernetes_namespace)"
    }
   },
   {
    "name": "app",
    "query": {
     "query": "label_values(ejustice_ecase_active_users{kubernetes_namespace=\"$environment\"}, app)"
    }
   },
   {
    "name": "ui_service",
    "query": {
     "query": "label_values(ejustice_ecase_active_users{kubernetes_namespace=\"$environment\"}, kubernetes_name)"
    }
   },
   {
    "name": "headOrg",
    "query": {
     "query": "label_values(ejustice_ecase_loading_duration_in_seconds_bucket{kubernetes_namespace=\"$environment\",app=\"$app\"},headOrg)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Online Users",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ejustice_ecase_online_users{kubernetes_namespace=\"$environment\", app=~\"$app\", headOrg=~\"$headOrg\"})",
     "legendFormat": "All"
    },
    {
     "expr": "sum(ejustice_ecase_online_users{kubernetes_namespace=\"$environment\", app=~\"$app\", headOrg=~\"$headOrg\"}) by (status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Activities (# of Users)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(ejustice_ecase_active_users{kubernetes_namespace=\"$environment\", kubernetes_name=~\"$ui_service\", app=~\"$app\", area!=\"ALL\"}) by (area)",
     "legendFormat": "{{area}}"
    }
   ]
  },
  {
   "title": "Online Users",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "max(sum(ejustice_ecase_online_users{kubernetes_namespace=\"$environment\", app=~\"$app\", kubernetes_name=~\"$ui_service\"}) by (status, instance)) by (status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Online Active Users by Head Organization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 4 },
   "targets": [
    {
     "expr": "sum(ejustice_ecase_online_users{kubernetes_namespace=\"$environment\", app=~\"$app\", kubernetes_name=~\"$ui_service\", headOrg=~\"$headOrg\", status=\"active\"}) by (headOrg)",
     "legendFormat": "Head Org ({{headOrg}})"
    }
   ]
  },
  {
   "title": "Online Active Users by Organization (Top 10)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 4 },
   "targets": [
    {
     "expr": "topk(10, sum(ejustice_ecase_online_users{kubernetes_namespace=\"$environment\", app=~\"$app\", kubernetes_name=~\"$ui_service\", headOrg=~\"$headOrg\", status=\"active\"}) by (org))",
     "legendFormat": "Org ({{org}})"
    }
   ]
  },
  {
   "title": "Page Loading Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(ejustice_ecase_loading_duration_in_seconds_bucket{kubernetes_namespace=\"$environment\", app=\"$app\", kubernetes_name=\"$ui_service\", headOrg=~\"$headOrg\"}[2m])) by (le))",
     "legendFormat": "95th Percentile"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(ejustice_ecase_loading_duration_in_seconds_bucket{kubernetes_namespace=\"$environment\", app=\"$app\", kubernetes_name=\"$ui_service\", headOrg=~\"$headOrg\"}[2m])) by (le))",
     "legendFormat": "75th Percentile"
    }
   ]
  },
  {
   "title": "Download Speed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum(ejustice_ecase_users_speed_in_mbps_bucket{kubernetes_namespace=\"$environment\", app=\"$app\", kubernetes_name=\"$ui_service\", type=\"download\"}) by (le)) ",
     "legendFormat": "90% of users under"
    },
    {
     "expr": "histogram_quantile(0.75, sum(ejustice_ecase_users_speed_in_mbps_bucket{kubernetes_namespace=\"$environment\", app=\"$app\", kubernetes_name=\"$ui_service\", type=\"download\"}) by (le)) ",
     "legendFormat": "75% of users under"
    },
    {
     "expr": "histogram_quantile(0.5, sum(ejustice_ecase_users_speed_in_mbps_bucket{kubernetes_namespace=\"$environment\", app=\"$app\", kubernetes_name=\"$ui_service\", type=\"download\"}) by (le)) ",
     "legendFormat": "50% of users under"
    },
    {
     "expr": "histogram_quantile(0.25, sum(ejustice_ecase_users_speed_in_mbps_bucket{kubernetes_namespace=\"$environment\", app=\"$app\", kubernetes_name=\"$ui_service\", type=\"download\"}) by (le)) ",
     "legendFormat": "25% of users under"
    }
   ]
  },
  {
   "title": "Upload Speed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum(ejustice_ecase_users_speed_in_mbps_bucket{kubernetes_namespace=\"$environment\", app=\"$app\", kubernetes_name=\"$ui_service\", type=\"upload\"}) by (le)) ",
     "legendFormat": "90% of users under"
    },
    {
     "expr": "histogram_quantile(0.75, sum(ejustice_ecase_users_speed_in_mbps_bucket{kubernetes_namespace=\"$environment\", app=\"$app\", kubernetes_name=\"$ui_service\", type=\"upload\"}) by (le)) ",
     "legendFormat": "75% of users under"
    },
    {
     "expr": "histogram_quantile(0.5, sum(ejustice_ecase_users_speed_in_mbps_bucket{kubernetes_namespace=\"$environment\", app=\"$app\", kubernetes_name=\"$ui_service\", type=\"upload\"}) by (le)) ",
     "legendFormat": "50% of users under"
    },
    {
     "expr": "histogram_quantile(0.25, sum(ejustice_ecase_users_speed_in_mbps_bucket{kubernetes_namespace=\"$environment\", app=\"$app\", kubernetes_name=\"$ui_service\", type=\"upload\"}) by (le)) ",
     "legendFormat": "25% of users under"
    }
   ]
  },
  {
   "title": "Idle Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(ejustice_ecase_idle_duration_in_minutes_bucket{kubernetes_namespace=\"$environment\", app=\"$app\", kubernetes_name=\"$ui_service\"}[$__rate_interval])) by (le))",
     "legendFormat": "95th Percentile"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(ejustice_ecase_idle_duration_in_minutes_bucket{kubernetes_namespace=\"$environment\", app=\"$app\", kubernetes_name=\"$ui_service\"}[$__rate_interval])) by (le))",
     "legendFormat": "75th Percentile"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(ejustice_ecase_idle_duration_in_minutes_bucket{kubernetes_namespace=\"$environment\", app=\"$app\", kubernetes_name=\"$ui_service\"}[$__rate_interval])) by (le))",
     "legendFormat": "50th Percentile"
    }
   ]
  }
 ]
}