apiVersion: 1
contactPoints:
    - orgId: 1
      name: critical
      receivers:
        - uid: critical
          type: teams
          settings:
            message: '{{ template "message" .}}'
            title: '{{ template "title" .}}'
            url: ${SLACK_URL}
          disableResolveMessage: false
    - orgId: 1
      name: projectemail
      receivers:
        - uid: projectemail
          type: email
          settings:
            addresses: <%= @env_name %>-alerting.synisys.com
            message: '{{ template "message" .}}'
            singleEmail: false
            subject: '{{ template "title" .}}'
          disableResolveMessage: false
    - orgId: 1
      name: warning
      receivers:
        - uid: warning
          type: teams
          settings:
            message: '{{ template "message" .}}'
            title: '{{ template "title" .}}'
            url: ${SLACK_URL}
          disableResolveMessage: false
