apiVersion: 1
groups:
    - orgId: 1
      name: 10s
      folder: alerting
      interval: 10s
      rules:
        - uid: disk-usage
          title: DISK USAGE
          condition: C
          data:
            - refId: A
              relativeTimeRange:
                from: 300
                to: 0
              datasourceUid: "000000001"
              model:
                datasource:
                    type: prometheus
                    uid: "000000001"
                editorMode: code
                exemplar: true
                expr: 100 - ((node_filesystem_free_bytes{instance=~".+:9100", instance!~"sis2s055:9100|elk-temp:9100",device!~'rootfs',mountpoint!~"/sys/firmware/efi/efivars|/proc/fs/nfsd|/boot|/mnt/backup_nfs|/nfs-docker|/postgresql_cluster3|/run/.+"}) / (node_filesystem_size_bytes{instance=~".+:9100",device!~'rootfs'})) *100
                interval: ""
                intervalMs: 30000
                legendFormat: '{{instance}}:{{mountpoint}} '
                maxDataPoints: 43200
                range: true
                refId: A
            - refId: B
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params: []
                        type: gt
                      operator:
                        type: and
                      query:
                        params:
                            - B
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: A
                intervalMs: 1000
                maxDataPoints: 43200
                reducer: last
                refId: B
                settings:
                    mode: replaceNN
                    replaceWithValue: 0
                type: reduce
            - refId: C
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 90
                        type: gt
                      operator:
                        type: and
                      query:
                        params:
                            - C
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: B
                intervalMs: 1000
                maxDataPoints: 43200
                refId: C
                type: threshold
          dashboardUid: vldByyKnz
          panelId: 24
          noDataState: OK
          execErrState: OK
          for: 3m
          annotations:
            __dashboardUid__: vldByyKnz
            __panelId__: "24"
            summary: '{{ index $labels "instance" }}{{ index $labels "mountpoint" }} is {{ humanize (index $values "B").Value }}%'
          labels:
            severity: critical
          isPaused: false
