apiVersion: 1
groups:
    - orgId: 1
      name: 10s
      folder: alerting
      interval: 10s
      rules:
        - uid: kube-node-ready
          title: Kube NODE ready
          condition: C
          data:
            - refId: A
              relativeTimeRange:
                from: 300
                to: 0
              datasourceUid: "000000001"
              model:
                datasource:
                    type: prometheus
                    uid: "000000001"
                exemplar: true
                expr: kube_node_status_condition{condition="Ready", status="true",node!="dev-blockchain"}
                interval: ""
                intervalMs: 30000
                legendFormat: '{{node}}'
                maxDataPoints: 43200
                refId: A
            - refId: B
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params: []
                        type: gt
                      operator:
                        type: and
                      query:
                        params:
                            - B
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: A
                intervalMs: 1000
                maxDataPoints: 43200
                reducer: last
                refId: B
                type: reduce
            - refId: C
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 1
                        type: lt
                      operator:
                        type: and
                      query:
                        params:
                            - C
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: B
                intervalMs: 1000
                maxDataPoints: 43200
                refId: C
                type: threshold
          dashboardUid: vldByyKnz
          panelId: 70
          noDataState: OK
          execErrState: OK
          for: 3m
          annotations:
            __dashboardUid__: vldByyKnz
            __panelId__: "70"
            summary: '{{ index $labels "node" }}Readyness is {{ index $values "B" }}'
          labels:
            severity: critical
          isPaused: false
