apiVersion: 1
datasources:
  - name: elasticsearch
    type: elasticsearch
    access: proxy
    uid: 000000006
    database: '*'
    url: http://elasticsearch:9200
    basicAuth: true
    basicAuthUser: elastic
    secureJsonData:
      basicAuthPassword: RY5UQGU6ceRBVw
    jsonData:
      timeField: '@timestamp'
      esVersion: '8.9.1'
      logMessageField: 'message'
      logLevelField: 'app.loglevel'