apiVersion: 1
datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    id: 1
    orgId: 1
    uid: 000000001
    url: http://prometheus:9090
    basicAuth: false
    isDefault: true
    editable: true