{
 "title": "Alerting",
 "tags": [ "alerting" ],
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Alert LIST",
   "type": "alertlist",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Infrastructure",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Kube NODE ready",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "kube_node_status_condition{condition=\"Ready\", status=\"true\",node!=\"dev-blockchain\"}",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Microservice availability",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (namespace,pod)(kube_pod_status_ready{condition=\"true\",namespace!~\"chatwoot|cert-manager|argocd|velero|cnpg-system|consul.*|metallb-system|vault|kube-system|monitoring|knative-serving|ingress-nginx|istio-system|minio|default|filebeat|hal|openunison|opentelemetry|randomcoffee|projecttracker|kubernetes-dashboard|kube-fledged|portal-qa\", pod!~\"reportexportservice-v1.+\"} == 0 and on(pod) kube_pod_status_phase{phase!=\"Succeeded\"} == 1)",
     "legendFormat": "{{namespace}} {{pod}}"
    }
   ]
  },
  {
   "title": "RabbitMQ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rabbitmq_up{job=~\"kubernetes-service-endpoints\", kubernetes_namespace=~\".+\"}",
     "legendFormat": "{{kubernetes_namespace}}"
    }
   ]
  },
  {
   "title": "Redis",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "redis_up{job=~\"kubernetes-service-endpoints\", kubernetes_node!~\"mrs.+\", kubernetes_namespace=~\".+\"}",
     "legendFormat": "{{kubernetes_namespace}}"
    }
   ]
  },
  {
   "title": "Consul",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "consul_up{job=\"consul-exporter\"}",
     "legendFormat": "{{environment}} {{service}}"
    }
   ]
  },
  {
   "title": "Nginx",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "min(nginx_up{job=\"nginx-prometheus-exporter\"})",
     "legendFormat": "Nginx"
    }
   ]
  },
  {
   "title": "All Servers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "up{instance=~\".+:9100\", kubernetes_node!=\"aks-newpool-37651559-vmss000001\"}",
     "legendFormat": "{{kubernetes_node}} {{instance}} {{service}}"
    }
   ]
  },
  {
   "title": "Kubernetes Nodes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "up{kubernetes_node=~\".+\", instance=~\".+:9100\", kubernetes_node!=\"aks-newpool-37651559-vmss000001\"}",
     "legendFormat": "{{kubernetes_node}}"
    }
   ]
  },
  {
   "title": "DISK SIZE FREE",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_free_bytes{instance=~\".+:9100\", instance!~\"sis2s055:9100|elk-temp:9100\",device!~'rootfs',mountpoint!~\"/sys/firmware/efi/efivars|/proc/fs/nfsd|/boot|/mnt/backup_nfs|/nfs-docker|/postgresql_cluster3\"}) / (node_filesystem_size_bytes{instance=~\".+:9100\",device!~'rootfs'})) *100",
     "legendFormat": "{{instance}}:{{mountpoint}} "
    }
   ]
  },
  {
   "title": "PV utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100- (kubelet_volume_stats_available_bytes{namespace=~\".+\", persistentvolumeclaim!~\"postgres-10-pvc\" ,persistentvolumeclaim=~\".+\"} / kubelet_volume_stats_capacity_bytes{namespace=~\".+\",persistentvolumeclaim=~\".+\"}  *100)",
     "legendFormat": "{{cluster}} {{namespace}} {{persistentvolumeclaim}}"
    }
   ]
  },
  {
   "title": "CPU usage ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (rate(node_cpu_seconds_total{mode=\"idle\"}[$__rate_interval])) * 100)  ",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "RAM usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "((node_memory_MemTotal_bytes{job!=\"Jenkins\", instance!~\"sis2s041:9100\"} - node_memory_MemFree_bytes{job!=\"Jenkins\"} - (node_memory_Cached_bytes{job!=\"Jenkins\"} + node_memory_Buffers_bytes{job!=\"Jenkins\"} + node_memory_SReclaimable_bytes{job!=\"Jenkins\"})) / node_memory_MemTotal_bytes{job!=\"Jenkins\"} )*100",
     "legendFormat": "{{kubernetes_node}} {{instance}}"
    }
   ]
  },
  {
   "title": "SysLoad (5m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg by (instance)(node_load5{instance=~\".+\"}) /  count by (instance)(count(node_cpu_seconds_total{instance=~\".+\"}) by (instance,cpu)) * 100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Prometheus",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 66 },
   "targets": [
    {
     "expr": "up{job=\"prometheus\"}",
     "legendFormat": "up {{job}}"
    }
   ]
  },
  {
   "title": "NGINX-ACCESS log count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Nginx-Access log count",
     "bucketAggs": [
      {
       "$$hashKey": "object:286",
       "field": "@timestamp",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:284", "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "type: \"nginx-access\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Application log count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Application log count",
     "bucketAggs": [
      {
       "$$hashKey": "object:286",
       "field": "@timestamp",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:284", "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "type: \"log\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "PostgreSQL UP",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 82 },
   "targets": [
    {
     "expr": "pg_up or cnpg_collector_up{job=\"kubernetes-service-endpoints\"}",
     "legendFormat": "{{environment}} {{service}} {{kubernetes_namespace}} {{kubernetes_name}} "
    }
   ]
  },
  {
   "title": "Kube Cert Expire Alert",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "targets": [
    {
     "expr": "cert_exporter_cert_expires_in_seconds{kubernetes_node=~\".+\",filename=~\".+\", filename!~\"/var/lib/kubelet/pki/kubelet.crt\"} / 86400",
     "legendFormat": "{{kubernetes_node}} {{filename}}"
    }
   ]
  },
  {
   "title": "Application",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 90 },
   "targets": [
    {}
   ]
  },
  {
   "title": "No RabbitMQ consumer ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 91 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rabbitmq_queue_consumers{job=\"kubernetes-service-endpoints\",\n  queue!~\".*retry\",\n  queue!~\"reporting-service-sync-.*\",\n  queue!~\".*-exchange-tracker\",\n  queue!~\"^SIS.+\",\n  queue!~\"^sis.+\",\n  queue!~\"^Sis.+\",\n  queue!~\"^DESKTOP.+\",\n  queue!~\"messaging-upgraded-services\",\n  queue!~\"reporting-service-sync.source-exchange-created\",\n  queue!~\"health-status-result-test\",\n  queue!~\"^reporting-service-sync.+\",\n  queue!~\".+-v1.+\",\n  queue!~\".+-v2.+\",\n  queue!~\"^macadmins.+\",\n  queue!~\"^localhost.+\",\n  queue!~\"^[0-9].+\",\n  queue!~\"health-status-result\",\n  queue!~\"^kube-master-dev.+\",\n  queue!~\".*docker.*\"\n  } < 1",
     "legendFormat": "{{queue}}  <{{kubernetes_namespace}}>"
    }
   ]
  },
  {
   "title": "RabbitMQ Queue limit ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rabbitmq_queue_messages_ready{job=\"kubernetes-service-endpoints\",\n  queue!~\".*sms.*retry.*|.*mail.*retry.*\",\n  queue!~\"messaging-upgraded-services\",\n  queue!~\"^reporting-service-sync.+\",\n  queue!~\"health-status-result-test\"\n  } > 500",
     "legendFormat": "{{queue}} <{{kubernetes_namespace}}>"
    }
   ]
  },
  {
   "title": "Rabbitmq Process Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 99 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "((rabbitmq_process_resident_memory_bytes * on(instance) group_left(rabbitmq_cluster, rabbitmq_node) rabbitmq_identity_info{rabbitmq_cluster=~\".+\"})\r\n/\r\n(rabbitmq_resident_memory_limit_bytes * on(instance) group_left(rabbitmq_cluster, rabbitmq_node) rabbitmq_identity_info{rabbitmq_cluster=~\".+\"})) *100",
     "legendFormat": "{{kubernetes_namespace}} {{kubernetes_name}}"
    }
   ]
  },
  {
   "title": "Success Rate SLO",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 99 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(sum_over_time((\r\n  (\r\n    (sum(rate(service_response_status_total{kubernetes_name=~\".+\", kubernetes_namespace=~\".+\", status!~\"5..\"}[2m])) by (kubernetes_name,kubernetes_namespace))\r\n    /\r\n    (sum(rate(service_response_status_total{kubernetes_name=~\".+\", kubernetes_namespace=~\".+\"}[2m])) by (kubernetes_name,kubernetes_namespace))\r\n  ) > bool 0.995\r\n  +\r\n  (sum(rate(service_response_status_total{kubernetes_name=~\".+\", kubernetes_namespace=~\".+\"}[2m])) by (kubernetes_name,kubernetes_namespace) == bool 0)\r\n)[5m:])\r\n/\r\ncount_over_time(sum(rate(service_response_status_total{kubernetes_name=~\".+\", kubernetes_namespace=~\".+\"}[2m])) by (kubernetes_name,kubernetes_namespace)[5m:])\r\n)*100",
     "legendFormat": "{{label_nam{{kubernetes_namespace}} {{kubernetes_name}}e}}"
    }
   ]
  },
  {
   "title": "Hikari IDLE Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 107 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(hikaricp_idle_connections{kubernetes_namespace=~\".+\", kubernetes_name=~\".+\",  pool=~\".+\"}) *100/ (hikaricp_max_connections{kubernetes_namespace=~\".+\", kubernetes_name=~\".+\",  pool=~\".+\"})",
     "legendFormat": "Idle_connections {{kubernetes_namespace}}_{{kubernetes_name}}_{{pool}}"
    }
   ]
  },
  {
   "title": "Hikari ACTIVE Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 107 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(hikaricp_active_connections{kubernetes_namespace=~\".+\", kubernetes_name=~\".+\",  pool=~\".+\"}) *100/ (hikaricp_max_connections{kubernetes_namespace=~\".+\", kubernetes_name=~\".+\",  pool=~\".+\"})",
     "legendFormat": "Active_connections {{kubernetes_namespace}}_{{kubernetes_name}}/{{instance}}_{{pool}}"
    }
   ]
  },
  {
   "title": "99th Latency SLO over ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 115 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "\n(sum_over_time((histogram_quantile(0.99, sum(rate(service_request_seconds_bucket{kubernetes_namespace=~\".+\", kubernetes_name=~\"authorizationservice-v1|authservice-v1|authservicejwt-v1|kbservice-v1|mlservice-v1|pageservice-v1|policyservice-v1|roleservice-v1|umservice-v1|userdataservice-v1\", method!=\"OPTION\"}[$__rate_interval]) )  by (le,kubernetes_name,kubernetes_namespace))  <= bool 0.5) [5m:] )            \n/\nsum_over_time((sum(rate(service_request_seconds_count{kubernetes_namespace=~\".+\", kubernetes_name=~\"authorizationservice-v1|authservice-v1|authservicejwt-v1|kbservice-v1|mlservice-v1|pageservice-v1|policyservice-v1|roleservice-v1|umservice-v1|userdataservice-v1\", method!=\"OPTION\"}[$__rate_interval])) by (kubernetes_name,kubernetes_namespace) > bool 0) [5m:]))*100",
     "legendFormat": "99-th slo_{{kubernetes_namespace}}_{{kubernetes_name}}"
    }
   ]
  },
  {
   "title": "SVC Endpoints",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 115 },
   "targets": [
    {
     "expr": "kube_endpoint_address_available{namespace!~\"lts-caladan|lts-geghamasar|lts-arrakis|predev2|predev1|haltest|perftesting|kube-system|kube-public|kube-node-lease|default|velero|dev2|dev5|dev7|dev11|dev12|dev14|staging2|ejpdev|keller|devkeller|mcp-infrastructure|bigchaindb|chatwoot|argocd|metallb-system|hal|randomcoffee|projecttracker\", endpoint!~\"elasticsearch.*|rabbitmq.*|redis.*|ingress.*|postgres.*|fullsyncservice-v1|.*cluster.local.*|example.com-nfs|encryptionservice-v1|changedeploymentservice-v1\"} ==0",
     "legendFormat": "{{namespace}} {{endpoint}}"
    }
   ]
  },
  {
   "title": "GC collection time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 123 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(jvm_gc_collection_seconds_sum[$__rate_interval])",
     "legendFormat": "{{kubernetes_namespace}} {{kubernetes_name}} {{gc}}"
    }
   ]
  }
 ]
}