{
 "title": "DB-Alerting",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "PG Number of Connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance)(pg_stat_database_numbackends{instance=~\".+:9187\", job=\"postgres services\"})*100/sum by (instance) (pg_settings_max_connections{instance=~\".+:9187\", job=\"postgres services\"})",
     "legendFormat": "{{instance}} "
    }
   ]
  },
  {
   "title": "PG Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "100 - (node_memory_MemFree_bytes{instance=~\".+:9100\", job=\"DB-Servers\"} *100)/node_memory_MemTotal_bytes{instance=~\".+:9100\", job=\"DB-Servers\"}",
     "legendFormat": "{{service}}"
    },
    {
     "expr": "container_memory_working_set_bytes{container=~\"postgres.*\", container!~\"postgres-exporter.*\"} /container_spec_memory_limit_bytes{container=~\"postgres.*\", container!~\"postgres-exporter.*\"}",
     "legendFormat": "{{cluster}} {{namespace}} {{container}} "
    }
   ]
  },
  {
   "title": "PG UP",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "pg_up{kubernetes_name!~\".+exporter.+\"} or up{environment=\"cluster1\",instance=\"postgresql15\"}",
     "legendFormat": "{{environment}} {{service}}"
    }
   ]
  }
 ]
}