{
 "title": "DBA Monitoring",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Daily Backups Status",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "pg_backup_status_daily_backup_status{backup_type=\"daily_backup\",instance=~\".+:9187\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Weekly Backups Status",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "pg_backup_status_weekly_backup_status{backup_type=\"weekly_backup\",instance=~\".+:9187\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Monthly Backups Status",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "pg_backup_status_monthly_backup_status{backup_type=\"monthly_backup\",instance=~\".+:9187\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "PG Active Long Running Sessions",
   "type": "timeseries",
   "description": "queries running more than 15 minutes",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 },
   "targets": [
    {
     "expr": "dbmon_pg_active_sessions_count{instance=~\".+:9187\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "User Connection Count",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "dbmon_pg_user_connection_count{instance=~\".+:9187\"}",
     "legendFormat": "{{user_name}} - {{db_name}} - {{client_ip}} - {{state}}"
    }
   ]
  },
  {
   "title": "PG Up Alert",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 6 },
   "targets": [
    {
     "expr": "pg_up{instance=~\".+:9187\"}"
    }
   ]
  },
  {
   "title": "postgresql status systemctl",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 6 },
   "targets": [
    {
     "expr": "node_systemd_unit_state{name=~\"postgresql-.+.service\",state=\"active\",instance=~\".+:9100\"}"
    }
   ]
  },
  {
   "title": "RAM used",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (node_memory_MemAvailable_bytes{service=~\"postgres.+\"} *100)/node_memory_MemTotal_bytes{service=~\"postgres.+\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU Busy ",
   "type": "timeseries",
   "description": "Busy state of all CPU cores together",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (irate(node_cpu_seconds_total{mode=\"idle\",service=~\"postgres.+\"}[$__rate_interval])) * 100)  ",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Disk Use",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{service=~\"postgres.+\"} * 100) / node_filesystem_size_bytes{service=~\"postgres.+\"})",
     "legendFormat": "{{instance}}-{{mountpoint}}"
    }
   ]
  },
  {
   "title": "Disk IOps",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "irate(node_disk_reads_completed_total{service=~\"postgres.+\",device=~\"[a-z]*[a-z]\"}[$__rate_interval])",
     "legendFormat": "{{instance}}-{{device}} - Reads completed"
    },
    {
     "expr": "irate(node_disk_writes_completed_total{service=~\"postgres.+\",device=~\"[a-z]*[a-z]\"}[$__rate_interval])",
     "legendFormat": "{{instance}}-{{device}} - Writes completed"
    }
   ]
  }
 ]
}