{
 "title": "DBA - PostgreSQL Database",
 "description": "This dashboard works with postgres_exporter for prometheus",
 "tags": [
  "postgres",
  "db",
  "stats"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "instance", "label": "Instance", "query": { "query": "label_values(pg_up, instance)" } },
   { "name": "datname", "label": "Database", "query": { "query": "label_values(datname)" } },
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,5m,1h,6h,1d" },
   { "name": "node_exporter_port", "query": "9100" }
  ]
 },
 "panels": [
  {
   "title": "General Counters, CPU, Memory and File Descriptor Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU Busy",
   "type": "gauge",
   "description": "Busy state of all CPU cores together",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(((count(count(node_cpu_seconds_total{instance=~\"$instance:$node_exporter_port\"}) by (cpu))) - avg(sum by (mode)(irate(node_cpu_seconds_total{mode='idle',instance=~\"$instance:$node_exporter_port\"}[$__rate_interval])))) * 100) / count(count(node_cpu_seconds_total{instance=~\"$instance:$node_exporter_port\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "RAM used",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(node_memory_MemTotal_bytes{instance=\"$instance:$node_exporter_port\"} - (node_memory_MemFree_bytes{instance=\"$instance:$node_exporter_port\"} + node_memory_Buffers_bytes{instance=\"$instance:$node_exporter_port\"} + node_memory_Cached_bytes{instance=\"$instance:$node_exporter_port\"})) / node_memory_MemTotal_bytes{instance=\"$instance:$node_exporter_port\"} * 100",
     "legendFormat": "Used"
    }
   ]
  },
  {
   "title": "RAM cached",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(node_memory_Cached_bytes{instance=\"$instance:$node_exporter_port\"} * 100) / node_memory_MemTotal_bytes{instance=\"$instance:$node_exporter_port\"}",
     "legendFormat": "Used"
    }
   ]
  },
  {
   "title": "Current IOwait",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(node_cpu_seconds_total{instance=\"instance:$node_exporter_port\", mode=\"iowait\"}[$__rate_interval])) by (mode)* 100 / scalar(count(node_cpu_seconds_total{mode=\"user\", instance=\"$instance:$node_exporter_port\"})) or sum(irate(node_cpu_seconds_total{instance=\"$instance:$node_exporter_port\", mode=\"iowait\"}[$__rate_interval])) by (mode) * 100 / scalar(count(node_cpu_seconds_total{mode=\"user\", instance=\"$instance:$node_exporter_port\"}))",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "Number of Connections",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pg_stat_database_numbackends{datname=~\"$datname\",instance=~\"$instance.*\"})"
    },
    { "expr": "connec" }
   ]
  },
  {
   "title": "Connections",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(avg_over_time(pg_stat_activity_count{instance=~\"$instance.*\"}[$__interval])) /\nsum(pg_settings_max_connections{instance=~\"$instance.*\"})"
    }
   ]
  },
  {
   "title": "QPS",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(pg_stat_database_xact_commit{datname=~\"$datname\",instance=~\"$instance.*\"}[$__rate_interval])) + sum(irate(pg_stat_database_xact_rollback{datname=~\"$datname\",instance=~\"$instance.*\"}[$__rate_interval]))",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "postgresql",
     "select": [
      [
       { "params": [ "xact_commit" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Current fetch data",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "SUM(pg_stat_database_tup_fetched{datname=~\"$datname\", instance=~\"$instance.*\"})"
    }
   ]
  },
  {
   "title": "Current insert data",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 19, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "SUM(pg_stat_database_tup_inserted{instance=~\"$instance.*\"})"
    }
   ]
  },
  {
   "title": "Current update data",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "SUM(pg_stat_database_tup_updated{datname=~\"$datname\", instance=~\"$instance.*\"})"
    }
   ]
  },
  {
   "title": "Start Time",
   "type": "stat",
   "description": "start time of the process",
   "gridPos": { "h": 2, "w": 3, "x": 16, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "process_start_time_seconds{instance=~\"$instance.*\",job=~\".*Servers\"} * 1000"
    }
   ]
  },
  {
   "title": "Max Connections",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 19, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "pg_settings_max_connections{instance=~\"$instance.*\"}"
    }
   ]
  },
  {
   "title": "Average CPU Usage",
   "type": "timeseries",
   "description": "Average user and system CPU time spent in seconds.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (instance)(rate(node_cpu_seconds_total{mode=\"system\",instance=~\"$instance:$node_exporter_port\"}[$__rate_interval])) * 100",
     "legendFormat": "Busy System"
    },
    {
     "expr": "sum by (instance)(rate(node_cpu_seconds_total{mode=\"user\",instance=~\"$instance:$node_exporter_port\"}[$__rate_interval])) * 100",
     "legendFormat": "Busy User"
    },
    {
     "expr": "sum by (instance)(rate(node_cpu_seconds_total{mode=\"iowait\",instance=~\"$instance:$node_exporter_port\"}[$__rate_interval])) * 100",
     "legendFormat": "Busy Iowait"
    },
    {
     "expr": "sum by (instance)(rate(node_cpu_seconds_total{mode=\".*irq\",instance=~\"$instance:$node_exporter_port\"}[$__rate_interval])) * 100",
     "legendFormat": "Busy IRQs"
    },
    {
     "expr": "sum by (instance)(rate(node_cpu_seconds_total{mode!='idle',mode!='user',mode!='system',mode!='iowait',mode!='irq',mode!='softirq',instance=~\"$instance:$node_exporter_port\"}[$__rate_interval])) * 100",
     "legendFormat": "Busy Other"
    },
    {
     "expr": "sum by (instance)(rate(node_cpu_seconds_total{mode=\"idle\",instance=~\"$instance:$node_exporter_port\"}[$__rate_interval])) * 100",
     "legendFormat": "Idle"
    }
   ]
  },
  {
   "title": "Average Memory Usage",
   "type": "timeseries",
   "description": "Virtual and Resident memory size in bytes, averages over 5 min interval",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$instance:$node_exporter_port\"}",
     "legendFormat": "RAM Total"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$instance:$node_exporter_port\"} - node_memory_MemFree_bytes{instance=~\"$instance:$node_exporter_port\"} - (node_memory_Cached_bytes{instance=~\"$instance:$node_exporter_port\"} + node_memory_Buffers_bytes{instance=~\"$instance:$node_exporter_port\"})",
     "legendFormat": "RAM Used"
    },
    {
     "expr": "node_memory_Cached_bytes{instance=~\"$instance:$node_exporter_port\"} + node_memory_Buffers_bytes{instance=~\"$instance:$node_exporter_port\"}",
     "legendFormat": "RAM Cache + Buffer"
    },
    {
     "expr": "node_memory_MemFree_bytes{instance=~\"$instance:$node_exporter_port\"}",
     "legendFormat": "RAM Free"
    },
    {
     "expr": "(node_memory_SwapTotal_bytes{instance=~\"$instance:$node_exporter_port\"} - node_memory_SwapFree_bytes{instance=~\"$instance:$node_exporter_port\"})",
     "legendFormat": "SWAP Used"
    }
   ]
  },
  {
   "title": "Network Traffic Basic",
   "type": "timeseries",
   "description": "Basic network info per interface",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{instance=~\"$instance:$node_exporter_port\"}[$__rate_interval])",
     "legendFormat": "recv {{device}}"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total{instance=~\"$instance:$node_exporter_port\"}[$__rate_interval])",
     "legendFormat": "trans {{device}} "
    }
   ]
  },
  {
   "title": "Disk Use",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{instance=~\"$instance:$node_exporter_port\"} * 100) / node_filesystem_size_bytes{instance=~\"$instance:$node_exporter_port\"})",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "Disk IOps",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "irate(node_disk_reads_completed_total{instance=~\"$instance:$node_exporter_port\",device=~\"[a-z]*[a-z]\"}[$__rate_interval])",
     "legendFormat": "{{device}} - Reads completed"
    },
    {
     "expr": "irate(node_disk_writes_completed_total{instance=~\"$instance:$node_exporter_port\",device=~\"[a-z]*[a-z]\"}[$__rate_interval])",
     "legendFormat": "{{device}} - Writes completed"
    }
   ]
  },
  {
   "title": "I/O Usage Read / Write",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "irate(node_disk_read_bytes_total{instance=~\"$instance:$node_exporter_port\",device=~\"[a-z]*[a-z]\"}[$__rate_interval])",
     "legendFormat": "{{device}} - Successfully read bytes"
    },
    {
     "expr": "irate(node_disk_written_bytes_total{instance=~\"$instance:$node_exporter_port\",device=~\"[a-z]*[a-z]\"}[$__rate_interval])",
     "legendFormat": "{{device}} - Successfully written bytes"
    }
   ]
  },
  {
   "title": "Disk R/W Time",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "irate(node_disk_read_time_seconds_total{instance=~\"$instance:$node_exporter_port\"}[$__rate_interval])",
     "legendFormat": "{{device}} - Read time ms"
    },
    {
     "expr": "irate(node_disk_write_time_seconds_total{instance=~\"$instance:$node_exporter_port\"}[$__rate_interval])",
     "legendFormat": "{{device}} - Write time ms"
    }
   ]
  },
  {
   "title": "Disk IOs Weighted",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "irate(node_disk_io_time_weighted_seconds_total{instance=~\"$instance:$node_exporter_port\"}[$__rate_interval])",
     "legendFormat": "{{device}} - IO time weighted"
    }
   ]
  },
  {
   "title": "Settings",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Shared Buffers",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_settings_shared_buffers_bytes{instance=~\"$instance.*\"}"
    }
   ]
  },
  {
   "title": "Effective Cache",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_settings_effective_cache_size_bytes{instance=~\"$instance.*\"}"
    }
   ]
  },
  {
   "title": "Maintenance Work Mem",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_settings_maintenance_work_mem_bytes{instance=~\"$instance.*\"}"
    }
   ]
  },
  {
   "title": "Work Mem",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_settings_work_mem_bytes{instance=~\"$instance.*\"}"
    }
   ]
  },
  {
   "title": "Max WAL Size",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_settings_max_wal_size_bytes{instance=~\"$instance.*\"}"
    }
   ]
  },
  {
   "title": "Random Page Cost",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_settings_random_page_cost{instance=~\"$instance.*\"}"
    }
   ]
  },
  {
   "title": "Max Worker Processes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "pg_settings_max_worker_processes{instance=~\"$instance.*\"}"
    }
   ]
  },
  {
   "title": "Max Parallel Workers",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_settings_max_parallel_workers{instance=~\"$instance.*\"}"
    }
   ]
  },
  {
   "title": "pg_settings_max_files_per_process ",
   "type": "stat",
   "description": "pg_settings_max_files_per_process ",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_settings_max_files_per_process {instance=~\"$instance.*\"}"
    }
   ]
  },
  {
   "title": "pg_settings_ssl ",
   "type": "stat",
   "description": "pg_settings_ssl ",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_settings_ssl {instance=~\"$instance.*\"}"
    }
   ]
  },
  {
   "title": "pg_settings_track_activity_query_size ",
   "type": "stat",
   "description": "# HELP pg_settings_track_activity_query_size Sets the size reserved for pg_stat_activity.query, in bytes.",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "pg_settings_track_activity_query_size {instance=~\"$instance.*\"}"
    }
   ]
  },
  {
   "title": "pg_settings_track_commit_timestamp ",
   "type": "stat",
   "description": "HELP pg_settings_track_commit_timestamp Collects transaction commit time.",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_settings_track_commit_timestamp {instance=~\"$instance.*\"}"
    }
   ]
  },
  {
   "title": "pg_settings_track_counts ",
   "type": "stat",
   "description": "HELP pg_settings_track_counts Collects statistics on database activity.",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_settings_track_counts {instance=~\"$instance.*\"}"
    }
   ]
  },
  {
   "title": "pg_settings_commit_delay",
   "type": "stat",
   "description": "HELP pg_settings_commit_delay Sets the delay in microseconds between transaction commit and flushing WAL to disk.",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_settings_commit_delay{instance=~\"$instance.*\"}"
    }
   ]
  },
  {
   "title": "pg_settings_checkpoint_warning_seconds",
   "type": "stat",
   "description": "pg_settings_checkpoint_warning_seconds",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_settings_checkpoint_warning_seconds{instance=~\"$instance.*\"}"
    }
   ]
  },
  {
   "title": "pg_settings_deadlock_timeout_seconds ",
   "type": "stat",
   "description": "pg_settings_deadlock_timeout_seconds ",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_settings_deadlock_timeout_seconds {instance=~\"$instance.*\"}"
    }
   ]
  },
  {
   "title": "pg_settings_effective_io_concurrency ",
   "type": "stat",
   "description": "# HELP pg_settings_effective_io_concurrency Number of simultaneous requests that can be handled efficiently by the disk subsystem.",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_settings_effective_io_concurrency {instance=~\"$instance.*\"}"
    }
   ]
  },
  {
   "title": "pg_settings_idle_in_transaction_session_timeout_seconds ",
   "type": "stat",
   "description": "# HELP pg_settings_idle_in_transaction_session_timeout_seconds Sets the maximum allowed duration of any idling transaction. [Units converted to seconds.]",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_settings_idle_in_transaction_session_timeout_seconds {instance=~\"$instance.*\"}"
    }
   ]
  },
  {
   "title": "pg_settings_maintenance_work_mem_in_GB",
   "type": "stat",
   "description": "# HELP pg_settings_maintenance_work_mem_bytes Sets the maximum memory to be used for maintenance operations. [Units converted to bytes.]",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_settings_maintenance_work_mem_bytes {instance=~\"$instance.*\"}/1024/1024/1024"
    }
   ]
  },
  {
   "title": "Transactions/Sessions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Transactions",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(pg_stat_database_xact_commit{instance=~\"$instance.*\", datname=~\"$datname\"}[$__rate_interval])",
     "legendFormat": "{{datname}} commits"
    },
    {
     "expr": "irate(pg_stat_database_xact_rollback{instance=~\"$instance.*\", datname=~\"$datname\"}[$__rate_interval])",
     "legendFormat": "{{datname}} rollbacks"
    }
   ]
  },
  {
   "title": "Number of  connections per database",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk(10,pg_stat_database_numbackends{datname=~\"$datname\",instance=~\"$instance.*\"})",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Longest Transaction",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "pg_stat_activity_max_tx_duration{instance=~\"$instance.*\"}",
     "legendFormat": "{{datname}} max_tx_duration [{{state}}]"
    }
   ]
  },
  {
   "title": "Active sessions",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "pg_stat_activity_count{datname=~\"$datname\", instance=~\"$instance.*\", state=\"active\"} !=0",
     "legendFormat": "{{datname}}, s: {{state}}"
    }
   ]
  },
  {
   "title": "Max duration in seconds any active transaction has been running",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "targets": [
    {
     "expr": "topk(20,pg_stat_activity_max_tx_duration{datname=~\"$datname\",instance=~\"$instance.*\", state='active'})",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Idle sessions",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk(10,pg_stat_activity_count{datname=~\"$datname\", instance=~\"$instance.*\", state=~\"idle|idle in transaction|idle in transaction (aborted)\"})",
     "legendFormat": "{{datname}}, s: {{state}}"
    }
   ]
  },
  {
   "title": "Transactions rollbacks",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(pg_stat_database_xact_rollback{instance=~\"$instance.*\"}[$__rate_interval]) ",
     "legendFormat": "{{datname}} rollbacks"
    }
   ]
  },
  {
   "title": "Transactions commits",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(pg_stat_database_xact_commit{instance=~\"$instance.*\"}[$__rate_interval]) > 1",
     "legendFormat": "{{datname}} commits"
    }
   ]
  },
  {
   "title": "Database Stats DML",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 61 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Fetch data (SELECT)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 62 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "pg_stat_database_tup_fetched{datname=~\"$datname\", instance=~\"$instance.*\"} != 0",
       "legendFormat": "{{datname}}"
      }
     ]
    },
    {
     "title": "Insert data",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 62 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "pg_stat_database_tup_inserted{datname=~\"$datname\", instance=~\"$instance.*\"} != 0",
       "legendFormat": "{{datname}}"
      }
     ]
    },
    {
     "title": "Update data",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 62 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "pg_stat_database_tup_updated{datname=~\"$datname\", instance=~\"$instance.*\"} != 0",
       "legendFormat": "{{datname}}"
      }
     ]
    },
    {
     "title": "Return data",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 69 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "pg_stat_database_tup_returned{datname=~\"$datname\", instance=~\"$instance.*\"} != 0",
       "legendFormat": "{{datname}}"
      }
     ]
    },
    {
     "title": "Delete data",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 69 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "pg_stat_database_tup_deleted{datname=~\"$datname\", instance=~\"$instance.*\"} != 0",
       "legendFormat": "{{datname}}"
      }
     ]
    },
    {
     "title": "Read Stats",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 69 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "irate(pg_stat_database_tup_fetched{instance=~\"$instance.*\"}[$__rate_interval])",
       "legendFormat": "{{datname}} SELECT (index scan)"
      },
      {
       "expr": "irate(pg_stat_database_tup_returned{instance=~\"$instance.*\"}[$__rate_interval])",
       "legendFormat": "{{datname}} SELECT (table scan)"
      }
     ]
    }
   ]
  },
  {
   "title": "Cache/Buffers/Temps",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 62 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Cache Hit Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "pg_stat_database_blks_hit{instance=~\"$instance.*\", datname=~\"$datname\"} / (pg_stat_database_blks_read{instance=~\"$instance.*\", datname=~\"$datname\"} + pg_stat_database_blks_hit{instance=~\"$instance.*\", datname=~\"$datname\"})",
     "legendFormat": "{{ datname }}"
    }
   ]
  },
  {
   "title": "Buffers (bgwriter)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(pg_stat_bgwriter_buffers_backend{instance=~\"$instance.*\"}[$__rate_interval])",
     "legendFormat": "buffers_backend"
    },
    {
     "expr": "irate(pg_stat_bgwriter_buffers_alloc{instance=~\"$instance.*\"}[$__rate_interval])",
     "legendFormat": "buffers_alloc"
    },
    {
     "expr": "irate(pg_stat_bgwriter_buffers_backend_fsync{instance=~\"$instance.*\"}[$__rate_interval])",
     "legendFormat": "backend_fsync"
    },
    {
     "expr": "irate(pg_stat_bgwriter_buffers_checkpoint{instance=~\"$instance.*\"}[$__rate_interval])",
     "legendFormat": "buffers_checkpoint"
    },
    {
     "expr": "irate(pg_stat_bgwriter_buffers_clean{instance=~\"$instance.*\"}[$__rate_interval])",
     "legendFormat": "buffers_clean"
    }
   ]
  },
  {
   "title": "Temp File (Bytes)",
   "type": "timeseries",
   "description": "Total amount of data written to temporary files by queries in this database. All temporary files are counted, regardless of why the temporary file was created, and regardless of the log_temp_files setting.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "irate(pg_stat_database_temp_bytes{instance=~\"$instance.*\", datname=~\"$datname\"}[$__rate_interval])",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Locks/Deadlocks/Latencies",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 70 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Lock tables",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "pg_locks_count{datname=~\"$datname\", instance=~\"$instance.*\"} != 0",
     "legendFormat": "{{datname}},{{mode}}"
    }
   ]
  },
  {
   "title": "Conflicts/Deadlocks",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(pg_stat_database_conflicts{instance=~\"$instance.*\", datname=~\"$datname\"}[$__rate_interval])",
     "legendFormat": "{{datname}} conflicts"
    },
    {
     "expr": "irate(pg_stat_database_deadlocks{instance=~\"$instance.*\", datname=~\"$datname\"}[$__rate_interval])",
     "legendFormat": "{{datname}} deadlocks"
    }
   ]
  },
  {
   "title": "Disk Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "(rate(node_disk_read_time_seconds_total{device=~\".+\", instance=\"$instance:$node_exporter_port\"}[$__rate_interval]) / rate(node_disk_reads_completed_total{device=~\".+\", instance=\"$instance:$node_exporter_port\"}[$__rate_interval])) or (irate(node_disk_read_time_seconds_total{device=~\".+\", instance=\"$instance:$node_exporter_port\"}[$__rate_interval]) / irate(node_disk_reads_completed_total{device=~\".+\", instance=\"$instance:$node_exporter_port\"}[$__rate_interval]))",
     "legendFormat": "Write: {{ device }}"
    }
   ]
  },
  {
   "title": "Aditional Info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 78 },
   "targets": [
    {}
   ]
  },
  {
   "title": "go_memstats_heap_objects ",
   "type": "stat",
   "description": "go_memstats_heap_objects ",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 79 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "go_memstats_heap_objects{instance=~\"$instance.*\"}"
    }
   ]
  },
  {
   "title": "process_max_fds ",
   "type": "stat",
   "description": "# HELP process_max_fds Maximum number of open file descriptors.",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 79 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(process_max_fds {instance=~\"$instance.*\"})"
    }
   ]
  },
  {
   "title": "process_cpu_seconds_total ",
   "type": "stat",
   "description": "HELP process_cpu_seconds_total Total user and system CPU time spent in seconds.",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 79 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(process_cpu_seconds_total {instance=~\"$instance.*\"})"
    }
   ]
  },
  {
   "title": "process_open_fds ",
   "type": "stat",
   "description": "HELP process_open_fds Number of open file descriptors.",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 79 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(process_open_fds {instance=~\"$instance.*\"})"
    }
   ]
  },
  {
   "title": "process_resident_memory_in_MB",
   "type": "stat",
   "description": "# HELP process_resident_memory_bytes Resident memory size in Mega bytes.",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 79 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(process_resident_memory_bytes {instance=~\"$instance.*\"})/1024/1024"
    }
   ]
  },
  {
   "title": "process_start_time_days",
   "type": "stat",
   "description": "HELP process_start_time_seconds Start time of the process since unix epoch in seconds.",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 79 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(process_start_time_seconds {instance=~\"$instance.*\"})/60/60/24"
    }
   ]
  },
  {
   "title": "process_virtual_memory_megabytes ",
   "type": "stat",
   "description": "HELP process_virtual_memory_bytes Virtual memory size in Mega bytes.",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 79 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(process_virtual_memory_bytes {instance=~\"$instance.*\"})/1024/1024"
    }
   ]
  },
  {
   "title": "pg_stat_database_numbackends ",
   "type": "stat",
   "description": "HELP pg_stat_database_numbackends Number of backends currently connected to this database. This is the only column in this view that returns a value reflecting current state; all other columns return the accumulated values since the last reset.",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 79 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(pg_stat_database_numbackends {instance=~\"$instance.*\"})"
    }
   ]
  },
  {
   "title": "Open File Descriptors",
   "type": "timeseries",
   "description": "Number of open file descriptors",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "process_open_fds{instance=~\"$instance.*\"}",
     "legendFormat": "Open FD"
    }
   ]
  },
  {
   "title": "pg_stat_activity_count ",
   "type": "stat",
   "description": "HELP pg_stat_activity_count number of connections in this state",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 82 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(pg_stat_activity_count{instance=~\"$instance.*\"})"
    }
   ]
  },
  {
   "title": "pg_stat_database_blk_read_time ",
   "type": "stat",
   "description": "# HELP pg_stat_database_blk_read_time Time spent reading data file blocks by backends in this database, in milliseconds",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 82 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(pg_stat_database_blk_read_time {instance=~\"$instance.*\"})"
    }
   ]
  },
  {
   "title": "pg_stat_database_conflicts ",
   "type": "stat",
   "description": "HELP pg_stat_database_conflicts Number of queries canceled due to conflicts with recovery in this database. (Conflicts occur only on standby servers; see pg_stat_database_conflicts for details.)",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 82 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(pg_stat_database_conflicts {instance=~\"$instance.*\"})"
    }
   ]
  },
  {
   "title": "pg_stat_database_conflicts_confl_deadlock ",
   "type": "stat",
   "description": "HELP pg_stat_database_conflicts_confl_deadlock Number of queries in this database that have been canceled due to deadlocks",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 82 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(pg_stat_database_conflicts_confl_deadlock {instance=~\"$instance.*\"})"
    }
   ]
  },
  {
   "title": "pg_stat_database_conflicts_confl_tablespace ",
   "type": "stat",
   "description": "HELP pg_stat_database_conflicts_confl_tablespace Number of queries in this database that have been canceled due to dropped tablespaces",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 82 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(pg_stat_database_conflicts_confl_tablespace {instance=~\"$instance.*\"})"
    }
   ]
  },
  {
   "title": "pg_stat_database_temp_files ",
   "type": "stat",
   "description": "HELP pg_stat_database_temp_files Number of temporary files created by queries in this database. All temporary files are counted, regardless of why the temporary file was created (e.g., sorting or hashing), and regardless of the log_temp_files setting.",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 82 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(pg_stat_database_temp_files {instance=~\"$instance.*\"})"
    }
   ]
  },
  {
   "title": "pg_stat_database_numbackends ",
   "type": "stat",
   "description": "HELP pg_stat_database_numbackends Number of backends currently connected to this database. This is the only column in this view that returns a value reflecting current state; all other columns return the accumulated values since the last reset.",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 82 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(pg_stat_database_numbackends {instance=~\"$instance.*\"})"
    }
   ]
  },
  {
   "title": "process_virtual_memory_max_bytes ",
   "type": "stat",
   "description": "HELP process_virtual_memory_max_bytes Maximum amount of virtual memory available in bytes.",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 82 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "process_virtual_memory_max_bytes {instance=~\"$instance.*\"}"
    }
   ]
  },
  {
   "title": "pg_stat_database_tup_deleted",
   "type": "timeseries",
   "description": "pg_stat_database_tup_deleted",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(pg_stat_database_tup_deleted{instance=~\"$instance.*\",datname=~\"$datname\"})"
    },
    {
     "expr": "sum(pg_stat_database_tup_inserted{instance=~\"$instance.*\",datname=~\"$datname\"})"
    },
    {
     "expr": "sum(pg_stat_database_tup_updated{instance=~\"$instance.*\",datname=~\"$datname\"})"
    },
    {
     "expr": "sum(pg_stat_database_tup_fetched{instance=~\"$instance.*\",datname=~\"$datname\"})"
    },
    {
     "expr": "sum(pg_stat_database_tup_returned{instance=~\"$instance.*\",datname=~\"$datname\"})"
    }
   ]
  },
  {
   "title": "pg_stat_database_numbackends ",
   "type": "timeseries",
   "description": "# HELP pg_stat_database_numbackends Number of backends currently connected to this database. This is the only column in this view that returns a value reflecting current state; all other columns return the accumulated values since the last reset.",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(pg_stat_database_numbackends {instance=~\"$instance.*\"})"
    }
   ]
  },
  {
   "title": "Checkpoint Stats",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "irate(pg_stat_bgwriter_checkpoint_write_time{instance=~\"$instance.*\"}[$__rate_interval])",
     "legendFormat": "write_time - Total amount of time that has been spent in the portion of checkpoint processing where files are written to disk."
    },
    {
     "expr": "irate(pg_stat_bgwriter_checkpoint_sync_time{instance=~\"$instance.*\"}[$__rate_interval])",
     "legendFormat": "sync_time - Total amount of time that has been spent in the portion of checkpoint processing where files are synchronized to disk."
    }
   ]
  }
 ]
}