{
 "title": "DBA Percentiles Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "server", "label": "server", "query": { "query": "label_values(pg_up,instance)" } },
   {
    "name": "db_name",
    "label": "db_name",
    "query": {
     "query": "label_values(pg_query_execution_count{instance=~\"$server\"},db_name)  "
    }
   },
   {
    "name": "user_name",
    "label": "user_name",
    "query": {
     "query": "label_values(pg_query_execution_count{instance=~\"$server\", db_name=~\"$db_name\"}, user_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Execution Count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "pg_query_execution_count{db_name=~\"$db_name\",instance=~\"$server\", user_name=~\"$user_name\"}",
     "legendFormat": "{{user_name}}"
    }
   ]
  },
  {
   "title": "Execution Time 75",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "pg_query_execution_time_75{db_name=~\"$db_name\", instance=~\"$server\", user_name=~\"$user_name\"}",
     "legendFormat": "{{user_name}}"
    }
   ]
  },
  {
   "title": "Execution Time 95",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "pg_query_execution_time_95{db_name=~\"$db_name\", instance=~\"$server\", user_name=~\"$user_name\"}",
     "legendFormat": "{{user_name}}"
    }
   ]
  },
  {
   "title": "Execution Time 99",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "pg_query_execution_time_99{db_name=~\"$db_name\", instance=~\"$server\", user_name=~\"$user_name\"}",
     "legendFormat": "{{user_name}}"
    }
   ]
  },
  {
   "title": "Execution Time Max",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "pg_query_execution_time_max{db_name=~\"$db_name\", instance=~\"$server\", user_name=~\"$user_name\"}",
     "legendFormat": "{{user_name}}"
    }
   ]
  }
 ]
}