{
 "title": "DBA Monitoring PostgreSQL - Synergy Development Servers",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "instance", "label": "instance", "query": { "query": "label_values(pg_up,instance)" } },
   {
    "name": "db_name",
    "label": "db_name",
    "query": {
     "query": "label_values(dbmon_pg_user_connection_count{instance=\"$instance:9187\"},db_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "RAM used",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (node_memory_MemAvailable_bytes{instance=~\"$instance:9100\",job=\"DB-Servers\"} *100)/node_memory_MemTotal_bytes{instance=~\"$instance:9100\",job=\"DB-Servers\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU Busy ",
   "type": "timeseries",
   "description": "Busy state of all CPU cores together",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(((count(count(node_cpu_seconds_total{instance=~\"$instance:9100\",job=\"DB-Servers\"}) by (cpu))) - avg(sum by (mode)(irate(node_cpu_seconds_total{mode='idle',instance=~\"$instance:9100\",job=\"DB-Servers\"}[5m])))) * 100) / count(count(node_cpu_seconds_total{instance=~\"$instance:9100\",job=\"DB-Servers\"}) by (cpu))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Disk Use",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{instance=~\"$instance:9100\",job=\"DB-Servers\"} * 100) / node_filesystem_size_bytes{instance=~\"$instance:9100\",job=\"DB-Servers\"})",
     "legendFormat": "{{instance}}-{{mountpoint}}"
    }
   ]
  },
  {
   "title": "Disk IOps",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "irate(node_disk_reads_completed_total{instance=~\"$instance:9100\",device=~\"[a-z]*[a-z]\"}[$__rate_interval])",
     "legendFormat": "{{instance}}-{{device}} - Reads completed"
    },
    {
     "expr": "irate(node_disk_writes_completed_total{instance=~\"$instance:9100\",device=~\"[a-z]*[a-z]\"}[$__rate_interval])",
     "legendFormat": "{{instance}}-{{device}} - Writes completed"
    }
   ]
  },
  {
   "title": "User Connection Count",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "dbmon_pg_user_connection_count{instance=~\"$instance:9187\", db_name=~\"$db_name\"}",
     "legendFormat": "{{user_name}} - {{db_name}} - {{client_ip}} - {{state}}"
    }
   ]
  },
  {
   "title": "Daily Backups Status",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "pg_backup_status_daily_backup_status{backup_type=\"daily_backup\",instance=~\"$instance:9187\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Azure Daily Backups Status",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 18 },
   "targets": [
    {
     "expr": "pg_backup_status_daily_azure_backup_status{backup_type=\"daily_backup_azure\",instance=~\"$instance:9187\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "NFS Daily Backups Status",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "pg_backup_status_daily_nfs_backup_status{backup_type=\"daily_backup_nfs\",instance=~\"$instance:9187\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "PG Active Long Running Sessions",
   "type": "stat",
   "description": "queries running more than 15 minutes",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dbmon_pg_active_sessions_count{instance=~\"$instance:9187\"}"
    }
   ]
  },
  {
   "title": "PG Up",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "pg_up{instance=~\"$instance:9187\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "postgresql status systemctl",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 24 },
   "targets": [
    {
     "expr": "node_systemd_unit_state{name=~\"postgresql-.+.service\",state=\"active\",instance=~\"$instance:9100\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "PostgreSQL Master Items",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "pg_stat_replication",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 31 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "dbmon_pg_monitoring_replication_presence{instance=~\".+:9187\"}"
      }
     ]
    },
    {
     "title": "repmgr status",
     "type": "timeseries",
     "gridPos": { "h": 4, "w": 4, "x": 4, "y": 31 },
     "targets": [
      {
       "expr": "node_systemd_unit_state{name=\"repmgr.service\",state=\"active\",instance=\"sis2s059:9100\"}"
      }
     ]
    },
    {
     "title": "keepalived status systemctl",
     "type": "timeseries",
     "gridPos": { "h": 4, "w": 4, "x": 8, "y": 31 },
     "targets": [
      {
       "expr": "node_systemd_unit_state{name=\"keepalived.service\",state=\"active\",instance=\"sis2s059:9100\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "PostgreSQL Slave Items",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "targets": [
    {}
   ]
  },
  {
   "title": "upstream is node1",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dbmon_pg_monitoring_replication_presence{instance=~\".+:9187\"}"
    }
   ]
  },
  {
   "title": "repmgr status",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 32 },
   "targets": [
    {
     "expr": "node_systemd_unit_state{name=\"repmgr.service\",state=\"active\",instance=\"sis2s059:9100\"}"
    }
   ]
  },
  {
   "title": "keepalived status systemctl",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 32 },
   "targets": [
    {
     "expr": "node_systemd_unit_state{name=\"keepalived.service\",state=\"active\",instance=\"sis2s059:9100\"}"
    }
   ]
  },
  {
   "title": "Alerting",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Daily Backups Status",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 37 },
   "targets": [
    {
     "expr": "pg_backup_status_daily_backup_status{backup_type=\"daily_backup\",instance=~\".+:9187\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Azure Daily Backups Status",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 37 },
   "targets": [
    {
     "expr": "pg_backup_status_daily_azure_backup_status{backup_type=\"daily_backup_azure\",instance=~\".+:9187\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "NFS Daily Backups Status",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 37 },
   "targets": [
    {
     "expr": "pg_backup_status_daily_nfs_backup_status{backup_type=\"daily_backup_nfs\",instance=~\".+:9187\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "PG Active Long Running Sessions",
   "type": "timeseries",
   "description": "queries running more than 15 minutes",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 37 },
   "targets": [
    {
     "expr": "dbmon_pg_active_sessions_count{instance=~\".+:9187\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "User Connection Count",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 43 },
   "targets": [
    {
     "expr": "dbmon_pg_user_connection_count{instance=~\".+:9187\"}",
     "legendFormat": "{{user_name}} - {{db_name}} - {{client_ip}} - {{state}}"
    }
   ]
  },
  {
   "title": "PG Up Alert",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 43 },
   "targets": [
    {
     "expr": "pg_up{instance=~\".+:9187\"}"
    }
   ]
  },
  {
   "title": "postgresql status systemctl",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 43 },
   "targets": [
    {
     "expr": "node_systemd_unit_state{name=~\"postgresql-.+.service\",state=\"active\",instance=~\".+:9100\"}"
    }
   ]
  },
  {
   "title": "RAM used",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (node_memory_MemAvailable_bytes{instance=~\".+:9100\",job=\"DB-Servers\"} *100)/node_memory_MemTotal_bytes{instance=~\".+:9100\",job=\"DB-Servers\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU Busy ",
   "type": "timeseries",
   "description": "Busy state of all CPU cores together",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (irate(node_cpu_seconds_total{mode=\"idle\",job=\"DB-Servers\"}[$__rate_interval])) * 100)  ",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Disk Use",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{instance=~\".+:9100\",job=\"DB-Servers\"} * 100) / node_filesystem_size_bytes{instance=~\".+:9100\",job=\"DB-Servers\"})",
     "legendFormat": "{{instance}}-{{mountpoint}}"
    }
   ]
  },
  {
   "title": "Disk IOps",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "irate(node_disk_reads_completed_total{instance=~\".+:9100\",device=~\"[a-z]*[a-z]\"}[$__rate_interval])",
     "legendFormat": "{{instance}}-{{device}} - Reads completed"
    },
    {
     "expr": "irate(node_disk_writes_completed_total{instance=~\".+:9100\",device=~\"[a-z]*[a-z]\"}[$__rate_interval])",
     "legendFormat": "{{instance}}-{{device}} - Writes completed"
    }
   ]
  }
 ]
}