{
 "title": "Docker Containers",
 "description": "Containers metrics",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "cluster",
    "query": {
     "query": "label_values(container_memory_usage_bytes{job=\"kubernetes-nodes-cadvisor\"}, cluster)"
    }
   },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(container_memory_usage_bytes{cluster=~\"$cluster\"}, instance)"
    }
   },
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(container_memory_usage_bytes{job=\"kubernetes-nodes-cadvisor\",cluster=~\"$cluster\"},namespace)"
    }
   },
   {
    "name": "container_service",
    "query": {
     "query": "label_values(container_memory_usage_bytes{instance=~\"$instance\", namespace=~\"$namespace\",container!~\"\"},container)"
    }
   },
   {
    "name": "java_process",
    "query": {
     "query": "label_values(namedprocess_namegroup_num_procs{kubernetes_node=~\"$instance\", namespace=~\"$namespace\"},service)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Load",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_user_seconds_total{cluster=~\"$cluster\", instance=~\"$instance\", image!=\"\"}[$__rate_interval])) / count(node_cpu_seconds_total{cluster=~\"$cluster\", kubernetes_node=~\"$instance\", mode=\"user\"}) * 100"
    }
   ]
  },
  {
   "title": "Memory Load",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(sum(node_memory_MemTotal_bytes{cluster=~\"$cluster\", kubernetes_node=~\"$instance\"}) - sum(node_memory_MemFree_bytes{cluster=~\"$cluster\", kubernetes_node=~\"$instance\"}+node_memory_Buffers_bytes{cluster=~\"$cluster\", kubernetes_node=~\"$instance\"}+node_memory_Cached_bytes{cluster=~\"$cluster\", kubernetes_node=~\"$instance\"}) ) / sum(node_memory_MemTotal_bytes{cluster=~\"$cluster\", kubernetes_node=~\"$instance\"}) * 100"
    }
   ]
  },
  {
   "title": "Memory Per $cluster/$instance",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{cluster=~\"$cluster\", instance=~\"$instance\", image!=\"\",container!~\"\"})",
     "legendFormat": "Used Memory"
    },
    {
     "expr": "sum(node_memory_MemTotal_bytes{cluster=~\"$cluster\", kubernetes_node=~\"$instance\"})",
     "legendFormat": "Total Memory"
    }
   ]
  },
  {
   "title": "Used Storage $cluster $instance",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(container_fs_usage_bytes{cluster=~\"$cluster\", instance=~\"$instance\"})",
     "legendFormat": "Used Disk"
    },
    {
     "expr": "sum(container_fs_limit_bytes{cluster=~\"$cluster\", instance=~\"$instance\"})",
     "legendFormat": "Total Disk"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "stat",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "machine_cpu_cores{instance=~\"$instance\",job=\"kubernetes-nodes-cadvisor\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Running Containers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "scalar(count(container_memory_usage_bytes{cluster=~\"$cluster\", instance=~\"$instance\", image!=\"\", namespace=~\"$namespace\"}) > 0)",
     "legendFormat": "containers"
    }
   ]
  },
  {
   "title": "System Load",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_load1{kubernetes_node=~\"$instance\"}",
     "legendFormat": "load 1m"
    }
   ]
  },
  {
   "title": "I/O Usage",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(irate(node_disk_read_bytes_total{cluster=~\"$cluster\", kubernetes_node=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "read"
    },
    {
     "expr": "sum(irate(node_disk_written_bytes_total{cluster=~\"$cluster\", kubernetes_node=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "written"
    },
    {
     "expr": "sum(irate(node_disk_io_time_seconds_total{cluster=~\"$cluster\", kubernetes_node=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "io time"
    }
   ]
  },
  {
   "title": "Memory Used",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (cluster,instance,namespace,container) (container_memory_usage_bytes{cluster=~\"$cluster\",instance=~\"$instance\", namespace=~\"$namespace\", container=~\"$container_service\", container!=\"\"})",
     "legendFormat": "{{cluster}} {{namespace}} {{container}} {{instance}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by (cluster,namespace,container,instance) (rate(container_cpu_usage_seconds_total{cluster=~\"$cluster\", instance=~\"$instance\", namespace=~\"$namespace\",container=~\"$container_service\", container!=\"\"}[$__rate_interval])) * 100",
     "legendFormat": "{{cluster}} {{namespace}} {{container}} {{instance}}"
    }
   ]
  },
  {
   "title": "Cluster Memory Usage Per Namespace/Instance",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (cluster)(node_memory_MemTotal_bytes{cluster=~\"$cluster\", kubernetes_node=~\"$instance\"})",
     "legendFormat": "Total {{cluster}}"
    },
    {
     "expr": "sum by (cluster)(container_memory_usage_bytes{cluster=~\"$cluster\", instance=~\"$instance\", namespace=~\"$namespace\", container!=\"\"})",
     "legendFormat": "Total Used {{cluster}}"
    },
    {
     "expr": "sum by (cluster,namespace)(container_memory_usage_bytes{cluster=~\"$cluster\", instance=~\"$instance\", namespace=~\"$namespace\", container!=\"\"})",
     "legendFormat": "Used {{cluster}} {{namespace}}"
    }
   ]
  },
  {
   "title": "Cluster CPU Usage Per Namespace",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "core" } },
   "targets": [
    {
     "expr": "sum by (cluster,namespace) (rate(container_cpu_usage_seconds_total{cluster=~\"$cluster\", instance=~\"$instance\", namespace=~\"$namespace\", container!=\"\"}[$__rate_interval])) ",
     "legendFormat": "Used {{cluster}} {{namespace}}"
    },
    {
     "expr": "sum by (cluster) (rate(container_cpu_usage_seconds_total{cluster=~\"$cluster\", instance=~\"$instance\", namespace=~\"$namespace\", container!=\"\"}[$__rate_interval])) ",
     "legendFormat": "Total Used {{cluster}} "
    },
    {
     "expr": "sum by (cluster)(machine_cpu_cores{cluster=~\"$cluster\", instance=~\"$instance\"}) ",
     "legendFormat": "Total {{cluster}} "
    }
   ]
  },
  {
   "title": "Container I/O Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(namedprocess_namegroup_read_bytes_total{cluster=~\"$cluster\", namespace=~\"$namespace\", service=~\"$java_process\"}[$__rate_interval])",
     "legendFormat": "Read {{namespace}} {{service}} "
    },
    {
     "expr": "rate(namedprocess_namegroup_write_bytes_total{cluster=~\"$cluster\", namespace=~\"$namespace\", service=~\"$java_process\"}[$__rate_interval])",
     "legendFormat": "Write {{namespace}} {{service}}"
    },
    {
     "expr": "rate(rabbitmq_io_write_bytes_total{cluster=~\"$cluster\", kubernetes_namespace=~\"$namespace\",kubernetes_node=~\"$instance\"}[$__rate_interval]) ",
     "legendFormat": "Write {{kubernetes_namespace}} rabbitmq"
    },
    {
     "expr": "rate(rabbitmq_io_read_bytes_total{cluster=~\"$cluster\", kubernetes_namespace=~\"$namespace\",kubernetes_node=~\"$instance\"}[$__rate_interval]) ",
     "legendFormat": "Read {{kubernetes_namespace}} rabbitmq"
    }
   ]
  },
  {
   "title": "Container Cached Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (cluster,namespace,pod)(container_memory_cache{cluster=~\"$cluster\", instance=~\"$instance\", job=\"kubernetes-nodes-cadvisor\", namespace=~\"$namespace\", container!=\"\", container=~\"$container_service\"})",
     "legendFormat": "{{cluster}} {{namespace}} {{pod}}"
    }
   ]
  },
  {
   "title": "Container Network Input",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (cluster,namespace,pod) (rate(container_network_receive_bytes_total{cluster=~\"$cluster\", instance=~\"$instance\", namespace=~\"$namespace\", pod=~\"$container_service.*\"}[$__rate_interval]))",
     "legendFormat": "{{cluster}} {{ namespace }} {{pod}}"
    }
   ]
  },
  {
   "title": "Container Network Output",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (cluster,namespace,pod) (rate(container_network_transmit_bytes_total{cluster=~\"$cluster\", instance=~\"$instance\", namespace=~\"$namespace\", pod=~\"$container_service.*\"}[$__rate_interval]))",
     "legendFormat": "{{cluster}} {{ namespace }} {{pod}}"
    }
   ]
  }
 ]
}