{
 "title": "FE2 Service Metrics",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(jvm_info, kubernetes_namespace)"
    }
   },
   {
    "name": "service_name",
    "label": "service_name",
    "query": {
     "query": "label_values(jvm_info{kubernetes_namespace=\"$namespace\", kubernetes_name=~\"fe2service-v.+\"}, kubernetes_name)"
    }
   },
   {
    "name": "pod_ip",
    "label": "pod_ip",
    "query": {
     "query": "label_values(jvm_info{kubernetes_namespace=\"$namespace\",kubernetes_name=\"$service_name\"},instance)"
    }
   },
   {
    "name": "pod_name",
    "label": "pod_name",
    "query": {
     "query": "label_values(container_memory_usage_bytes{namespace=\"$namespace\", pod=~\"$service_name.*\"},pod)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Heap Memory",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{instance=\"$pod_ip\",kubernetes_name=\"$service_name\",kubernetes_namespace=\"$namespace\", id=\"Eden Space\"}",
     "legendFormat": "{{id}}"
    },
    {
     "expr": "jvm_memory_used_bytes{instance=\"$pod_ip\",kubernetes_name=\"$service_name\",kubernetes_namespace=\"$namespace\", id=\"Survivor Space\"}",
     "legendFormat": "{{id}}"
    },
    {
     "expr": "jvm_memory_used_bytes{instance=\"$pod_ip\",kubernetes_name=\"$service_name\",kubernetes_namespace=\"$namespace\", id=\"Tenured Gen\"}",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "Non Heap Memory",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{instance=\"$pod_ip\",kubernetes_name=\"$service_name\",kubernetes_namespace=\"$namespace\", area=\"nonheap\"}",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "Queue Time",
   "type": "timeseries",
   "description": "Time spent in queue before being processed",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "vertx_http_client_queue_time_seconds_max{instance=\"$pod_ip\",kubernetes_name=\"$service_name\",kubernetes_namespace=\"$namespace\"}",
     "legendFormat": "Time"
    }
   ]
  },
  {
   "title": "HTTP Server Active Requests",
   "type": "timeseries",
   "description": "Number of requests being processed",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "vertx_http_server_active_requests{instance=\"$pod_ip\",kubernetes_name=\"$service_name\",kubernetes_namespace=\"$namespace\"}",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "HTTP Server Active Connections",
   "type": "timeseries",
   "description": "Number of opened connections to the server",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "vertx_http_server_active_connections{instance=\"$pod_ip\",kubernetes_name=\"$service_name\",kubernetes_namespace=\"$namespace\"}",
     "legendFormat": "ActiveConnections"
    }
   ]
  },
  {
   "title": "EventBus Metrics",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "vertx_eventbus_handlers{instance=\"$pod_ip\",kubernetes_name=\"$service_name\",kubernetes_namespace=\"$namespace\"}",
     "legendFormat": "Handlers"
    },
    {
     "expr": "vertx_eventbus_pending{instance=\"$pod_ip\",kubernetes_name=\"$service_name\",kubernetes_namespace=\"$namespace\"}",
     "legendFormat": "Pending"
    }
   ]
  },
  {
   "title": "Net Client Active Connections",
   "type": "timeseries",
   "description": "Number of connections to the remote host currently opened",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "vertx_net_client_active_connections{instance=\"$pod_ip\",kubernetes_name=\"$service_name\",kubernetes_namespace=\"$namespace\"}",
     "legendFormat": "Connections"
    }
   ]
  },
  {
   "title": "Pod Memory and Swap",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{namespace=\"$namespace\" , pod=\"$pod_name\", container=\"$service_name\"}",
     "legendFormat": "memory"
    },
    {
     "expr": "container_memory_swap{namespace=\"$namespace\" , pod=\"$pod_name\", container=\"$service_name\"}",
     "legendFormat": "swap"
    }
   ]
  },
  {
   "title": "EventBus Sent Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(vertx_eventbus_sent_total{instance=\"$pod_ip\",kubernetes_name=\"$service_name\",kubernetes_namespace=\"$namespace\"}[2m]))",
     "legendFormat": "Sent"
    }
   ]
  },
  {
   "title": "EventBus Receive Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(vertx_eventbus_received_total{instance=\"$pod_ip\",kubernetes_name=\"$service_name\",kubernetes_namespace=\"$namespace\"}[2m]))",
     "legendFormat": "Receive"
    }
   ]
  },
  {
   "title": "Time spent in GC pause",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 42 },
   "targets": [
    {
     "expr": "idelta(jvm_gc_pause_seconds_sum{instance=\"$pod_ip\",kubernetes_name=\"$service_name\",kubernetes_namespace=\"$namespace\"}[2m])",
     "legendFormat": "{{action}}"
    }
   ]
  },
  {
   "title": "Requests Per Second",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 49 },
   "targets": [
    {
     "expr": "sum(idelta(vertx_http_server_requests_total{instance=\"$pod_ip\",kubernetes_name=\"$service_name\",kubernetes_namespace=\"$namespace\"}[2m]))",
     "legendFormat": "total"
    },
    {
     "expr": "idelta(vertx_http_server_requests_total{instance=\"$pod_ip\",kubernetes_name=\"$service_name\",kubernetes_namespace=\"$namespace\"}[2m])",
     "legendFormat": "code: {{code}} route: {{route}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum (idelta (container_cpu_usage_seconds_total{pod=\"$pod_name\", image!=\"\",namespace=\"$namespace\",container=\"$service_name\"}[2m])/30) by (pod)",
     "legendFormat": "cpu usage"
    }
   ]
  },
  {
   "title": "JVM Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(jvm_memory_max_bytes{area=\"heap\", instance=\"$pod_ip\",kubernetes_name=\"$service_name\",kubernetes_namespace=\"$namespace\"})",
     "legendFormat": "heap limit"
    },
    {
     "expr": "sum(jvm_memory_used_bytes{area=\"heap\", instance=\"$pod_ip\",kubernetes_name=\"$service_name\",kubernetes_namespace=\"$namespace\"})",
     "legendFormat": "used heap"
    }
   ]
  },
  {
   "title": "JVM Threads State",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 71 },
   "targets": [
    {
     "expr": "jvm_threads_states_threads{instance=\"$pod_ip\", kubernetes_name=\"$service_name\", kubernetes_namespace=\"$namespace\"}",
     "legendFormat": "{{state}}"
    }
   ]
  }
 ]
}