{
 "title": "Hikari Pool Connections",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(jvm_info, kubernetes_namespace)"
    }
   },
   {
    "name": "service",
    "query": {
     "query": "label_values(hikaricp_active_connections{kubernetes_namespace=\"$namespace\"},kubernetes_name)"
    }
   },
   {
    "name": "application",
    "query": {
     "query": "label_values(hikaricp_active_connections{kubernetes_namespace=\"$namespace\"},pool)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Hikari Pool Connections",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "hikaricp_active_connections{kubernetes_namespace=\"$namespace\", kubernetes_name=\"$service\", pool=\"$application\"}",
     "legendFormat": "active"
    },
    {
     "expr": "hikaricp_idle_connections{kubernetes_namespace=\"$namespace\", kubernetes_name=\"$service\", pool=\"$application\"}",
     "legendFormat": "idle"
    },
    {
     "expr": "hikaricp_pending_threads{kubernetes_namespace=\"$namespace\", kubernetes_name=\"$service\", pool=\"$application\"}",
     "legendFormat": "pending"
    },
    {
     "expr": "idelta(hikaricp_connection_timeout_total{kubernetes_namespace=\"$namespace\", kubernetes_name=\"$service\", pool=\"$application\"}[$__rate_interval])",
     "legendFormat": "timeout"
    },
    {
     "expr": "hikaricp_max_connections{kubernetes_namespace=\"$namespace\", kubernetes_name=\"$service\", pool=\"$application\"}",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "Hikari Pool Connections (All services of Current Project)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(hikaricp_active_connections{kubernetes_namespace=\"$namespace\", pool=\"$application\"})",
     "legendFormat": "active"
    },
    {
     "expr": "sum(hikaricp_idle_connections{kubernetes_namespace=\"$namespace\", pool=\"$application\"})",
     "legendFormat": "idle"
    },
    {
     "expr": "sum(hikaricp_pending_threads{kubernetes_namespace=\"$namespace\",  pool=\"$application\"})",
     "legendFormat": "pending"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 20 },
   "options": {
    "content": "<div style=\"text-align: center;\"><i><strong style=\"color: #CCCCCC; font-size: 40px;\">Connections Creation</strong></i></div>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "50 Percentile Connection Creation",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "avg(hikaricp_connection_creation_millis{kubernetes_name=\"$service\",kubernetes_namespace=\"$namespace\",pool=\"$application\", quantile=\"0.5\"})",
     "metrics": [
      {
       "field": "request_time",
       "id": "1",
       "meta": {},
       "settings": { "percents": [ "75" ] },
       "type": "percentiles"
      }
     ],
     "query": "type:\"nginx-access\" AND request_host:\"k8s-dev.synisys.com\" AND request_uri:\"reportingservice/v1\" AND NOT method:\"OPTIONS\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "95 Percentile Connection Creation",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "avg(hikaricp_connection_creation_millis{kubernetes_name=\"$service\",kubernetes_namespace=\"$namespace\",pool=\"$application\", quantile=\"0.95\"})",
     "metrics": [
      {
       "field": "request_time",
       "id": "1",
       "meta": {},
       "settings": { "percents": [ "75" ] },
       "type": "percentiles"
      }
     ],
     "query": "type:\"nginx-access\" AND request_host:\"k8s-dev.synisys.com\" AND request_uri:\"reportingservice/v1\" AND NOT method:\"OPTIONS\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "99 Percentile Connection Creation",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "avg(hikaricp_connection_creation_millis{kubernetes_name=\"$service\",kubernetes_namespace=\"$namespace\",pool=\"$application\", quantile=\"0.99\"})",
     "metrics": [
      {
       "field": "request_time",
       "id": "1",
       "meta": {},
       "settings": { "percents": [ "75" ] },
       "type": "percentiles"
      }
     ],
     "query": "type:\"nginx-access\" AND request_host:\"k8s-dev.synisys.com\" AND request_uri:\"reportingservice/v1\" AND NOT method:\"OPTIONS\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Hikari Pool Connections Creation",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "idelta(hikaricp_connection_creation_millis_sum{kubernetes_namespace=\"$namespace\", kubernetes_name=\"$service\", pool=\"$application\"}[$__rate_interval])",
     "legendFormat": "creation",
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 35 },
   "options": {
    "content": "<div style=\"text-align: center;\"><i><strong style=\"color: #CCCCCC; font-size: 40px;\">Connections Acquired</strong></i></div>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "50 Percentile Connection Acquired",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "avg(hikaricp_connection_acquired_nanos{kubernetes_name=\"$service\",kubernetes_namespace=\"$namespace\",pool=\"$application\", quantile=\"0.5\"})",
     "metrics": [
      {
       "field": "request_time",
       "id": "1",
       "meta": {},
       "settings": { "percents": [ "75" ] },
       "type": "percentiles"
      }
     ],
     "query": "type:\"nginx-access\" AND request_host:\"k8s-dev.synisys.com\" AND request_uri:\"reportingservice/v1\" AND NOT method:\"OPTIONS\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "95 Percentile Connection Acquired",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "avg(hikaricp_connection_acquired_nanos{kubernetes_name=\"$service\",kubernetes_namespace=\"$namespace\",pool=\"$application\", quantile=\"0.95\"})",
     "metrics": [
      {
       "field": "request_time",
       "id": "1",
       "meta": {},
       "settings": { "percents": [ "75" ] },
       "type": "percentiles"
      }
     ],
     "query": "type:\"nginx-access\" AND request_host:\"k8s-dev.synisys.com\" AND request_uri:\"reportingservice/v1\" AND NOT method:\"OPTIONS\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "99 Percentile Connection Acquired",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "avg(hikaricp_connection_acquired_nanos{kubernetes_name=\"$service\",kubernetes_namespace=\"$namespace\",pool=\"$application\", quantile=\"0.99\"})",
     "metrics": [
      {
       "field": "request_time",
       "id": "1",
       "meta": {},
       "settings": { "percents": [ "75" ] },
       "type": "percentiles"
      }
     ],
     "query": "type:\"nginx-access\" AND request_host:\"k8s-dev.synisys.com\" AND request_uri:\"reportingservice/v1\" AND NOT method:\"OPTIONS\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Hikari Pool Connections Acquired",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "rate(hikaricp_connection_acquired_nanos_sum{kubernetes_namespace=\"$namespace\", kubernetes_name=\"$service\", pool=\"$application\"}[$__rate_interval])",
     "legendFormat": "acquired"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 50 },
   "options": {
    "content": "<div style=\"text-align: center;\"><i><strong style=\"color: #CCCCCC; font-size: 40px;\">Connections Usage</strong></i></div>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "50 Percentile Connection Usage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "avg(hikaricp_connection_usage_millis{kubernetes_name=\"$service\",kubernetes_namespace=\"$namespace\",pool=\"$application\", quantile=\"0.5\"})",
     "metrics": [
      {
       "field": "request_time",
       "id": "1",
       "meta": {},
       "settings": { "percents": [ "75" ] },
       "type": "percentiles"
      }
     ],
     "query": "type:\"nginx-access\" AND request_host:\"k8s-dev.synisys.com\" AND request_uri:\"reportingservice/v1\" AND NOT method:\"OPTIONS\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "95 Percentile Connection Usage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "avg(hikaricp_connection_usage_millis{kubernetes_name=\"$service\",kubernetes_namespace=\"$namespace\",pool=\"$application\", quantile=\"0.95\"})",
     "metrics": [
      {
       "field": "request_time",
       "id": "1",
       "meta": {},
       "settings": { "percents": [ "75" ] },
       "type": "percentiles"
      }
     ],
     "query": "type:\"nginx-access\" AND request_host:\"k8s-dev.synisys.com\" AND request_uri:\"reportingservice/v1\" AND NOT method:\"OPTIONS\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "99 Percentile Connection Usage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "avg(hikaricp_connection_usage_millis{kubernetes_name=\"$service\",kubernetes_namespace=\"$namespace\",pool=\"$application\", quantile=\"0.99\"})",
     "metrics": [
      {
       "field": "request_time",
       "id": "1",
       "meta": {},
       "settings": { "percents": [ "75" ] },
       "type": "percentiles"
      }
     ],
     "query": "type:\"nginx-access\" AND request_host:\"k8s-dev.synisys.com\" AND request_uri:\"reportingservice/v1\" AND NOT method:\"OPTIONS\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Hikari Pool Connections Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 57 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "idelta(hikaricp_connection_usage_millis_sum{kubernetes_namespace=\"$namespace\", kubernetes_name=\"$service\", pool=\"$application\"}[$__rate_interval])",
     "legendFormat": "usage"
    }
   ]
  }
 ]
}