{
 "title": "Infrastructure Availability",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(up,kubernetes_namespace)"
    }
   },
   { "name": "availability_span", "label": "availability_span", "query": "1h,2h,6h,12h,1d,2d,7d" }
  ]
 },
 "panels": [
  {
   "title": "SLOs over $availability_span",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "K8s-nodes Availability",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time((count(up{instance=~\".+k8s.+|k8s.+|aks-.+\"} == 1 ) / count(up{instance=~\".+k8s.+|k8s.+|aks-.+\"})) [$availability_span:] )"
    }
   ]
  },
  {
   "title": "Prometheus Availability",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time((sum(up{job=\"prometheus\"} ) / count(up{job=\"prometheus\"})) [$availability_span:] )"
    }
   ]
  },
  {
   "title": "Elasticsearch Availability",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(up{job=\"elasticsearch_exporter\",namespace=~\"$namespace\"} [$availability_span:] )"
    }
   ]
  },
  {
   "title": "Redis Availability",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time((sum(redis_up{kubernetes_namespace=~\"$namespace\"} ) / count(redis_up{kubernetes_namespace=~\"$namespace\"})) [$availability_span:] )"
    }
   ]
  },
  {
   "title": "Consul Availability",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time((sum(up{job=\"consul-exporter\"} ) / count(up{job=\"consul-exporter\"})) [$availability_span:] )"
    }
   ]
  },
  {
   "title": "Rabbitmq Availability",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time((sum(rabbitmq_up{kubernetes_namespace=~\"$namespace\"} ) / count(rabbitmq_up{kubernetes_namespace=~\"$namespace\"})) [$availability_span:] )"
    }
   ]
  },
  {
   "title": "Vault Availability",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg_over_time((sum(up{instance=~\"vault.+:9100\"} ) by (instance) / count(up{instance=~\"vault.+:9100\"})by (instance)) [$availability_span:] ) ",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Nginx Availability",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time((sum(up{job=\"nginx-prometheus-exporter\"} ) / count(up{job=\"nginx-prometheus-exporter\"})) [$availability_span:] )"
    }
   ]
  },
  {
   "title": "infrastructure",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "repeat": "namespace",
   "targets": [
    {}
   ]
  },
  {
   "title": "Kube-Nodes-Availability SLO over $availability_span",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg_over_time((count(up{instance=~\".+k8s.+|k8s.+|aks-.+\"} == 1 ) / count(up{instance=~\".+k8s.+|k8s.+|aks-.+\"})) [$availability_span:] )",
     "legendFormat": "k8s up over $availability_span"
    }
   ]
  },
  {
   "title": "Rabbitmq-Availability SLO over $availability_span",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg_over_time((sum by (kubernetes_namespace)(rabbitmq_up{kubernetes_namespace=~\"$namespace\"} ) / count by (kubernetes_namespace)(rabbitmq_up{kubernetes_namespace=~\"$namespace\"})) [$availability_span:] )",
     "legendFormat": "{{kubernetes_namespace}} rabbit up over $availability_span"
    }
   ]
  },
  {
   "title": "Kube-Nodes-Availability",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "min(up{instance=~\".+k8s.+|k8s.+|aks-.+\"} )",
     "legendFormat": "min(k8s up)"
    }
   ]
  },
  {
   "title": "Rabbitmq-Availability",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rabbitmq_up{kubernetes_namespace=~\"$namespace\"}",
     "legendFormat": "{{kubernetes_namespace}}"
    }
   ]
  },
  {
   "title": "Consul Availability SLO over $availability_span",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg_over_time((sum(up{job=\"consul-exporter\"} ) / count(up{job=\"consul-exporter\"})) [$availability_span:] )",
     "legendFormat": "consul up over $availability_span"
    }
   ]
  },
  {
   "title": "Redis-Availability SO over $availability_span",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg_over_time((sum(redis_up{kubernetes_namespace=~\"$namespace\"} ) / count(redis_up{kubernetes_namespace=~\"$namespace\"})) [$availability_span:] )",
     "legendFormat": "redis up over $availability_span"
    }
   ]
  },
  {
   "title": "Consul Availability",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    { "expr": "consul_up", "legendFormat": "consul up" }
   ]
  },
  {
   "title": "Redis-Availability",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "redis_up{kubernetes_namespace=~\"$namespace\"}",
     "legendFormat": "min(redis up)"
    }
   ]
  },
  {
   "title": "Elasticsearch Availability SLO over $availability_span",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg_over_time((sum(up{job=~\"elasticsearch_exporter\",namespace=~\"$namespace\"} ) / count(up{job=~\"elasticsearch_exporter\",namespace=~\"$namespace\"})) [$availability_span:] )",
     "legendFormat": "elastic up over $availability_span"
    }
   ]
  },
  {
   "title": "Nginx Availability SLO over $availability_span",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg_over_time((sum(up{job=\"nginx-prometheus-exporter\"} ) / count(up{job=\"nginx-prometheus-exporter\"})) [$availability_span:] )",
     "legendFormat": "nginx up over $availability_span"
    }
   ]
  },
  {
   "title": "Elasticsearch Availability",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "min(up{job=\"elasticsearch_exporter\",namespace=~\"$namespace\"})",
     "legendFormat": "min(elastic up)"
    }
   ]
  },
  {
   "title": "Nginx Availability",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "min(up{job=\"nginx-prometheus-exporter\"})",
     "legendFormat": "min(nginx up)"
    }
   ]
  },
  {
   "title": "Prometheus Availability over $availability_span",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg_over_time((sum(up{job=\"prometheus\"} ) / count(up{job=\"prometheus\"})) [$availability_span:] )",
     "legendFormat": "prometheus up over $availability_span"
    }
   ]
  },
  {
   "title": "Vault Availability over $availability_span",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg_over_time((sum(up{instance=~\"vault-.+:9100\"} ) by (instance) / count(up{instance=~\"vault-.+:9100\"})by (instance)) [$availability_span:] )",
     "legendFormat": "{{instance}} up over $availability_span"
    }
   ]
  },
  {
   "title": "Prometheus Availability",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "min(up{job=\"prometheus\"})",
     "legendFormat": "min(prometheus up)"
    }
   ]
  },
  {
   "title": "Vault Availability",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "min(up{instance=~\"vault-.+:9100\"}) by (instance)",
     "legendFormat": "min({{instance}} up)"
    }
   ]
  }
 ]
}