{
 "title": "RabbitMq Consumers",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "environment",
    "label": "environment",
    "query": {
     "query": "label_values(jvm_info, kubernetes_namespace)"
    }
   },
   {
    "name": "queue",
    "label": "queue",
    "query": {
     "query": "label_values(rabbitmq_queue_consumers{kubernetes_namespace=~\"$environment\",queue!~\".*retry\", queue!~\"reporting-service-sync-.*\", queue!~\".*-exchange-tracker\", queue!~\"^SIS.+\", queue!~\"^sis.+\", queue!~\"^DESKTOP.+\", queue!~\"messaging-upgraded-services\", queue!~\"reporting-service-sync.source-exchange-created\", queue!~\"health-status-result-test\"},queue)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "# of queues without consumer",
   "type": "stat",
   "gridPos": { "h": 5, "w": 11, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(rabbitmq_queue_consumers{kubernetes_namespace=~\"$environment\", job=\"kubernetes-service-endpoints\",\n  queue!~\".*retry\",\n  queue!~\".*-exchange-tracker\",\n  queue!~\"^SIS.+\",\n  queue!~\"^sis.+\",\n  queue!~\"^Sis.+\",\n  queue!~\"^DESKTOP.+\",\n  queue!~\"messaging-upgraded-services\",\n  queue!~\"health-status-result-test\",\n  queue!~\"^reporting-service-sync.+\",\n  queue!~\".+-v1.+\",\n  queue!~\"^macadmins.+\",\n  queue!~\"^localhost.+\",\n  queue!~\"^[0-9].+\",\n  queue!~\"health-status-result\",\n  queue!~\"^kube-master-dev.+\"\n  }==0)",
     "legendFormat": "{{queue}}"
    }
   ]
  },
  {
   "title": "%  queues without consumer",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 13, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(rabbitmq_queue_consumers{kubernetes_namespace=~\"$environment\",  queue!~\".*retry\",\n  queue!~\".*-exchange-tracker\",\n  queue!~\"^SIS.+\",\n  queue!~\"^sis.+\",\n  queue!~\"^Sis.+\",\n  queue!~\"^DESKTOP.+\",\n  queue!~\"messaging-upgraded-services\",\n  queue!~\"health-status-result-test\",\n  queue!~\"^reporting-service-sync.+\",\n  queue!~\".+-v1.+\",\n  queue!~\"^macadmins.+\",\n  queue!~\"^localhost.+\",\n  queue!~\"^[0-9].+\",\n  queue!~\"health-status-result\",\n  queue!~\"^kube-master-dev.+\"}==0)/count(rabbitmq_queue_consumers{kubernetes_namespace=~\"$environment\",   queue!~\".*retry\",\n  queue!~\".*-exchange-tracker\",\n  queue!~\"^SIS.+\",\n  queue!~\"^sis.+\",\n  queue!~\"^Sis.+\",\n  queue!~\"^DESKTOP.+\",\n  queue!~\"messaging-upgraded-services\",\n  queue!~\"health-status-result-test\",\n  queue!~\"^reporting-service-sync.+\",\n  queue!~\".+-v1.+\",\n  queue!~\"^macadmins.+\",\n  queue!~\"^localhost.+\",\n  queue!~\"^[0-9].+\",\n  queue!~\"health-status-result\",\n  queue!~\"^kube-master-dev.+\"})",
     "legendFormat": "{{queue}}"
    }
   ]
  },
  {
   "title": "Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {}
   ]
  },
  {
   "title": "queues without consumer",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rabbitmq_queue_consumers{kubernetes_namespace=~\"$environment\", job=\"kubernetes-service-endpoints\",\n  queue!~\".*retry\",\n  queue!~\".*-exchange-tracker\",\n  queue!~\"^SIS.+\",\n  queue!~\"^sis.+\",\n  queue!~\"^Sis.+\",\n  queue!~\"^DESKTOP.+\",\n  queue!~\"messaging-upgraded-services\",\n  queue!~\"health-status-result-test\",\n  queue!~\"^reporting-service-sync.+\",\n  queue!~\".+-v1.+\",\n  queue!~\"^macadmins.+\",\n  queue!~\"^localhost.+\",\n  queue!~\"^[0-9].+\",\n  queue!~\"health-status-result\",\n  queue!~\"^kube-master-dev.+\"\n  }==0",
     "legendFormat": "{{queue}}"
    }
   ]
  },
  {
   "title": "Consumers per time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rabbitmq_queue_consumers{kubernetes_namespace=~\"$environment\",queue=\"$queue\"}",
     "legendFormat": "{{queue}}"
    }
   ]
  },
  {
   "title": "Consumers count  by Queue",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "sum(rabbitmq_queue_consumers{kubernetes_namespace=~\"$environment\"}) by (queue)",
     "legendFormat": "{{queue}}"
    }
   ]
  },
  {
   "title": "Queue limit alert",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rabbitmq_queue_messages_ready{job=\"kubernetes-service-endpoints\",\n  queue!~\"messaging-upgraded-services\",\n  queue!~\"^reporting-service-sync.+\",\n  queue!~\"health-status-result-test\"\n  } > 500",
     "legendFormat": "{{queue}} <{{kubernetes_namespace}}>"
    }
   ]
  },
  {
   "title": "High size of unconsumed messages alert",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 9, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rabbitmq_queue_messages_ready{kubernetes_namespace=\"$environment\",app=\"rabbitmq\"} ",
     "legendFormat": "{{kubernetes_namespace}}"
    }
   ]
  },
  {
   "title": "Consumer missing alert",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rabbitmq_queue_consumers{job=\"kubernetes-service-endpoints\",\n  queue!~\".*retry\",\n  queue!~\"reporting-service-sync-.*\",\n  queue!~\".*-exchange-tracker\",\n  queue!~\"^SIS.+\",\n  queue!~\"^sis.+\",\n  queue!~\"^Sis.+\",\n  queue!~\"^DESKTOP.+\",\n  queue!~\"messaging-upgraded-services\",\n  queue!~\"reporting-service-sync.source-exchange-created\",\n  queue!~\"health-status-result-test\",\n  queue!~\"^reporting-service-sync.+\",\n  queue!~\".+-v1.+\",\n  queue!~\".+-v2.+\",\n  queue!~\"^macadmins.+\",\n  queue!~\"^localhost.+\",\n  queue!~\"^[0-9].+\",\n  queue!~\"health-status-result\",\n  queue!~\"^kube-master-dev.+\",\n  queue!~\".*docker.*\"\n  } < 1",
     "legendFormat": "{{queue}}  <{{kubernetes_namespace}}>"
    }
   ]
  }
 ]
}