{
 "title": "Reporting Metrics G1 GC",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(jvm_info, kubernetes_namespace)"
    }
   },
   {
    "name": "application",
    "label": "application",
    "query": {
     "query": "label_values(hikaricp_active_connections{kubernetes_namespace=~\"$namespace\",kubernetes_name=~\"reportingservice-v1\"},pool)"
    }
   },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(jvm_memory_pool_bytes_used{kubernetes_namespace=~\"$namespace\", kubernetes_name=~\"reportingservice-v1\"},instance)"
    }
   },
   {
    "name": "instance_name",
    "query": {
     "query": "label_values(container_memory_usage_bytes{namespace=~\"$namespace\", pod=~\"reportingservice-v1.*\"},pod)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Data Sync Status",
   "type": "stat",
   "description": "Indicates if there is an error in data sync process",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sync_error{instance=~\"$instance\",kubernetes_namespace=~\"$namespace\", appId=~\"$application\"}",
     "legendFormat": "error"
    }
   ]
  },
  {
   "title": "Non-Heap Memory",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "jvm_memory_pool_bytes_used{instance=~\"$instance\",kubernetes_name=~\"reportingservice-v1\",kubernetes_namespace=~\"$namespace\",pool=~\"Code Cache\"}",
     "legendFormat": "code cache",
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    },
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "jvm_memory_pool_bytes_used{instance=~\"$instance\",kubernetes_name=~\"reportingservice-v1\",kubernetes_namespace=~\"$namespace\",pool=~\"Compressed Class Space\"}",
     "legendFormat": "class space",
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    },
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "jvm_memory_pool_bytes_used{instance=~\"$instance\",kubernetes_name=~\"reportingservice-v1\",kubernetes_namespace=~\"$namespace\",pool=~\"Metaspace\"}",
     "legendFormat": "metaspace",
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Heap Memory By Generations",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_used{instance=~\"$instance\", kubernetes_name=~\"reportingservice-v1\",kubernetes_namespace=~\"$namespace\",pool=~\"G1 Old Gen\"}",
     "legendFormat": "PS Old Gen"
    },
    {
     "expr": "jvm_memory_pool_bytes_used{instance=~\"$instance\", kubernetes_name=~\"reportingservice-v1\",kubernetes_namespace=~\"$namespace\",pool=~\"G1 Survivor Space\"}",
     "legendFormat": "PS Survivor Space"
    },
    {
     "expr": "jvm_memory_pool_bytes_used{instance=~\"$instance\", kubernetes_name=~\"reportingservice-v1\",kubernetes_namespace=~\"$namespace\",pool=~\"G1 Eden Space\"}",
     "legendFormat": "{{pool}}"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum (idelta (container_cpu_usage_seconds_total{pod=~\"$instance_name\", image!~\"\",namespace=~\"$namespace\",container=~\"reportingservice-v1\",kubernetes_io_hostname=~\".+\"}[2m])/30) by (pod)",
     "legendFormat": "cpu usage"
    }
   ]
  },
  {
   "title": "Redis client Non-Heap Memory usage (Netty)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "cache_netty_memory_bytes_max{area=\"nonheap\",kubernetes_namespace=~\"$namespace\"}",
     "legendFormat": "{{kubernetes_namespace}} {{kubernetes_name}} {{area}} max"
    },
    {
     "expr": "cache_netty_memory_bytes_used{area=\"nonheap\",kubernetes_namespace=~\"$namespace\"}",
     "legendFormat": "{{kubernetes_namespace}} {{kubernetes_name}} {{area}} used"
    }
   ]
  },
  {
   "title": "GC collection time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "increase(jvm_gc_collection_seconds_sum{instance=~\"$instance\",kubernetes_name=~\"reportingservice-v1\",kubernetes_namespace=~\"$namespace\"}[2m])",
     "legendFormat": "{{gc}}"
    }
   ]
  },
  {
   "title": "JVM memory",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "jvm_memory_bytes_max{area=~\"heap\", instance=~\"$instance\", kubernetes_name=~\"reportingservice-v1\", kubernetes_namespace=~\"$namespace\"}",
     "legendFormat": "heap limit"
    },
    {
     "expr": "jvm_memory_bytes_used{area=~\"heap\", instance=~\"$instance\", kubernetes_name=~\"reportingservice-v1\", kubernetes_namespace=~\"$namespace\"}",
     "legendFormat": "used heap"
    }
   ]
  },
  {
   "title": "Pod Memory &  Swap",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{namespace=~\"$namespace\", container=~\"reportingservice-v1\"}",
     "legendFormat": "memory"
    },
    {
     "expr": "container_memory_swap{namespace=~\"$namespace\", container=~\"reportingservice-v1\"}",
     "legendFormat": "swap"
    }
   ]
  },
  {
   "title": "Service Up",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "up{kubernetes_name=~\"reportingservice-v1\",kubernetes_namespace=~\"$namespace\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "# of threads",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "jvm_threads_current{instance=~\"$instance\", kubernetes_name=~\"reportingservice-v1\", kubernetes_namespace=~\"$namespace\"}",
     "legendFormat": "threads count"
    }
   ]
  },
  {
   "title": "jvm threads state",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "jvm_threads_state{instance=~\"$instance\", kubernetes_name=~\"reportingservice-v1\", kubernetes_namespace=~\"$namespace\"}",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "jetty thread pool",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "jetty_thread_pool_size{instance=~\"$instance\", kubernetes_name=~\"reportingservice-v1\", kubernetes_namespace=~\"$namespace\"}",
     "legendFormat": "threads"
    },
    {
     "expr": "jetty_thread_pool_busy{instance=~\"$instance\", kubernetes_name=~\"reportingservice-v1\", kubernetes_namespace=~\"$namespace\"}",
     "legendFormat": "busy"
    },
    {
     "expr": "jetty_thread_pool_idle{instance=~\"$instance\", kubernetes_name=~\"reportingservice-v1\", kubernetes_namespace=~\"$namespace\"}",
     "legendFormat": "idle"
    },
    {
     "expr": "jetty_thread_pool_queued{instance=~\"$instance\", kubernetes_name=~\"reportingservice-v1\", kubernetes_namespace=~\"$namespace\"}",
     "legendFormat": "queued"
    }
   ]
  },
  {
   "title": "Executor Service",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "reporting_executor_active{kubernetes_namespace=~\"$namespace\"}",
     "legendFormat": "active"
    },
    {
     "expr": "reporting_executor_queued{kubernetes_namespace=~\"$namespace\"}",
     "legendFormat": "queued"
    },
    {
     "expr": "reporting_executor_pool_size{kubernetes_namespace=~\"$namespace\"}",
     "legendFormat": "size"
    },
    {
     "expr": "reporting_executor_pool_largest_size{kubernetes_namespace=~\"$namespace\"}",
     "legendFormat": "largest size"
    }
   ]
  },
  {
   "title": "Async Publisher Executor Service",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 93 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "reporting_async_publisher_executor_active{kubernetes_namespace=~\"$namespace\", instance=~\"$instance\", kubernetes_name=~\"reportingservice-v1\"}",
     "legendFormat": "active"
    },
    {
     "expr": "reporting_async_publisher_executor_queued{kubernetes_namespace=~\"$namespace\", instance=~\"$instance\", kubernetes_name=~\"reportingservice-v1\"}",
     "legendFormat": "queued"
    },
    {
     "expr": "reporting_async_publisher_executor_pool_size{kubernetes_namespace=~\"$namespace\", instance=~\"$instance\", kubernetes_name=~\"reportingservice-v1\"}",
     "legendFormat": "size"
    },
    {
     "expr": "reporting_async_publisher_executor_pool_largest_size{kubernetes_namespace=~\"$namespace\", instance=~\"$instance\", kubernetes_name=~\"reportingservice-v1\"}",
     "legendFormat": "largest_size"
    }
   ]
  },
  {
   "title": "Executor Service Completed Tasks",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 100 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "idelta(reporting_executor_completed{kubernetes_namespace=~\"$namespace\"}[90s])",
     "legendFormat": "completed"
    },
    {
     "expr": "idelta(reporting_executor_task_count{kubernetes_namespace=~\"$namespace\"}[90s])",
     "legendFormat": "scheduled"
    }
   ]
  },
  {
   "title": "Responce codes",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 106 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "idelta(service_response_status_total{kubernetes_name=~\"reportingservice-v1\", kubernetes_namespace=~\"$namespace\", app=~\"ALL\"}[$__rate_interval])",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "type": "text",
   "description": "Provides the info for services about hikari connection pool",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 111 },
   "options": {
    "content": "<div style=~\"text-align: center;\"><i><strong style=~\"color: #CCCCCC; font-size: 40px;\">Hikari Connections Pool</strong></i></div>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "hikari pool active connections",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 114 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "hikaricp_active_connections{kubernetes_namespace=~\"$namespace\", kubernetes_name=~\"reportingservice-v1\"}",
     "legendFormat": "{{pool}}"
    }
   ]
  },
  {
   "title": "hikari pool idle connections",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 119 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "hikaricp_idle_connections{kubernetes_namespace=~\"$namespace\", kubernetes_name=~\"reportingservice-v1\"}",
     "legendFormat": "{{pool}}"
    }
   ]
  },
  {
   "title": "hikari pool pending connections",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 124 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "hikaricp_pending_threads{kubernetes_namespace=~\"$namespace\", kubernetes_name=~\"reportingservice-v1\"}",
     "legendFormat": "{{pool}}"
    }
   ]
  },
  {
   "title": "hikari pool timeout connections",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 129 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "idelta(hikaricp_connection_timeout_total{kubernetes_namespace=~\"$namespace\", kubernetes_name=~\"reportingservice-v1\"}[90s])",
     "legendFormat": "{{pool}}"
    }
   ]
  },
  {
   "title": "Hikari Pool Connections",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 134 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(hikaricp_active_connections{kubernetes_namespace=~\"$namespace\", kubernetes_name=~\"reportingservice-v1\"})",
     "legendFormat": "active"
    },
    {
     "expr": "sum(hikaricp_idle_connections{kubernetes_namespace=~\"$namespace\", kubernetes_name=~\"reportingservice-v1\"})",
     "legendFormat": "idle"
    }
   ]
  },
  {
   "title": "50 Percentile Connection Usage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 143 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "hikaricp_connection_usage_millis{kubernetes_name=~\"reportingservice-v1\",kubernetes_namespace=~\"$namespace\",pool=~\"$application\", quantile=~\"0.5\"}",
     "metrics": [
      {
       "field": "request_time",
       "id": "1",
       "meta": {},
       "settings": { "percents": [ "75" ] },
       "type": "percentiles"
      }
     ],
     "query": "type:\"nginx-access\" AND request_host:\"k8s-dev.synisys.com\" AND request_uri:\"reportingservice/v1\" AND NOT method:\"OPTIONS\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "95 Percentile Connection Usage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 143 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "hikaricp_connection_usage_millis{kubernetes_name=~\"reportingservice-v1\",kubernetes_namespace=~\"$namespace\",pool=~\"$application\", quantile=~\"0.95\"}",
     "metrics": [
      {
       "field": "request_time",
       "id": "1",
       "meta": {},
       "settings": { "percents": [ "75" ] },
       "type": "percentiles"
      }
     ],
     "query": "type:\"nginx-access\" AND request_host:\"k8s-dev.synisys.com\" AND request_uri:\"reportingservice/v1\" AND NOT method:\"OPTIONS\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "99 Percentile Connection Usage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 143 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "hikaricp_connection_usage_millis{kubernetes_name=~\"reportingservice-v1\",kubernetes_namespace=~\"$namespace\",pool=~\"$application\", quantile=~\"0.99\"}",
     "metrics": [
      {
       "field": "request_time",
       "id": "1",
       "meta": {},
       "settings": { "percents": [ "75" ] },
       "type": "percentiles"
      }
     ],
     "query": "type:\"nginx-access\" AND request_host:\"k8s-dev.synisys.com\" AND request_uri:\"reportingservice/v1\" AND NOT method:\"OPTIONS\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Query Execution Time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 147 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {}
   ]
  },
  {
   "title": "Query Executions Count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 154 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "legendFormat": "__auto",
     "metrics": [
      {
       "field": "postgres_duration",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "type:\"postgres-log\" AND host:\"sis2s091\" AND postgres_environment:\"$namespace\" AND postgres_servicename:\"reporting-service\"  AND postgres_app:\"$application\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Redis Connections",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 161 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "redis_connected_clients{kubernetes_namespace=~\"$namespace\"}",
     "legendFormat": "connections"
    }
   ]
  },
  {
   "title": "Logs of Queries cache hits/misses",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 167 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "hit",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "type:\"log\" AND app.environment:\"$namespace\" AND app.service.name:\"reportingservice\" AND message:\"$application:reportQueriesCache cache hit.\"",
     "timeField": "@timestamp"
    },
    {
     "alias": "miss",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "type:\"log\" AND app.service.name:\"reportingservice\" AND message:\"$application:reportQueriesCache cache miss.\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 174 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "type:\"nginx-access\" AND request_host:\"k8s-dev.synisys.com\" AND request_uri:\"reportingservice/v1\" AND NOT method:\"OPTIONS\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Percentiles",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 181 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "request_time",
       "id": "1",
       "meta": {},
       "settings": {
        "percents": [
         25,
         50,
         75,
         95,
         99
        ]
       },
       "type": "percentiles"
      }
     ],
     "query": "type:\"nginx-access\" AND request_host:\"k8s-dev.synisys.com\" AND request_uri:\"reportingservice/v1\" AND NOT method:\"OPTIONS\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "type": "text",
   "description": "Provides the info for services fault tolerance and resilience whom this service calls",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 188 },
   "options": {
    "content": "<div style=~\"text-align: center;\"><i><strong style=~\"color: #7F7FFF; font-size: 40px;\">Resilience</strong></i></div>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "75 Percentile AVG(s)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 191 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "request_time",
       "id": "1",
       "meta": {},
       "settings": { "percents": [ "75" ] },
       "type": "percentiles"
      }
     ],
     "query": "type:\"nginx-access\" AND request_host:\"k8s-dev.synisys.com\" AND request_uri:\"reportingservice/v1\" AND NOT method:\"OPTIONS\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "95 Percentile AVG (s)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 191 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "request_time",
       "id": "1",
       "meta": {},
       "settings": { "percents": [ "95" ] },
       "type": "percentiles"
      }
     ],
     "query": "type:\"nginx-access\" AND request_host:\"k8s-dev.synisys.com\" AND request_uri:\"reportingservice/v1\" AND NOT method:\"OPTIONS\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "99 Percentile AVG (s)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 191 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "request_time",
       "id": "1",
       "meta": {},
       "settings": { "percents": [ "99" ] },
       "type": "percentiles"
      }
     ],
     "query": "type:\"nginx-access\" AND request_host:\"k8s-dev.synisys.com\" AND request_uri:\"reportingservice/v1\" AND NOT method:\"OPTIONS\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "2XX Count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 195 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "type:\"nginx-access\" AND request_host:\"k8s-dev.synisys.com\" AND nginx.service.name:\"reportingservice\" AND nginx.service.version:\"v1\" AND status_code:2*",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "3XX Count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 195 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "type:\"nginx-access\" AND request_host:\"k8s-dev.synisys.com\" AND nginx.service.name:\"reportingservice\" AND nginx.service.version:\"v1\" AND status_code:3*",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "4XX Count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 195 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "type:\"nginx-access\" AND request_host:\"k8s-dev.synisys.com\" AND nginx.service.name:\"reportingservice\" AND nginx.service.version:\"v1\" AND status_code:4*",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "5XX Count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 195 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "type:\"nginx-access\" AND request_host:\"k8s-dev.synisys.com\" AND nginx.service.name:\"reportingservice\" AND nginx.service.version:\"v1\" AND status_code:5*",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Queries Cache hit/miss",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 198 },
   "format": "percent",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cache_hit_percentage{kubernetes_namespace=~\"$namespace\", instance=~\"$instance\", cacheName=~\"$application:reportQueriesCache\"}",
     "legendFormat": "hit"
    },
    {
     "expr": "cache_miss_percentage{kubernetes_namespace=~\"$namespace\", instance=~\"$instance\", cacheName=~\"$application:reportQueriesCache\"}",
     "legendFormat": "miss"
    }
   ]
  },
  {
   "title": "Reports Cache hit/miss",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 198 },
   "format": "percent",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cache_hit_percentage{kubernetes_namespace=~\"$namespace\", instance=~\"$instance\", cacheName=~\"$application:reportResultCache\"}",
     "legendFormat": "hit"
    },
    {
     "expr": "cache_miss_percentage{kubernetes_namespace=~\"$namespace\", instance=~\"$instance\", cacheName=~\"$application:reportResultCache\"}",
     "legendFormat": "miss"
    }
   ]
  },
  {
   "title": "Queries Cache hits/misses",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 207 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "idelta(cache_hits{kubernetes_namespace=~\"$namespace\", instance=~\"$instance\", cacheName=~\"$application:reportQueriesCache\"}[90s])",
     "legendFormat": "hit "
    },
    {
     "expr": "idelta(cache_misses{kubernetes_namespace=~\"$namespace\", instance=~\"$instance\", cacheName=~\"$application:reportQueriesCache\"}[90s])",
     "legendFormat": "miss"
    }
   ]
  },
  {
   "title": "Reports Cache hits/misses",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 212 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "idelta(cache_hits{kubernetes_namespace=~\"$namespace\", instance=~\"$instance\", cacheName=~\"$application:reportResultCache\"}[90s])",
     "legendFormat": "hit"
    },
    {
     "expr": "idelta(cache_misses{kubernetes_namespace=~\"$namespace\", instance=~\"$instance\", cacheName=~\"$application:reportResultCache\"}[90s])",
     "legendFormat": "miss"
    }
   ]
  },
  {
   "title": "Queries Cache gets/puts/removals",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 217 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "idelta(cache_gets{kubernetes_namespace=~\"$namespace\", instance=~\"$instance\", cacheName=~\"$application:reportQueriesCache\"}[90s])",
     "legendFormat": "gets"
    },
    {
     "expr": "idelta(cache_puts{kubernetes_namespace=~\"$namespace\", instance=~\"$instance\", cacheName=~\"$application:reportQueriesCache\"}[90s])",
     "legendFormat": "puts"
    },
    {
     "expr": "idelta(cache_removals{kubernetes_namespace=~\"$namespace\", instance=~\"$instance\", cacheName=~\"$application:reportQueriesCache\"}[90s])",
     "legendFormat": "removals"
    }
   ]
  },
  {
   "title": "Reports Cache gets/puts/removals",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 217 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "idelta(cache_gets{kubernetes_namespace=~\"$namespace\", instance=~\"$instance\", cacheName=~\"$application:reportResultCache\"}[90s])",
     "legendFormat": "gets"
    },
    {
     "expr": "idelta(cache_puts{kubernetes_namespace=~\"$namespace\", instance=~\"$instance\", cacheName=~\"$application:reportResultCache\"}[90s])",
     "legendFormat": "puts"
    },
    {
     "expr": "idelta(cache_removals{kubernetes_namespace=~\"$namespace\", instance=~\"$instance\", cacheName=~\"$application:reportResultCache\"}[90s])",
     "legendFormat": "removals"
    }
   ]
  },
  {
   "title": "Queries Cache average time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 225 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "cache_average_get_time{kubernetes_namespace=~\"$namespace\", instance=~\"$instance\", cacheName=~\"$application:reportQueriesCache\"}",
     "legendFormat": "get time"
    },
    {
     "expr": "cache_average_put_time{kubernetes_namespace=~\"$namespace\", instance=~\"$instance\", cacheName=~\"$application:reportQueriesCache\"}",
     "legendFormat": "put time"
    },
    {
     "expr": "cache_average_remove_time{kubernetes_namespace=~\"$namespace\", instance=~\"$instance\", cacheName=~\"$application:reportQueriesCache\"}",
     "legendFormat": "remove time"
    }
   ]
  },
  {
   "title": "Reports Cache average time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 225 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "cache_average_get_time{kubernetes_namespace=~\"$namespace\", instance=~\"$instance\", cacheName=~\"$application:reportResultCache\"}",
     "legendFormat": "get time"
    },
    {
     "expr": "cache_average_put_time{kubernetes_namespace=~\"$namespace\", instance=~\"$instance\", cacheName=~\"$application:reportResultCache\"}",
     "legendFormat": "put time"
    },
    {
     "expr": "cache_average_remove_time{kubernetes_namespace=~\"$namespace\", instance=~\"$instance\", cacheName=~\"$application:reportResultCache\"}",
     "legendFormat": "remove time"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 233 },
   "options": {
    "content": "<div style=~\"text-align: center;\"><i><strong style=~\"color: #CCCCCC; font-size: 40px;\">Performance Tests</strong></i></div>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Percentiles",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 236 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "aliasByMetric(smartSummarize(locust.reporting-service.Total.ok.percentile75, '1d', 'avg'))"
    },
    {
     "target": "aliasByMetric(smartSummarize(locust.reporting-service.Total.ok.percentile90, '1d', 'avg'))"
    },
    {
     "target": "aliasByMetric(smartSummarize(locust.reporting-service.Total.ok.percentile95, '1d', 'avg'))"
    },
    {
     "target": "aliasByMetric(smartSummarize(locust.reporting-service.Total.ok.percentile99, '1d', 'avg'))"
    }
   ]
  },
  {
   "title": "Percentiles",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 243 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "target": "aliasByMetric(locust.reporting-service.Total.ok.percentile75)"
    },
    {
     "target": "aliasByMetric(locust.reporting-service.Total.ok.percentile95)"
    },
    {
     "target": "aliasByMetric(locust.reporting-service.Total.ok.percentile99)"
    }
   ]
  },
  {
   "title": "RPS",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 250 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "aliasByMetric(locust.reporting-service.Total.ok.rps)"
    }
   ]
  },
  {
   "title": "OK vs KO",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 256 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "aliasByNode(locust.reporting-service.Total.ok.count, 3)"
    },
    {
     "target": "aliasByNode(locust.reporting-service.Total.ko.count, 3)"
    }
   ]
  }
 ]
}