{
 "title": "Service Metrics",
 "tags": [ "svc-metrics" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(jvm_info,kubernetes_namespace)"
    }
   },
   {
    "name": "service_name",
    "label": "service_name",
    "query": {
     "query": "label_values(up{kubernetes_namespace=~\"$namespace\"},kubernetes_name)"
    }
   },
   {
    "name": "pod_ip",
    "label": "pod_ip",
    "query": {
     "query": "label_values(up{kubernetes_namespace=~\"$namespace\", kubernetes_name=~\"$service_name\"},instance)"
    }
   },
   {
    "name": "pod",
    "label": "pod",
    "query": {
     "query": "label_values(container_memory_usage_bytes{namespace=~\"$namespace\", pod=~\"$service_name.*\"},pod)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Non-Heap Memory",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_used{instance=~\"$pod_ip\",kubernetes_name=~\"$service_name.*\",kubernetes_namespace=~\"$namespace\",pool=~\"Code Cache\"}",
     "legendFormat": "code cache {{kubernetes_name}}"
    },
    {
     "expr": "jvm_memory_pool_bytes_used{instance=~\"$pod_ip\",kubernetes_name=~\"$service_name.*\",kubernetes_namespace=~\"$namespace\",pool=~\"Compressed Class Space\"}",
     "legendFormat": "class space {{kubernetes_name}}"
    },
    {
     "expr": "jvm_memory_pool_bytes_used{instance=~\"$pod_ip\",kubernetes_name=~\"$service_name.*\",kubernetes_namespace=~\"$namespace\",pool=~\"Metaspace\"}",
     "legendFormat": "metaspace {{kubernetes_name}}"
    }
   ]
  },
  {
   "title": "JVM memory",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "jvm_memory_bytes_max{area=~\"heap\",instance=~\"$pod_ip\",kubernetes_name=~\"$service_name\",kubernetes_namespace=~\"$namespace\"}",
     "legendFormat": "heap limit {{kubernetes_name}}"
    },
    {
     "expr": "jvm_memory_bytes_used{area=~\"heap\",instance=~\"$pod_ip\",kubernetes_name=~\"$service_name\",kubernetes_namespace=~\"$namespace\"}",
     "legendFormat": "used heap {{kubernetes_name}}"
    },
    {
     "expr": "jvm_memory_bytes_max{area=~\"nonheap\",instance=~\"$pod_ip\",kubernetes_name=~\"$service_name\",kubernetes_namespace=~\"$namespace\"}",
     "legendFormat": "nonheap limit {{kubernetes_name}}"
    },
    {
     "expr": "jvm_memory_bytes_used{area=~\"nonheap\",instance=~\"$pod_ip\",kubernetes_name=~\"$service_name\",kubernetes_namespace=~\"$namespace\"}",
     "legendFormat": "used nonheap {{kubernetes_name}}"
    }
   ]
  },
  {
   "title": "Pod Memory &  Swap",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{namespace=~\"$namespace\" , pod=~\"$pod\", container=~\"$service_name|service-gateway\"}",
     "legendFormat": "memory {{pod}}"
    },
    {
     "expr": "container_memory_swap{namespace=~\"$namespace\" , pod=~\"$pod\", container=~\"$service_name|service-gateway\"}",
     "legendFormat": "swap {{pod}}"
    }
   ]
  },
  {
   "title": "Container Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{container=~\"$service_name|service-gateway\", namespace=~\"$namespace\",pod=~\"$pod\"} ",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Heap Memory By Generations",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_used{instance=~\"$pod_ip\",kubernetes_name=~\"$service_name\",kubernetes_namespace=~\"$namespace\",pool=~\".*\"}",
     "legendFormat": "{{pool}} {{kubernetes_name}}"
    }
   ]
  },
  {
   "title": "GC collection time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(jvm_gc_collection_seconds_sum{instance=~\"$pod_ip\",kubernetes_name=~\"$service_name\",kubernetes_namespace=~\"$namespace\"}[$__rate_interval])",
     "legendFormat": "{{gc}} {{kubernetes_name}} "
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum (rate(container_cpu_usage_seconds_total{pod=~\"$pod\", image!~\"\",namespace=~\"$namespace\",container=~\"$service_name|service-gateway\",kubernetes_io_hostname=~\".+\"}[$__rate_interval])) by (pod,container)",
     "legendFormat": "cpu usage {{pod}} "
    }
   ]
  },
  {
   "title": "threading",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "jvm_threads_current{instance=~\"$pod_ip\",kubernetes_name=~\"$service_name\",kubernetes_namespace=~\"$namespace\"}",
     "legendFormat": "threads count {{kubernetes_name}}"
    }
   ]
  },
  {
   "title": "Request/Response Per Second",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(jetty_requests_total{instance=~\"$pod_ip\",kubernetes_name=~\"$service_name\",kubernetes_namespace=~\"$namespace\"}[$__rate_interval])",
     "legendFormat": "request per second {{kubernetes_name}}"
    },
    {
     "expr": "-rate(jetty_responses_total{code=~\"2xx\", instance=~\"$pod_ip\",kubernetes_name=~\"$service_name\",kubernetes_namespace=~\"$namespace\"}[$__rate_interval])",
     "legendFormat": "2xx response per second {{kubernetes_name}}"
    }
   ]
  },
  {
   "title": "jvm threads state",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "jvm_threads_state{instance=~\"$pod_ip\", kubernetes_name=~\"$service_name\", kubernetes_namespace=~\"$namespace\"}",
     "legendFormat": "{{state}} {{kubernetes_name}}"
    }
   ]
  },
  {
   "title": "jetty thread pool",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "jetty_thread_pool_size{instance=~\"$pod_ip\", kubernetes_name=~\"$service_name\", kubernetes_namespace=~\"$namespace\"}",
     "legendFormat": "size {{kubernetes_name}}"
    },
    {
     "expr": "jetty_thread_pool_max_size{instance=~\"$pod_ip\", kubernetes_name=~\"$service_name\", kubernetes_namespace=~\"$namespace\"}",
     "legendFormat": "max {{kubernetes_name}}"
    },
    {
     "expr": "jetty_thread_pool_queued{instance=~\"$pod_ip\", kubernetes_name=~\"$service_name\", kubernetes_namespace=~\"$namespace\"}",
     "legendFormat": "queued {{kubernetes_name}}"
    },
    {
     "expr": "jetty_thread_pool_busy{instance=~\"$pod_ip\", kubernetes_name=~\"$service_name\", kubernetes_namespace=~\"$namespace\"}",
     "legendFormat": "busy {{kubernetes_name}}"
    }
   ]
  },
  {
   "title": "jetty thread pool",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "jetty_thread_pool_size{instance=~\"$pod_ip\", kubernetes_name=~\"$service_name\",  kubernetes_namespace=~\"$namespace\"}",
     "legendFormat": "threads {{kubernetes_name}}"
    },
    {
     "expr": "jetty_thread_pool_busy{instance=~\"$pod_ip\", kubernetes_name=~\"$service_name\",  kubernetes_namespace=~\"$namespace\"}",
     "legendFormat": "busy {{kubernetes_name}}"
    },
    {
     "expr": "jetty_thread_pool_idle{instance=~\"$pod_ip\", kubernetes_name=~\"$service_name\", kubernetes_namespace=~\"$namespace\"}",
     "legendFormat": "idle {{kubernetes_name}}"
    },
    {
     "expr": "jetty_thread_pool_queued{instance=~\"$pod_ip\", kubernetes_name=~\"$service_name\", kubernetes_namespace=~\"$namespace\"}",
     "legendFormat": "queued {{kubernetes_name}}"
    },
    {
     "expr": "jetty_thread_pool_max_size{instance=~\"$instance\", kubernetes_name=~\"$service_name\", kubernetes_namespace=~\"$namespace\"}",
     "legendFormat": "max {{kubernetes_name}}"
    },
    {
     "expr": "jetty_thread_pool_min_size{instance=~\"$instance\", kubernetes_name=~\"$service_name\", kubernetes_namespace=~\"$namespace\"}",
     "legendFormat": "min {{kubernetes_name}}"
    }
   ]
  },
  {
   "title": "Network I/O",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum (idelta (container_network_receive_bytes_total{pod=~\"$pod\", image!~\"\",namespace=~\"$namespace\",kubernetes_io_hostname=~\".+\"}[$__rate_interval])) by (pod)",
     "legendFormat": "received {{pod}}"
    },
    {
     "expr": "- sum (idelta (container_network_transmit_bytes_total{pod=~\"$pod\", image!~\"\",namespace=~\"$namespace\",kubernetes_io_hostname=~\".+\"}[$__rate_interval])) by (pod)",
     "legendFormat": "transmited {{pod}}"
    }
   ]
  },
  {
   "title": "Service Up Time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 95 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "up{kubernetes_name=~\"$service_name\",kubernetes_namespace=~\"$namespace\", instance=~\"$pod_ip\"}",
     "legendFormat": "{{kubernetes_name}} {{instance}}"
    }
   ]
  },
  {
   "title": "1XX  Count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 102 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(jetty_responses_total{code=~\"1xx\",instance=~\"$pod_ip\",kubernetes_name=~\"$service_name\",kubernetes_namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "2XX  Count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 102 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(jetty_responses_total{code=~\"2xx\", kubernetes_name=~\"$service_name\",kubernetes_namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "3XX  Count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 102 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(jetty_responses_total{code=~\"3xx\",instance=~\"$pod_ip\",kubernetes_name=~\"$service_name\",kubernetes_namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "4XX  Count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 102 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(jetty_responses_total{code=~\"4xx\",instance=~\"$pod_ip\",kubernetes_name=~\"$service_name\",kubernetes_namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "5XX  Count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 102 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(jetty_responses_total{code=~\"5xx\",instance=~\"$pod_ip\",kubernetes_name=~\"$service_name\",kubernetes_namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "All Pods 400s",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 105 },
   "targets": [
    {
     "expr": "jetty_responses_total{code=~\"4xx\",kubernetes_name=~\"$service_name\",kubernetes_namespace=~\"$namespace\"}",
     "legendFormat": "{{kubernetes_namespace}} {{kubernetes_name}}"
    }
   ]
  },
  {
   "title": "IO Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 113 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(container_fs_write_bytes_total{pod=~\"$pod\", container=~\"$service_name|service-gateway\", namespace=~\"$namespace\"}[$__rate_interval])\n",
     "legendFormat": "Write {{pod}}"
    },
    {
     "expr": "-rate(container_fs_reads_bytes_total{pod=~\"$pod\", container=~\"$service_name|service-gateway\", namespace=~\"$namespace\"}[$__rate_interval])\n",
     "legendFormat": "Read {{pod}}"
    }
   ]
  }
 ]
}