{
 "title": "service to service call metrics",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(service_to_service_execution_seconds_bucket,kubernetes_namespace)"
    }
   },
   {
    "name": "service",
    "label": "service",
    "query": {
     "query": "label_values(service_to_service_execution_seconds_count{ kubernetes_namespace=~\"$namespace\" }, kubernetes_name)"
    }
   },
   {
    "name": "target",
    "query": {
     "query": "label_values(service_to_service_execution_seconds_count{kubernetes_name=~\"$service\", kubernetes_namespace=~\"$namespace\"}, target_service)"
    }
   },
   {
    "name": "project",
    "label": "project",
    "query": {
     "query": "label_values(service_to_service_execution_seconds_bucket{kubernetes_namespace=\"$namespace\",kubernetes_name=~\"$service\"}, app)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Request count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(service_to_service_execution_seconds_count{kubernetes_name=~\"$service\", app=\"$project\", kubernetes_namespace=~\"$namespace\", target_service=~\"$target\"}[$__rate_interval])) by (target_service)",
     "legendFormat": "qps {{target_service}}"
    }
   ]
  },
  {
   "title": "Percentile",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.75, sum(rate(service_to_service_execution_seconds_bucket{kubernetes_namespace=~\"$namespace\", kubernetes_name=~\"$service\", app=~\"$project\", target_service=~\"$target\"}[$__rate_interval])) by (le,target_service))",
     "legendFormat": "75 {{target_service}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(service_to_service_execution_seconds_bucket{kubernetes_namespace=~\"$namespace\", kubernetes_name=~\"$service\", app=~\"$project\", target_service=~\"$target\"}[$__rate_interval])) by (le,target_service))",
     "legendFormat": "95 {{target_service}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(service_to_service_execution_seconds_bucket{kubernetes_namespace=~\"$namespace\", kubernetes_name=~\"$service\", app=~\"$project\", target_service=~\"$target\"}[$__rate_interval])) by (le,target_service))",
     "legendFormat": "99 {{target_service}}"
    },
    {
     "expr": "histogram_quantile(1.0, sum(rate(service_to_service_execution_seconds_bucket{kubernetes_namespace=~\"$namespace\", kubernetes_name=~\"$service\", app=~\"$project\", target_service=~\"$target\"}[$__rate_interval])) by (le,target_service))",
     "legendFormat": "max {{target_service}}"
    }
   ]
  },
  {
   "title": "Request count  OK vs KO",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(service_to_service_execution_result_total{kubernetes_name=~\"$service\", kubernetes_namespace=~\"$namespace\", target_service=~\"$target\", app=~\"$project\", status=~\"OK\"}[$__rate_interval])) by(target_service)",
     "legendFormat": "ok {{target_service}}"
    },
    {
     "expr": "sum(rate(service_to_service_execution_result_total{kubernetes_name=~\"$service\", kubernetes_namespace=~\"$namespace\", target_service=~\"$target\", app=~\"$project\", status=~\"KO\"}[$__rate_interval])) by(target_service)",
     "legendFormat": "ko {{target_service}}"
    }
   ]
  },
  {
   "title": "OK vs KO",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "service_to_service_execution_result_total{kubernetes_name=~\"$service\", kubernetes_namespace=~\"$namespace\", target_service=~\"$target\", app=~\"$project\"}",
     "legendFormat": "{{ status }} to {{ target_service }}"
    }
   ]
  }
 ]
}