{
 "title": "service query execution times",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(multidatasource_query_execution_seconds_bucket,kubernetes_namespace)"
    }
   },
   {
    "name": "service",
    "label": "service",
    "query": {
     "query": "label_values(multidatasource_query_execution_seconds_bucket,kubernetes_name)"
    }
   },
   {
    "name": "project",
    "label": "project",
    "query": {
     "query": "label_values(multidatasource_query_execution_seconds_bucket{kubernetes_namespace=\"$namespace\"},app)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Query execution count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(multidatasource_query_execution_seconds_count{kubernetes_name=~\"$service\", kubernetes_namespace=\"$namespace\",app=~\"$project\" }[$__rate_interval] ) )by(app,kubernetes_name)",
     "legendFormat": "qps {{app}} {{kubernetes_name}}"
    }
   ]
  },
  {
   "title": "Query execution time percentile",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(multidatasource_query_execution_seconds_bucket{kubernetes_namespace=\"$namespace\", kubernetes_name=~\"$service\", app=~\"$project\"}[$__rate_interval])) by (le, kubernetes_name, app))",
     "legendFormat": "95 {{kubernetes_name}} {{app}}"
    },
    {
     "expr": "histogram_quantile(1.0, sum(rate(multidatasource_query_execution_seconds_bucket{kubernetes_namespace=\"$namespace\", kubernetes_name=\"$service\", app=\"$project\"}[$__rate_interval])) by (le))",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "PreparedStatement duration percentile",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.75, sum(rate(multidatasource_prepared_statement_open_seconds_bucket{kubernetes_namespace=\"$namespace\", kubernetes_name=~\"$service\", app=~\"$project\"}[$__rate_interval])) by (le))",
     "legendFormat": "75"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(multidatasource_prepared_statement_open_seconds_bucket{kubernetes_namespace=\"$namespace\", kubernetes_name=~\"$service\", app=~\"$project\"}[$__rate_interval])) by (le))",
     "legendFormat": "95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(multidatasource_prepared_statement_open_seconds_bucket{kubernetes_namespace=\"$namespace\", kubernetes_name=\"$service\", app=\"$project\"}[$__rate_interval])) by (le))",
     "legendFormat": "99"
    },
    {
     "expr": "histogram_quantile(1.0, sum(rate(multidatasource_prepared_statement_open_seconds_bucket{kubernetes_namespace=\"$namespace\", kubernetes_name=\"$service\", app=\"$project\"}[$__rate_interval])) by (le))",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "Statement duration percentile",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.75, sum(rate(multidatasource_statement_open_seconds_bucket{kubernetes_namespace=\"$namespace\", kubernetes_name=~\"$service\", app=~\"$project\"}[$__rate_interval])) by (le))",
     "legendFormat": "75"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(multidatasource_statement_open_seconds_bucket{kubernetes_namespace=\"$namespace\", kubernetes_name=~\"$service\", app=~\"$project\"}[$__rate_interval])) by (le))",
     "legendFormat": "95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(multidatasource_statement_open_seconds_bucket{kubernetes_namespace=\"$namespace\", kubernetes_name=~\"$service\", app=~\"$project\"}[$__rate_interval])) by (le))",
     "legendFormat": "99"
    },
    {
     "expr": "histogram_quantile(1.0, sum(rate(multidatasource_statement_open_seconds_bucket{kubernetes_namespace=\"$namespace\", kubernetes_name=~\"$service\", app=~\"$project\"}[$__rate_interval])) by (le))",
     "legendFormat": "max"
    }
   ]
  }
 ]
}