{
 "title": "Stability",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "environment",
    "label": "environment",
    "query": {
     "query": "label_values(jvm_info, kubernetes_namespace)"
    }
   },
   {
    "name": "app_id",
    "query": {
     "query": "label_values(service_redis_connection{kubernetes_namespace=~\"$environment\"}, appId)"
    }
   },
   {
    "name": "service",
    "label": "service",
    "query": {
     "query": "label_values(service_health_check_response_count_for_app, serviceKey)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Redis Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "count(service_redis_connection{kubernetes_namespace=~\"$environment\", serviceKey=~\"$service\"}==1)",
     "legendFormat": "CONNECTED"
    },
    {
     "expr": "count(service_redis_connection{kubernetes_namespace=~\"$environment\", serviceKey=~\"$service\"}<=0)",
     "legendFormat": "NOT CONNECTED"
    }
   ]
  },
  {
   "title": "Rabbit Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count(service_rabbit_connection{kubernetes_namespace=~\"$environment\", serviceKey=~\"$service\"}==1)",
     "legendFormat": "CONNECTED"
    },
    {
     "expr": "count(service_rabbit_connection{kubernetes_namespace=~\"$environment\", serviceKey=~\"$service\"}<=0)",
     "legendFormat": "NOT CONNECTED"
    }
   ]
  },
  {
   "title": "DB Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count(service_db_connection{kubernetes_namespace=~\"$environment\", serviceKey=~\"$service\"}==1)",
     "legendFormat": "CONNECTED"
    },
    {
     "expr": "count(service_db_connection{kubernetes_namespace=~\"$environment\", serviceKey=~\"$service\"}<=0)",
     "legendFormat": "NOT CONNECTED"
    }
   ]
  },
  {
   "title": "Storage Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count(service_storage_connection{kubernetes_namespace=~\"$environment\", serviceKey=~\"$service\"}==1)",
     "legendFormat": "CONNECTED"
    },
    {
     "expr": "count(service_storage_connection{kubernetes_namespace=~\"$environment\", serviceKey=~\"$service\"}<=0)",
     "legendFormat": "NOT CONNECTED"
    }
   ]
  },
  {
   "title": "Redis disk usage %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100- (kubelet_volume_stats_available_bytes{namespace=~\"$environment\",persistentvolumeclaim=~\"redis-pvc\"} / kubelet_volume_stats_capacity_bytes{namespace=~\"$environment\",persistentvolumeclaim=~\"redis-pvc\"}  *100)",
     "legendFormat": "{{namespace}} {{persistentvolumeclaim}} usage "
    }
   ]
  },
  {
   "title": "# of queues without consumer",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(rabbitmq_queue_consumers{environment=\"$environment\", job=\"rabbitmq-exporter\",\n  queue!~\".*retry\",\n  queue!~\".*-exchange-tracker\",\n  queue!~\"^SIS.+\",\n  queue!~\"^sis.+\",\n  queue!~\"^Sis.+\",\n  queue!~\"^DESKTOP.+\",\n  queue!~\"messaging-upgraded-services\",\n  queue!~\"health-status-result-test\",\n  queue!~\"^reporting-service-sync.+\",\n  queue!~\".+-v1.+\",\n  queue!~\"^macadmins.+\",\n  queue!~\"^localhost.+\",\n  queue!~\"^[0-9].+\",\n  queue!~\"health-status-result\",\n  queue!~\"^kube-master-dev.+\"\n  }==0)",
     "legendFormat": "{{queue}}"
    }
   ]
  },
  { "title": "Detailed", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Redis Connections per Service",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "(service_redis_connection{appId=~\"$app_id\", kubernetes_namespace=~\"$environment\", serviceKey=~\"$service\"}) > BOOL 0.99",
     "legendFormat": "{{serviceKey}}-{{appId}}"
    }
   ]
  },
  {
   "title": "Rabbit Connections per Service",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "service_rabbit_connection{appId=~\"$app_id\", kubernetes_namespace=~\"$environment\", serviceKey=~\"$service\"} > BOOL 0.99",
     "legendFormat": "{{serviceKey}}-{{appId}}"
    }
   ]
  },
  {
   "title": "DB Connections per Service",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "service_db_connection{appId=~\"$app_id\", kubernetes_namespace=~\"$environment\", serviceKey=~\"$service\"} > BOOL 0.99",
     "legendFormat": "{{serviceKey}}-{{appId}}"
    }
   ]
  },
  {
   "title": "Storage Connections per Service",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "service_storage_connection{appId=~\"$app_id\", kubernetes_namespace=~\"$environment\", serviceKey=~\"$service\"} > BOOL 0.99",
     "legendFormat": "{{serviceKey}}-{{appId}}"
    }
   ]
  }
 ]
}