{
 "title": "Tier-1 SLO",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(up,kubernetes_namespace)"
    }
   },
   {
    "name": "service",
    "label": "service",
    "query": {
     "query": "label_values( up{kubernetes_namespace=~\"$namespace\",kubernetes_name!~\"redis-exporter\"} , kubernetes_name)"
    }
   },
   { "name": "availability_span", "label": "availability_span", "query": "1h,2h,6h,12h,1d,2d,7d,30d" },
   {
    "name": "app_ids",
    "label": "app_ids",
    "query": {
     "query": "label_values(service_request_seconds_bucket{kubernetes_name=\"classifierservice-v1\"},app)"
    }
   },
   {
    "name": "elasticsearch",
    "label": "log-service",
    "query": {
     "query": "label_values( up{job=\"kubernetes-service-endpoints\", kubernetes_namespace=\"$namespace\",kubernetes_name=~\"$service\"} , kubernetes_name)"
    }
   },
   {
    "name": "elastic_env",
    "label": "elastic_env",
    "query": {
     "query": "label_values(nginx_http_requests_count_ui,domain)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "SLO over $availability_span (from service metrics)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Success Rate",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg_over_time(\r\n    min(\r\n (sum_over_time(((\r\n  (\r\n    (sum(rate(service_response_status_total{kubernetes_name=~\"$service\", kubernetes_namespace=~\"$namespace\", app=~\"$app_ids\", status!~\"5..\"}[$__rate_interval])) by (kubernetes_name))\r\n    /\r\n    (sum(rate(service_response_status_total{kubernetes_name=~\"$service\", kubernetes_namespace=~\"$namespace\", app=~\"$app_ids\"}[$__rate_interval])) by (kubernetes_name))\r\n  ) > bool 0.995)\r\n  +\r\n  (sum(rate(service_response_status_total{kubernetes_name=~\"$service\", kubernetes_namespace=~\"$namespace\", app=~\"$app_ids\"}[$__rate_interval])) by (kubernetes_name) == bool 0)\r\n)[$availability_span:])\r\n/\r\ncount_over_time(sum(rate(service_response_status_total{kubernetes_name=~\"$service\", kubernetes_namespace=~\"$namespace\", app=~\"$app_ids\"}[$__rate_interval])) by (kubernetes_name)[$availability_span:])\r\n)\r\n    )\r\n[$availability_span:])\r\n\r\n",
     "legendFormat": "$namespace"
    }
   ]
  },
  {
   "title": "POD Availability",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg_over_time(\r\n    min(\r\n        sum_over_time( (sum(up{kubernetes_name=~\"$service\",kubernetes_namespace=~\"$namespace\"}) by (kubernetes_name) >=bool 1) [$availability_span:] )\r\n        / \r\n        count_over_time(sum(up{kubernetes_name=~\"$service\",kubernetes_namespace=~\"$namespace\"}) by (kubernetes_name) [$availability_span:])\r\n    )\r\n[$availability_span:])\r\n"
    }
   ]
  },
  {
   "title": "99th Latency",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(\r\navg(sum_over_time((histogram_quantile(0.99, sum(rate(service_request_seconds_bucket{kubernetes_namespace=\"$namespace\", kubernetes_name=~\"$service\", method!=\"OPTION\", app=~\"$app_ids\"}[$__rate_interval]) )  by (le,kubernetes_name))  <= bool 0.5) [$availability_span:] ))            \r\n/\r\navg(sum_over_time((sum(rate(service_request_seconds_count{kubernetes_name=~\"$service\", kubernetes_namespace=\"$namespace\",  method!=\"OPTION\", app=~\"$app_ids\"}[$__rate_interval])) by (kubernetes_name) > bool 0) [$availability_span:]))\r\n)"
    }
   ]
  },
  {
   "title": "95th Latency",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(\r\navg(sum_over_time((histogram_quantile(0.95, sum(rate(service_request_seconds_bucket{kubernetes_namespace=\"$namespace\", kubernetes_name=~\"$service\", method!=\"OPTION\", app=~\"$app_ids\"}[$__rate_interval]) )  by (le,kubernetes_name))  <= bool 0.25) [$availability_span:] ) )           \r\n/\r\navg(sum_over_time((sum(rate(service_request_seconds_count{kubernetes_name=~\"$service\", kubernetes_namespace=\"$namespace\",  method!=\"OPTION\", app=~\"$app_ids\"}[$__rate_interval])) by (kubernetes_name) > bool 0) [$availability_span:]))\r\n)"
    }
   ]
  },
  {
   "title": "Restarts Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(floor(increase(kube_pod_container_status_restarts_total{ namespace=~\"$namespace\", container=~\"$service\"}[$__range])))",
     "legendFormat": "{{namespace}} {{container}}"
    }
   ]
  },
  {
   "title": "ERROR log count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:488",
       "field": "@timestamp",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:486", "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "app.environment: \"$namespace\" AND app.service.name: \"$elasticsearch\" AND app.loglevel: \"error\"  AND app.loglevel: \"ERROR\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Nginx SLO over $availability_span  (all service calls from UI)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "$namespace _Success_Rate_nginx",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "avg_over_time(\r\n    min(\r\n        sum_over_time(\r\n\r\n        (\r\n\r\n        (sum(rate(nginx_http_requests_count_ui{domain=~\"$elastic_env\",status=\"all\"}[$__rate_interval])) - sum(rate(nginx_http_requests_count_ui{domain=~\"$elastic_env\",status=~\"5xx\"}[$__rate_interval]))) \r\n                    / \r\n        (sum(rate(nginx_http_requests_count_ui{domain=~\"$elastic_env\",status=\"all\"}[$__rate_interval]))) \r\n\r\n        )\r\n        [$availability_span:])\r\n        / \r\n        count_over_time(sum(rate(nginx_http_requests_count_ui{domain=~\"$elastic_env\",status=\"all\"}[$__rate_interval])) [$availability_span:])\r\n    )\r\n[$availability_span:])\r\n\r\n\r\n\r\n"
      }
     ]
    },
    {
     "title": "99th Latency",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 4, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "avg(\r\n    sum(rate(nginx_http_response_time{domain=\"$elastic_env\", lt=\"1\"} [$__rate_interval] ))  \r\n    / \r\n    sum(rate(nginx_http_requests_count_ui{domain=\"$elastic_env\",status=\"all\"} [$__rate_interval] ))\r\n)",
       "legendFormat": "$elastic_env Latency"
      }
     ]
    },
    {
     "title": "95th Latency",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 8, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "avg(\r\n    sum(rate(nginx_http_response_time{domain=\"$elastic_env\", lt=\"0.5\"} [$__rate_interval] ))  \r\n    / \r\n    sum(rate(nginx_http_requests_count_ui{domain=\"$elastic_env\",status=\"all\"} [$__rate_interval] ))\r\n)",
       "legendFormat": "$elastic_env Latency"
      }
     ]
    }
   ]
  },
  {
   "title": "SLOs over $availability_span (all calls from UI)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "$namespace _Success_Rate_nginx",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "avg_over_time(\r\n    min(\r\n        sum_over_time(\r\n\r\n        (\r\n\r\n        (sum(rate(nginx_http_requests_count_total{domain=~\"$elastic_env\",status=\"all\"}[$__rate_interval])) - sum(rate(nginx_http_requests_count_total{domain=~\"$elastic_env\",status=~\"5xx\"}[$__rate_interval]))) \r\n                    / \r\n        (sum(rate(nginx_http_requests_count_total{domain=~\"$elastic_env\",status=\"all\"}[$__rate_interval]))) \r\n\r\n        )\r\n        [$availability_span:])\r\n        / \r\n        count_over_time(sum(rate(nginx_http_requests_count_total{domain=~\"$elastic_env\",status=\"all\"}[$__rate_interval])) [$availability_span:])\r\n    )\r\n[$availability_span:])\r\n\r\n\r\n\r\n"
      }
     ]
    },
    {
     "title": "99th Latency",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 4, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "avg(\r\n    sum(rate(nginx_http_response_time{domain=\"$elastic_env\", lt=\"1\"} [$__rate_interval] ))  \r\n    / \r\n    sum(rate(nginx_http_requests_count_total{domain=\"$elastic_env\",status=\"all\"} [$__rate_interval] ))\r\n)",
       "legendFormat": "$elastic_env Latency"
      }
     ]
    },
    {
     "title": "95th Latency",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 8, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "avg(\r\n    sum(rate(nginx_http_response_time{domain=\"$elastic_env\", lt=\"0.5\"} [$__rate_interval] ))  \r\n    / \r\n    sum(rate(nginx_http_requests_count_total{domain=\"$elastic_env\",status=\"all\"} [$__rate_interval] ))\r\n)",
       "legendFormat": "$elastic_env Latency"
      }
     ]
    }
   ]
  },
  {
   "title": "Availability Detailed",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Success Rate SLO over $availability_span",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(sum_over_time(((\r\n  (\r\n    (sum(rate(service_response_status_total{kubernetes_name=~\"$service\", kubernetes_namespace=~\"$namespace\", app=~\"$app_ids\", status!~\"5..\"}[$__rate_interval])) by (kubernetes_name))\r\n    /\r\n    (sum(rate(service_response_status_total{kubernetes_name=~\"$service\", kubernetes_namespace=~\"$namespace\", app=~\"$app_ids\"}[$__rate_interval])) by (kubernetes_name))\r\n  ) > bool 0.995)\r\n  +\r\n  (sum(rate(service_response_status_total{kubernetes_name=~\"$service\", kubernetes_namespace=~\"$namespace\", app=~\"$app_ids\"}[$__rate_interval])) by (kubernetes_name) == bool 0)\r\n)[$availability_span:])\r\n/\r\ncount_over_time(sum(rate(service_response_status_total{kubernetes_name=~\"$service\", kubernetes_namespace=~\"$namespace\", app=~\"$app_ids\"}[$__rate_interval])) by (kubernetes_name)[$availability_span:])\r\n)",
     "legendFormat": "{{kubernetes_name}}"
    }
   ]
  },
  {
   "title": "POD Availability SLO over $availability_span",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "\nsum_over_time( (sum(up{kubernetes_name=~\"$service\",kubernetes_namespace=~\"$namespace\"}) by (kubernetes_name) >=bool 1) [$availability_span:] )\n/ \ncount_over_time(sum(up{kubernetes_name=~\"$service\",kubernetes_namespace=~\"$namespace\"}) by (kubernetes_name) [$availability_span:])\n",
     "legendFormat": "{{kubernetes_name}} availability slo"
    }
   ]
  },
  {
   "title": "Success Rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "\t\n\n(sum(rate(service_response_status_total{kubernetes_name=~\"$service\", kubernetes_namespace=\"$namespace\", app=~\"$app_ids\", status!~\"5..\"}[$__rate_interval])) by (kubernetes_name) )\n/\n(sum(rate(service_response_status_total{kubernetes_name=~\"$service\", kubernetes_namespace=\"$namespace\", app=~\"$app_ids\"}[$__rate_interval])) by (kubernetes_name) )\n",
     "legendFormat": "{{ kubernetes_name}}"
    }
   ]
  },
  {
   "title": "POD Availability",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "up{kubernetes_name=~\"$service\",kubernetes_namespace=~\"$namespace\"}",
     "legendFormat": "{{kubernetes_name}} availability"
    }
   ]
  },
  {
   "title": "Restarts Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(sum(up{job=\"kubernetes-service-endpoints\",kubernetes_namespace=\"$namespace\",kubernetes_name=~\"$service\" } != 0) by (kubernetes_name) - 1) by (kubernetes_name)",
     "legendFormat": "{{kubernetes_name}} "
    }
   ]
  },
  {
   "title": "ERROR log count $elasticsearch",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:70",
       "field": "@timestamp",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:68", "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "app.environment: \"$namespace\" AND app.service.name: \"$elasticsearch\" AND app.loglevel: \"error\"  AND app.loglevel: \"ERROR\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "nginx RPS $elasticsearch",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:327",
       "field": "@timestamp",
       "id": "2",
       "settings": { "interval": "1ms", "min_doc_count": 1, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:325", "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "type:\"nginx-access\" AND request_host:\"$elastic_env\" AND nginx.service.name:\"$elasticsearch\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 },
   "targets": [
    {}
   ]
  },
  {
   "title": "99th Latency SLO over $availability_span",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "\nsum_over_time((histogram_quantile(0.99, sum(rate(service_request_seconds_bucket{kubernetes_namespace=\"$namespace\", kubernetes_name=~\"$service\", method!=\"OPTION\", app=~\"$app_ids\"}[$__rate_interval]) )  by (le,kubernetes_name))  <= bool 0.5) [$availability_span:] )            \n/\nsum_over_time((sum(rate(service_request_seconds_count{kubernetes_name=~\"$service\", kubernetes_namespace=\"$namespace\",  method!=\"OPTION\", app=~\"$app_ids\"}[$__rate_interval])) by (kubernetes_name) > bool 0) [$availability_span:])",
     "legendFormat": "99-th slo {{kubernetes_name}}"
    }
   ]
  },
  {
   "title": "95th Latency SLO over $availability_span",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum_over_time((histogram_quantile(0.95, sum(rate(service_request_seconds_bucket{kubernetes_namespace=\"$namespace\", kubernetes_name=~\"$service\", method!=\"OPTION\", app=~\"$app_ids\"}[$__rate_interval]) )  by (le,kubernetes_name))  <= bool 0.25) [$availability_span:] )            \n/\nsum_over_time((sum(rate(service_request_seconds_count{kubernetes_name=~\"$service\", kubernetes_namespace=\"$namespace\",  method!=\"OPTION\", app=~\"$app_ids\"}[$__rate_interval])) by (kubernetes_name) > bool 0) [$availability_span:])",
     "legendFormat": "95-th slo: {{ kubernetes_name}}"
    }
   ]
  },
  {
   "title": "99th Latency",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(service_request_seconds_bucket{kubernetes_namespace=\"$namespace\", kubernetes_name=~\"$service\", method!=\"OPTION\", app=~\"$app_ids\"}[$__rate_interval])) by (le,kubernetes_name)) ",
     "legendFormat": "99th {{kubernetes_name}}"
    }
   ]
  },
  {
   "title": "95th Latency",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(service_request_seconds_bucket{kubernetes_namespace=\"$namespace\", kubernetes_name=~\"$service\", method!=\"OPTION\", app=~\"$app_ids\"}[$__rate_interval])) by (le,kubernetes_name)) ",
     "legendFormat": "95-th: {{ kubernetes_name}}"
    }
   ]
  }
 ]
}