{
 "title": "VERTX Service Metrics",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(jvm_info, kubernetes_namespace)"
    }
   },
   {
    "name": "service_name",
    "label": "service_name",
    "query": {
     "query": "label_values(vertx_http_server_active_connections{kubernetes_namespace=\"$namespace\"},kubernetes_name)"
    }
   },
   {
    "name": "pod_ip",
    "label": "pod_ip",
    "query": {
     "query": "label_values(vertx_http_server_active_connections{kubernetes_namespace=\"$namespace\", kubernetes_name=\"$service_name\"},instance)"
    }
   },
   {
    "name": "pod_name",
    "label": "pod_name",
    "query": {
     "query": "label_values(container_memory_usage_bytes{namespace=\"$namespace\", pod=~\"$service_name.*\"},pod)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "JVM Memory",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum(jvm_memory_max_bytes{area=\"heap\", instance=~\"$pod_ip\",kubernetes_name=\"$service_name\",kubernetes_namespace=\"$namespace\"})",
       "legendFormat": "heap limit"
      },
      {
       "expr": "sum(jvm_memory_used_bytes{area=\"heap\", instance=~\"$pod_ip\",kubernetes_name=\"$service_name\",kubernetes_namespace=\"$namespace\"})",
       "legendFormat": "used heap"
      }
     ]
    },
    {
     "title": "Heap Memory",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{instance=~\"$pod_ip\",kubernetes_name=\"$service_name\",kubernetes_namespace=\"$namespace\", area=\"heap\"}",
       "legendFormat": "{{id}}"
      }
     ]
    },
    {
     "title": "Non Heap Memory",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{instance=~\"$pod_ip\",kubernetes_name=\"$service_name\",kubernetes_namespace=\"$namespace\", area=\"nonheap\"}",
       "legendFormat": "{{id}}"
      }
     ]
    },
    {
     "title": "Pod Memory and Swap",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "container_memory_usage_bytes{namespace=~\"$namespace\" , pod=~\"$pod_name\", container=~\"$service_name|service-gateway\"}",
       "legendFormat": "memory {{container}}"
      },
      {
       "expr": "container_memory_swap{namespace=~\"$namespace\" , pod=~\"$pod_name\", container=~\"$service_name|service-gateway\"}",
       "legendFormat": "swap {{container}}"
      }
     ]
    }
   ]
  },
  { "title": "CPU and Threads", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{pod=~\"$pod_name\", image!=\"\",namespace=~\"$namespace\",container=~\"$service_name|service-gateway\"}[$__rate_interval])) by (pod,container)",
     "legendFormat": "cpu usage {{container}}"
    }
   ]
  },
  {
   "title": "Time spent in GC pause",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "rate(jvm_gc_pause_seconds_sum{instance=~\"$pod_ip\",kubernetes_name=\"$service_name\",kubernetes_namespace=\"$namespace\"}[5m])",
     "legendFormat": "{{gc}} - {{action}} - {{cause}}"
    }
   ]
  },
  {
   "title": "JVM Threads State",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "jvm_threads_states_threads{instance=~\"$pod_ip\", kubernetes_name=\"$service_name\", kubernetes_namespace=\"$namespace\"}",
     "legendFormat": "{{state}}"
    }
   ]
  },
  { "title": "HTTP Server", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Requests Per Second",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "round(sum(rate(vertx_http_server_requests_total{kubernetes_namespace=\"$namespace\", kubernetes_name=\"$service_name\", instance=~\"$pod_ip\"}[$__rate_interval])) by (code), 0.001)",
     "legendFormat": "{{code}}"
    },
    {
     "expr": "round(sum(rate(vertx_http_server_requests_total{kubernetes_namespace=\"$namespace\", kubernetes_name=\"$service_name\", instance=~\"$pod_ip\"}[$__rate_interval])), 0.001)",
     "legendFormat": "all"
    }
   ]
  },
  {
   "title": "HTTP Server Active Connections",
   "type": "timeseries",
   "description": "Number of opened connections to the server",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "vertx_http_server_active_connections{instance=~\"$pod_ip\",kubernetes_name=\"$service_name\",kubernetes_namespace=\"$namespace\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "HTTP Server Active Requests",
   "type": "timeseries",
   "description": "Number of requests being processed",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "expr": "sum by (method) (\n  vertx_http_server_active_requests{\n    kubernetes_namespace=\"$namespace\",\n    kubernetes_name=\"$service_name\",\n    instance=~\"$pod_ip\"\n  }\n)",
     "legendFormat": "{{method}}"
    },
    {
     "expr": "sum(\n  vertx_http_server_active_requests{\n    kubernetes_namespace=\"$namespace\",\n    kubernetes_name=\"$service_name\",\n    instance=~\"$pod_ip\"\n  }\n)",
     "legendFormat": "all"
    }
   ]
  },
  { "title": "HTTP Client", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "Net Client Active Connections",
   "type": "timeseries",
   "description": "Number of connections to the remote host currently opened",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "targets": [
    {
     "expr": "vertx_net_client_active_connections{instance=~\"$pod_ip\",kubernetes_name=\"$service_name\",kubernetes_namespace=\"$namespace\"}",
     "legendFormat": "Connections"
    }
   ]
  },
  {
   "title": "HTTP Client Active Requests",
   "type": "timeseries",
   "description": "Number of requests waiting for a response",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "expr": "sum by (method) (\n  vertx_http_client_active_requests{\n    kubernetes_namespace=\"$namespace\",\n    kubernetes_name=\"$service_name\",\n    instance=~\"$pod_ip\"\n  }\n)",
     "legendFormat": "{{method}}"
    },
    {
     "expr": "sum(\n  vertx_http_client_active_requests{\n    kubernetes_namespace=\"$namespace\",\n    kubernetes_name=\"$service_name\",\n    instance=~\"$pod_ip\"\n  }\n)",
     "legendFormat": "all"
    }
   ]
  },
  {
   "title": "Queue Time",
   "type": "timeseries",
   "description": "Time spent in queue before being processed",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max_over_time(\n  vertx_http_client_queue_time_seconds_max{\n    kubernetes_namespace=\"$namespace\",\n    kubernetes_name=\"$service_name\"\n  }[1m]\n)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Event Bus", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 } },
  {
   "title": "EventBus Metrics",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
   "targets": [
    {
     "expr": "vertx_eventbus_handlers{instance=~\"$pod_ip\",kubernetes_name=\"$service_name\",kubernetes_namespace=\"$namespace\"}",
     "legendFormat": "{{instance}} - Handlers"
    },
    {
     "expr": "vertx_eventbus_pending{instance=~\"$pod_ip\",kubernetes_name=\"$service_name\",kubernetes_namespace=\"$namespace\"}",
     "legendFormat": "{{instance}} - Pending"
    },
    {
     "expr": "sum(vertx_eventbus_handlers{instance=~\"$pod_ip\",kubernetes_name=\"$service_name\",kubernetes_namespace=\"$namespace\"})",
     "legendFormat": "All Handlers"
    },
    {
     "expr": "sum(vertx_eventbus_pending{instance=~\"$pod_ip\",kubernetes_name=\"$service_name\",kubernetes_namespace=\"$namespace\"})",
     "legendFormat": "All Pending"
    }
   ]
  },
  {
   "title": "EventBus Sent Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(vertx_eventbus_sent_total{instance=~\"$pod_ip\",kubernetes_name=\"$service_name\",kubernetes_namespace=\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "Sent"
    }
   ]
  },
  {
   "title": "EventBus Receive Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(vertx_eventbus_received_total{instance=~\"$pod_ip\",kubernetes_name=\"$service_name\",kubernetes_namespace=\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "Receive"
    }
   ]
  }
 ]
}