{
 "title": "rwa-iecms",
 "description": "CPU, memory, latency, error rates per service",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(jvm_info,kubernetes_namespace)"
    }
   },
   {
    "name": "nginx_host",
    "query": "{\"find\": \"terms\", \"field\": \"request_host.keyword\"}"
   },
   { "name": "db_server", "query": { "query": "label_values(pg_up,instance)" } },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(elasticsearch_indices_docs,cluster)"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "label_values(elasticsearch_indices_docs{cluster=\"$cluster\", name!=\"\"},instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Errors & Warnings",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "# of 2xx requests",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "select field",
         "hide": false,
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "count"
        }
       ],
       "query": "type:nginx-access AND request_host:\"$nginx_host\" AND status_code:2?? AND source_service_name.keyword:\"\"",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "# of 3xx requests",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "select field",
         "hide": false,
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "count"
        }
       ],
       "query": "type:nginx-access AND request_host:\"$nginx_host\" AND status_code:3?? AND source_service_name.keyword:\"\"",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "# of 4xx requests",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "select field",
         "hide": false,
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "count"
        }
       ],
       "query": "type:nginx-access AND request_host:\"$nginx_host\" AND status_code:4?? AND source_service_name.keyword:\"\"",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "# of 5xx requests",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 9, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "select field",
         "hide": false,
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "count"
        }
       ],
       "query": "type:nginx-access AND request_host:\"$nginx_host\" AND status_code:5?? AND source_service_name.keyword:\"\"",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "# of INFO Logs",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 15, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "select field",
         "hide": false,
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "count"
        }
       ],
       "query": "type:log AND app.environment:\"$namespace\" AND app.loglevel:\"INFO\"",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "# of WARN Logs",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 18, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "select field",
         "hide": false,
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "count"
        }
       ],
       "query": "type:log AND app.environment:\"$namespace\" AND app.loglevel:\"WARN\"",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "# of ERROR Logs",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 21, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "select field",
         "hide": false,
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "count"
        }
       ],
       "query": "type:log AND app.environment:\"$namespace\" AND app.loglevel:\"ERROR\"",
       "timeField": "@timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "Users",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Download Speed",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "Mbits" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.9, sum(ejustice_ecase_users_speed_in_mbps_bucket{kubernetes_namespace=\"production\", app=\"rwa-iecms\", kubernetes_name=\"rwaiecmsui-v1\", type=\"download\"}) by (le)) ",
       "legendFormat": "90% of users under"
      },
      {
       "expr": "histogram_quantile(0.75, sum(ejustice_ecase_users_speed_in_mbps_bucket{kubernetes_namespace=\"production\", app=\"rwa-iecms\", kubernetes_name=\"rwaiecmsui-v1\", type=\"download\"}) by (le)) ",
       "legendFormat": "75% of users under"
      },
      {
       "expr": "histogram_quantile(0.5, sum(ejustice_ecase_users_speed_in_mbps_bucket{kubernetes_namespace=\"production\", app=\"rwa-iecms\", kubernetes_name=\"rwaiecmsui-v1\", type=\"download\"}) by (le)) ",
       "legendFormat": "50% of users under"
      },
      {
       "expr": "histogram_quantile(0.25, sum(ejustice_ecase_users_speed_in_mbps_bucket{kubernetes_namespace=\"production\", app=\"rwa-iecms\", kubernetes_name=\"rwaiecmsui-v1\", type=\"download\"}) by (le)) ",
       "legendFormat": "25% of users under"
      }
     ]
    },
    {
     "title": "Upload Speed",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "Mbits" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.9, sum(ejustice_ecase_users_speed_in_mbps_bucket{kubernetes_namespace=\"production\", app=\"rwa-iecms\", kubernetes_name=\"rwaiecmsui-v1\", type=\"upload\"}) by (le)) ",
       "legendFormat": "90% of users under"
      },
      {
       "expr": "histogram_quantile(0.75, sum(ejustice_ecase_users_speed_in_mbps_bucket{kubernetes_namespace=\"production\", app=\"rwa-iecms\", kubernetes_name=\"rwaiecmsui-v1\", type=\"upload\"}) by (le)) ",
       "legendFormat": "75% of users under"
      },
      {
       "expr": "histogram_quantile(0.5, sum(ejustice_ecase_users_speed_in_mbps_bucket{kubernetes_namespace=\"production\", app=\"rwa-iecms\", kubernetes_name=\"rwaiecmsui-v1\", type=\"upload\"}) by (le)) ",
       "legendFormat": "50% of users under"
      },
      {
       "expr": "histogram_quantile(0.25, sum(ejustice_ecase_users_speed_in_mbps_bucket{kubernetes_namespace=\"production\", app=\"rwa-iecms\", kubernetes_name=\"rwaiecmsui-v1\", type=\"upload\"}) by (le)) ",
       "legendFormat": "25% of users under"
      }
     ]
    },
    {
     "title": "Online Active Users by Head Organization",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 2 },
     "targets": [
      {
       "expr": "sum(ejustice_ecase_online_users{kubernetes_namespace=\"production\", app=\"rwa-iecms\", kubernetes_name=\"rwaiecmsui-v1\"}) by (headOrg)",
       "legendFormat": "{{headOrg}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Page Loading [Admin & Public]",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Slow Network",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.90, sum(rate(ejustice_ecase_loading_duration_in_seconds_bucket{kubernetes_namespace=\"production\", app=\"rwa-iecms\", kubernetes_name=\"rwaiecmsui-v1\", networkSpeed=~\"very-slow|slow\", headOrg=\"-1\", groups=~\"(^|,)-1(,|$)\"}[$__rate_interval])) by (le, headOrg))",
       "legendFormat": "Administrators"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(ejustice_ecase_loading_duration_in_seconds_bucket{kubernetes_namespace=\"production\", app=\"rwa-iecms\", kubernetes_name=\"rwaiecmsui-v1\", networkSpeed=~\"very-slow|slow\", headOrg=\"-1\", groups=~\"(^|,)-2(,|$)\"}[$__rate_interval])) by (le, headOrg))",
       "legendFormat": "Public"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(ejustice_ecase_loading_duration_in_seconds_bucket{kubernetes_namespace=\"production\", app=\"rwa-iecms\", kubernetes_name=\"rwaiecmsui-v1\", networkSpeed=~\"very-slow|slow\", headOrg=\"-1\", groups=~\"(^|,)1000222(,|$)\"}[$__rate_interval])) by (le, headOrg))",
       "legendFormat": "Bidders"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(ejustice_ecase_loading_duration_in_seconds_bucket{kubernetes_namespace=\"production\", app=\"rwa-iecms\", kubernetes_name=\"rwaiecmsui-v1\", networkSpeed=~\"very-slow|slow\", headOrg=\"-1\", groups=~\"(^|,)-3(,|$)\"}[$__rate_interval])) by (le, headOrg))",
       "legendFormat": "Guests"
      }
     ]
    },
    {
     "title": "Normal Network",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.90, sum(rate(ejustice_ecase_loading_duration_in_seconds_bucket{kubernetes_namespace=\"production\", app=\"rwa-iecms\", kubernetes_name=\"rwaiecmsui-v1\", networkSpeed=~\"normal\", headOrg=\"-1\", groups=~\"(^|,)-1(,|$)\"}[$__rate_interval])) by (le, headOrg))",
       "legendFormat": "Administrators"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(ejustice_ecase_loading_duration_in_seconds_bucket{kubernetes_namespace=\"production\", app=\"rwa-iecms\", kubernetes_name=\"rwaiecmsui-v1\", networkSpeed=~\"normal\", headOrg=\"-1\", groups=~\"(^|,)-2(,|$)\"}[$__rate_interval])) by (le, headOrg))",
       "legendFormat": "Public"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(ejustice_ecase_loading_duration_in_seconds_bucket{kubernetes_namespace=\"production\", app=\"rwa-iecms\", kubernetes_name=\"rwaiecmsui-v1\", networkSpeed=~\"normal\", headOrg=\"-1\", groups=~\"(^|,)1000222(,|$)\"}[$__rate_interval])) by (le, headOrg))",
       "legendFormat": "Bidders"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(ejustice_ecase_loading_duration_in_seconds_bucket{kubernetes_namespace=\"production\", app=\"rwa-iecms\", kubernetes_name=\"rwaiecmsui-v1\", networkSpeed=~\"normal\", headOrg=\"-1\", groups=~\"(^|,)-3(,|$)\"}[$__rate_interval])) by (le, headOrg))",
       "legendFormat": "Guests"
      }
     ]
    },
    {
     "title": "Fast Network",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.90, sum(rate(ejustice_ecase_loading_duration_in_seconds_bucket{kubernetes_namespace=\"production\", app=\"rwa-iecms\", kubernetes_name=\"rwaiecmsui-v1\", networkSpeed=~\"very-fast|fast\", headOrg=\"-1\", groups=~\"(^|,)-1(,|$)\"}[$__rate_interval])) by (le, headOrg))",
       "legendFormat": "Administrators"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(ejustice_ecase_loading_duration_in_seconds_bucket{kubernetes_namespace=\"production\", app=\"rwa-iecms\", kubernetes_name=\"rwaiecmsui-v1\", networkSpeed=~\"very-fast|fast\", headOrg=\"-1\", groups=~\"(^|,)-2(,|$)\"}[$__rate_interval])) by (le, headOrg))",
       "legendFormat": "Public"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(ejustice_ecase_loading_duration_in_seconds_bucket{kubernetes_namespace=\"production\", app=\"rwa-iecms\", kubernetes_name=\"rwaiecmsui-v1\", networkSpeed=~\"very-fast|fast\", headOrg=\"-1\", groups=~\"(^|,)1000222(,|$)\"}[$__rate_interval])) by (le, headOrg))",
       "legendFormat": "Bidders"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(ejustice_ecase_loading_duration_in_seconds_bucket{kubernetes_namespace=\"production\", app=\"rwa-iecms\", kubernetes_name=\"rwaiecmsui-v1\", networkSpeed=~\"very-fast|fast\", headOrg=\"-1\", groups=~\"(^|,)-3(,|$)\"}[$__rate_interval])) by (le, headOrg))",
       "legendFormat": "Guests"
      }
     ]
    }
   ]
  },
  {
   "title": "Page Loading [Staff]",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Slow Network",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.90, sum(rate(ejustice_ecase_loading_duration_in_seconds_bucket{kubernetes_namespace=\"production\", app=\"rwa-iecms\", kubernetes_name=\"rwaiecmsui-v1\", networkSpeed=~\"very-slow|slow\", headOrg=\"14\", groups=~\"(^|,)2(,|$)\"}[$__rate_interval])) by (le, headOrg))",
       "legendFormat": "Investigating Officer"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(ejustice_ecase_loading_duration_in_seconds_bucket{kubernetes_namespace=\"production\", app=\"rwa-iecms\", kubernetes_name=\"rwaiecmsui-v1\", networkSpeed=~\"very-slow|slow\", headOrg=\"15\", groups=~\"(^|,)7(,|$)\"}[$__rate_interval])) by (le, headOrg))",
       "legendFormat": "Chief Prosecutor"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(ejustice_ecase_loading_duration_in_seconds_bucket{kubernetes_namespace=\"production\", app=\"rwa-iecms\", kubernetes_name=\"rwaiecmsui-v1\", networkSpeed=~\"very-slow|slow\", headOrg=\"15\", groups=~\"(^|,)8(,|$)\"}[$__rate_interval])) by (le, headOrg))",
       "legendFormat": "Prosecutor"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(ejustice_ecase_loading_duration_in_seconds_bucket{kubernetes_namespace=\"production\", app=\"rwa-iecms\", kubernetes_name=\"rwaiecmsui-v1\", networkSpeed=~\"very-slow|slow\", headOrg=\"16\", groups=~\"(^|,)16(,|$)\"}[$__rate_interval])) by (le, headOrg))",
       "legendFormat": "Judge"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(ejustice_ecase_loading_duration_in_seconds_bucket{kubernetes_namespace=\"production\", app=\"rwa-iecms\", kubernetes_name=\"rwaiecmsui-v1\", networkSpeed=~\"very-slow|slow\", headOrg=\"16\", groups=~\"(^|,)17(,|$)\"}[$__rate_interval])) by (le, headOrg))",
       "legendFormat": "Registrar"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(ejustice_ecase_loading_duration_in_seconds_bucket{kubernetes_namespace=\"production\", app=\"rwa-iecms\", kubernetes_name=\"rwaiecmsui-v1\", networkSpeed=~\"very-slow|slow\", headOrg=\"16\", groups=~\"(^|,)21(,|$)\"}[$__rate_interval])) by (le, headOrg))",
       "legendFormat": "Chief Registrar"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(ejustice_ecase_loading_duration_in_seconds_bucket{kubernetes_namespace=\"production\", app=\"rwa-iecms\", kubernetes_name=\"rwaiecmsui-v1\", networkSpeed=~\"very-slow|slow\", headOrg=\"17\", groups=~\"(^|,)40(,|$)\"}[$__rate_interval])) by (le, headOrg))",
       "legendFormat": "RCS Registrar Officer"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(ejustice_ecase_loading_duration_in_seconds_bucket{kubernetes_namespace=\"production\", app=\"rwa-iecms\", kubernetes_name=\"rwaiecmsui-v1\", networkSpeed=~\"very-slow|slow\", headOrg=\"17\", groups=~\"(^|,)41(,|$)\"}[$__rate_interval])) by (le, headOrg))",
       "legendFormat": "RCS Legal Officer"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(ejustice_ecase_loading_duration_in_seconds_bucket{kubernetes_namespace=\"production\", app=\"rwa-iecms\", kubernetes_name=\"rwaiecmsui-v1\", networkSpeed=~\"very-slow|slow\", headOrg=\"14\", groups=~\"(^|,)49(,|$)\"}[$__rate_interval])) by (le, headOrg))",
       "legendFormat": "Head Investigating Office"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(ejustice_ecase_loading_duration_in_seconds_bucket{kubernetes_namespace=\"production\", app=\"rwa-iecms\", kubernetes_name=\"rwaiecmsui-v1\", networkSpeed=~\"very-slow|slow\", headOrg=\"14\", groups=~\"(^|,)1000281(,|$)\"}[$__rate_interval])) by (le, headOrg))",
       "legendFormat": "Police Investigator"
      }
     ]
    },
    {
     "title": "Normal Network",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.90, sum(rate(ejustice_ecase_loading_duration_in_seconds_bucket{kubernetes_namespace=\"production\", app=\"rwa-iecms\", kubernetes_name=\"rwaiecmsui-v1\", networkSpeed=~\"normal\", headOrg=\"14\", groups=~\"(^|,)2(,|$)\"}[$__rate_interval])) by (le, headOrg))",
       "legendFormat": "Investigating Officer"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(ejustice_ecase_loading_duration_in_seconds_bucket{kubernetes_namespace=\"production\", app=\"rwa-iecms\", kubernetes_name=\"rwaiecmsui-v1\", networkSpeed=~\"normal\", headOrg=\"15\", groups=~\"(^|,)7(,|$)\"}[$__rate_interval])) by (le, headOrg))",
       "legendFormat": "Chief Prosecutor"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(ejustice_ecase_loading_duration_in_seconds_bucket{kubernetes_namespace=\"production\", app=\"rwa-iecms\", kubernetes_name=\"rwaiecmsui-v1\", networkSpeed=~\"normal\", headOrg=\"15\", groups=~\"(^|,)8(,|$)\"}[$__rate_interval])) by (le, headOrg))",
       "legendFormat": "Prosecutor"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(ejustice_ecase_loading_duration_in_seconds_bucket{kubernetes_namespace=\"production\", app=\"rwa-iecms\", kubernetes_name=\"rwaiecmsui-v1\", networkSpeed=~\"normal\", headOrg=\"16\", groups=~\"(^|,)16(,|$)\"}[$__rate_interval])) by (le, headOrg))",
       "legendFormat": "Judge"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(ejustice_ecase_loading_duration_in_seconds_bucket{kubernetes_namespace=\"production\", app=\"rwa-iecms\", kubernetes_name=\"rwaiecmsui-v1\", networkSpeed=~\"normal\", headOrg=\"16\", groups=~\"(^|,)17(,|$)\"}[$__rate_interval])) by (le, headOrg))",
       "legendFormat": "Registrar"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(ejustice_ecase_loading_duration_in_seconds_bucket{kubernetes_namespace=\"production\", app=\"rwa-iecms\", kubernetes_name=\"rwaiecmsui-v1\", networkSpeed=~\"normal\", headOrg=\"16\", groups=~\"(^|,)21(,|$)\"}[$__rate_interval])) by (le, headOrg))",
       "legendFormat": "Chief Registrar"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(ejustice_ecase_loading_duration_in_seconds_bucket{kubernetes_namespace=\"production\", app=\"rwa-iecms\", kubernetes_name=\"rwaiecmsui-v1\", networkSpeed=~\"normal\", headOrg=\"17\", groups=~\"(^|,)40(,|$)\"}[$__rate_interval])) by (le, headOrg))",
       "legendFormat": "RCS Registrar Officer"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(ejustice_ecase_loading_duration_in_seconds_bucket{kubernetes_namespace=\"production\", app=\"rwa-iecms\", kubernetes_name=\"rwaiecmsui-v1\", networkSpeed=~\"normal\", headOrg=\"17\", groups=~\"(^|,)41(,|$)\"}[$__rate_interval])) by (le, headOrg))",
       "legendFormat": "RCS Legal Officer"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(ejustice_ecase_loading_duration_in_seconds_bucket{kubernetes_namespace=\"production\", app=\"rwa-iecms\", kubernetes_name=\"rwaiecmsui-v1\", networkSpeed=~\"normal\", headOrg=\"14\", groups=~\"(^|,)49(,|$)\"}[$__rate_interval])) by (le, headOrg))",
       "legendFormat": "Head Investigating Office"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(ejustice_ecase_loading_duration_in_seconds_bucket{kubernetes_namespace=\"production\", app=\"rwa-iecms\", kubernetes_name=\"rwaiecmsui-v1\", networkSpeed=~\"normal\", headOrg=\"14\", groups=~\"(^|,)1000281(,|$)\"}[$__rate_interval])) by (le, headOrg))",
       "legendFormat": "Police Investigator"
      }
     ]
    },
    {
     "title": "Fast Network",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.90, sum(rate(ejustice_ecase_loading_duration_in_seconds_bucket{kubernetes_namespace=\"production\", app=\"rwa-iecms\", kubernetes_name=\"rwaiecmsui-v1\", networkSpeed=~\"very-fast|fast\", headOrg=\"14\", groups=~\"(^|,)2(,|$)\"}[$__rate_interval])) by (le, headOrg))",
       "legendFormat": "Investigating Officer"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(ejustice_ecase_loading_duration_in_seconds_bucket{kubernetes_namespace=\"production\", app=\"rwa-iecms\", kubernetes_name=\"rwaiecmsui-v1\", networkSpeed=~\"very-fast|fast\", headOrg=\"15\", groups=~\"(^|,)7(,|$)\"}[$__rate_interval])) by (le, headOrg))",
       "legendFormat": "Chief Prosecutor"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(ejustice_ecase_loading_duration_in_seconds_bucket{kubernetes_namespace=\"production\", app=\"rwa-iecms\", kubernetes_name=\"rwaiecmsui-v1\", networkSpeed=~\"very-fast|fast\", headOrg=\"15\", groups=~\"(^|,)8(,|$)\"}[$__rate_interval])) by (le, headOrg))",
       "legendFormat": "Prosecutor"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(ejustice_ecase_loading_duration_in_seconds_bucket{kubernetes_namespace=\"production\", app=\"rwa-iecms\", kubernetes_name=\"rwaiecmsui-v1\", networkSpeed=~\"very-fast|fast\", headOrg=\"16\", groups=~\"(^|,)16(,|$)\"}[$__rate_interval])) by (le, headOrg))",
       "legendFormat": "Judge"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(ejustice_ecase_loading_duration_in_seconds_bucket{kubernetes_namespace=\"production\", app=\"rwa-iecms\", kubernetes_name=\"rwaiecmsui-v1\", networkSpeed=~\"very-fast|fast\", headOrg=\"16\", groups=~\"(^|,)17(,|$)\"}[$__rate_interval])) by (le, headOrg))",
       "legendFormat": "Registrar"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(ejustice_ecase_loading_duration_in_seconds_bucket{kubernetes_namespace=\"production\", app=\"rwa-iecms\", kubernetes_name=\"rwaiecmsui-v1\", networkSpeed=~\"very-fast|fast\", headOrg=\"16\", groups=~\"(^|,)21(,|$)\"}[$__rate_interval])) by (le, headOrg))",
       "legendFormat": "Chief Registrar"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(ejustice_ecase_loading_duration_in_seconds_bucket{kubernetes_namespace=\"production\", app=\"rwa-iecms\", kubernetes_name=\"rwaiecmsui-v1\", networkSpeed=~\"very-fast|fast\", headOrg=\"17\", groups=~\"(^|,)40(,|$)\"}[$__rate_interval])) by (le, headOrg))",
       "legendFormat": "RCS Registrar Officer"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(ejustice_ecase_loading_duration_in_seconds_bucket{kubernetes_namespace=\"production\", app=\"rwa-iecms\", kubernetes_name=\"rwaiecmsui-v1\", networkSpeed=~\"very-fast|fast\", headOrg=\"17\", groups=~\"(^|,)41(,|$)\"}[$__rate_interval])) by (le, headOrg))",
       "legendFormat": "RCS Legal Officer"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(ejustice_ecase_loading_duration_in_seconds_bucket{kubernetes_namespace=\"production\", app=\"rwa-iecms\", kubernetes_name=\"rwaiecmsui-v1\", networkSpeed=~\"very-fast|fast\", headOrg=\"14\", groups=~\"(^|,)49(,|$)\"}[$__rate_interval])) by (le, headOrg))",
       "legendFormat": "Head Investigating Office"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(ejustice_ecase_loading_duration_in_seconds_bucket{kubernetes_namespace=\"production\", app=\"rwa-iecms\", kubernetes_name=\"rwaiecmsui-v1\", networkSpeed=~\"very-fast|fast\", headOrg=\"14\", groups=~\"(^|,)1000281(,|$)\"}[$__rate_interval])) by (le, headOrg))",
       "legendFormat": "Police Investigator"
      }
     ]
    }
   ]
  },
  {
   "title": "Page Loading [Military Staff]",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Slow Network",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.90, sum(rate(ejustice_ecase_loading_duration_in_seconds_bucket{kubernetes_namespace=\"production\", app=\"rwa-iecms\", kubernetes_name=\"rwaiecmsui-v1\", networkSpeed=~\"very-slow|slow\", headOrg=\"14\", groups=~\"(^|,)116(,|$)\"}[$__rate_interval])) by (le, headOrg))",
       "legendFormat": "Military Investigator"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(ejustice_ecase_loading_duration_in_seconds_bucket{kubernetes_namespace=\"production\", app=\"rwa-iecms\", kubernetes_name=\"rwaiecmsui-v1\", networkSpeed=~\"very-slow|slow\", headOrg=\"15\", groups=~\"(^|,)1000231(,|$)\"}[$__rate_interval])) by (le, headOrg))",
       "legendFormat": "Military Prosecutor"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(ejustice_ecase_loading_duration_in_seconds_bucket{kubernetes_namespace=\"production\", app=\"rwa-iecms\", kubernetes_name=\"rwaiecmsui-v1\", networkSpeed=~\"very-slow|slow\", headOrg=\"16\", groups=~\"(^|,)1000236(,|$)\"}[$__rate_interval])) by (le, headOrg))",
       "legendFormat": "Military Registrar"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(ejustice_ecase_loading_duration_in_seconds_bucket{kubernetes_namespace=\"production\", app=\"rwa-iecms\", kubernetes_name=\"rwaiecmsui-v1\", networkSpeed=~\"very-slow|slow\", headOrg=\"16\", groups=~\"(^|,)1000235(,|$)\"}[$__rate_interval])) by (le, headOrg))",
       "legendFormat": "Military Judge"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(ejustice_ecase_loading_duration_in_seconds_bucket{kubernetes_namespace=\"production\", app=\"rwa-iecms\", kubernetes_name=\"rwaiecmsui-v1\", networkSpeed=~\"very-slow|slow\", headOrg=\"17\", groups=~\"(^|,)1000240(,|$)\"}[$__rate_interval])) by (le, headOrg))",
       "legendFormat": "Military Prison Registrar Officer"
      }
     ]
    },
    {
     "title": "Normal Network",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.90, sum(rate(ejustice_ecase_loading_duration_in_seconds_bucket{kubernetes_namespace=\"production\", app=\"rwa-iecms\", kubernetes_name=\"rwaiecmsui-v1\", networkSpeed=~\"normal\", headOrg=\"14\", groups=~\"(^|,)116(,|$)\"}[$__rate_interval])) by (le, headOrg))",
       "legendFormat": "Military Investigator"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(ejustice_ecase_loading_duration_in_seconds_bucket{kubernetes_namespace=\"production\", app=\"rwa-iecms\", kubernetes_name=\"rwaiecmsui-v1\", networkSpeed=~\"normal\", headOrg=\"15\", groups=~\"(^|,)1000231(,|$)\"}[$__rate_interval])) by (le, headOrg))",
       "legendFormat": "Military Prosecutor"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(ejustice_ecase_loading_duration_in_seconds_bucket{kubernetes_namespace=\"production\", app=\"rwa-iecms\", kubernetes_name=\"rwaiecmsui-v1\", networkSpeed=~\"normal\", headOrg=\"16\", groups=~\"(^|,)1000236(,|$)\"}[$__rate_interval])) by (le, headOrg))",
       "legendFormat": "Military Registrar"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(ejustice_ecase_loading_duration_in_seconds_bucket{kubernetes_namespace=\"production\", app=\"rwa-iecms\", kubernetes_name=\"rwaiecmsui-v1\", networkSpeed=~\"normal\", headOrg=\"16\", groups=~\"(^|,)1000235(,|$)\"}[$__rate_interval])) by (le, headOrg))",
       "legendFormat": "Military Judge"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(ejustice_ecase_loading_duration_in_seconds_bucket{kubernetes_namespace=\"production\", app=\"rwa-iecms\", kubernetes_name=\"rwaiecmsui-v1\", networkSpeed=~\"normal\", headOrg=\"17\", groups=~\"(^|,)1000240(,|$)\"}[$__rate_interval])) by (le, headOrg))",
       "legendFormat": "Military Prison Registrar Officer"
      }
     ]
    },
    {
     "title": "Fast Network",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.90, sum(rate(ejustice_ecase_loading_duration_in_seconds_bucket{kubernetes_namespace=\"production\", app=\"rwa-iecms\", kubernetes_name=\"rwaiecmsui-v1\", networkSpeed=~\"very-fast|fast\", headOrg=\"14\", groups=~\"(^|,)116(,|$)\"}[$__rate_interval])) by (le, headOrg))",
       "legendFormat": "Military Investigator"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(ejustice_ecase_loading_duration_in_seconds_bucket{kubernetes_namespace=\"production\", app=\"rwa-iecms\", kubernetes_name=\"rwaiecmsui-v1\", networkSpeed=~\"very-fast|fast\", headOrg=\"15\", groups=~\"(^|,)1000231(,|$)\"}[$__rate_interval])) by (le, headOrg))",
       "legendFormat": "Military Prosecutor"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(ejustice_ecase_loading_duration_in_seconds_bucket{kubernetes_namespace=\"production\", app=\"rwa-iecms\", kubernetes_name=\"rwaiecmsui-v1\", networkSpeed=~\"very-fast|fast\", headOrg=\"16\", groups=~\"(^|,)1000236(,|$)\"}[$__rate_interval])) by (le, headOrg))",
       "legendFormat": "Military Registrar"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(ejustice_ecase_loading_duration_in_seconds_bucket{kubernetes_namespace=\"production\", app=\"rwa-iecms\", kubernetes_name=\"rwaiecmsui-v1\", networkSpeed=~\"very-fast|fast\", headOrg=\"16\", groups=~\"(^|,)1000235(,|$)\"}[$__rate_interval])) by (le, headOrg))",
       "legendFormat": "Military Judge"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(ejustice_ecase_loading_duration_in_seconds_bucket{kubernetes_namespace=\"production\", app=\"rwa-iecms\", kubernetes_name=\"rwaiecmsui-v1\", networkSpeed=~\"very-fast|fast\", headOrg=\"17\", groups=~\"(^|,)1000240(,|$)\"}[$__rate_interval])) by (le, headOrg))",
       "legendFormat": "Military Prison Registrar Officer"
      }
     ]
    }
   ]
  },
  {
   "title": "HTTP",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Request Per $__interval",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "alias": "rps",
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "expr": "type:nginx-access  AND  request_host:\"$namespace.synisys.com\" AND nginx.service.name:$service",
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "type.keyword:nginx-access AND request_host.keyword:\"$nginx_host\" AND source_service_name.keyword:\"\"",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Response time",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "expr": "type:nginx-access  AND  request_host:\"$namespace.synisys.com\" AND nginx.service.name:$service",
       "metrics": [
        {
         "field": "request_time",
         "hide": false,
         "id": "1",
         "meta": {},
         "settings": { "percents": [ "95" ] },
         "type": "percentiles"
        }
       ],
       "query": "type:nginx-access AND request_host:\"$nginx_host\" ",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Error Rate",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "alias": "Total",
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "type.keyword:nginx-access AND request_host.keyword:\"$nginx_host\" AND status_code.keyword:[100 TO 599] AND source_service_name.keyword:\"\"",
       "timeField": "@timestamp"
      },
      {
       "alias": "Error",
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "type.keyword:nginx-access AND request_host.keyword:\"$nginx_host\" AND status_code.keyword:[500 TO 599] AND source_service_name.keyword:\"\"",
       "timeField": "@timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "HTTP Latency by Service",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Request Per $__interval",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "alias": "{{nginx.service.name.keyword}}",
       "bucketAggs": [
        {
         "field": "nginx.service.name.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "10" },
         "type": "terms"
        },
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "expr": "type:nginx-access  AND  request_host:\"$namespace.synisys.com\" AND nginx.service.name:$service",
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "type.keyword:nginx-access AND request_host.keyword:\"$nginx_host\" AND source_service_name.keyword:\"\" AND NOT nginx.service.name.keyword:authservice",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Request Per $__interval",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "alias": "{{nginx.service.name.keyword}}",
       "bucketAggs": [
        {
         "field": "nginx.service.name.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "10" },
         "type": "terms"
        },
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "expr": "type:nginx-access  AND  request_host:\"$namespace.synisys.com\" AND nginx.service.name:$service",
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "type.keyword:nginx-access AND request_host.keyword:\"$nginx_host\" AND (\nnginx.service.name.keyword: reportingservice OR\nnginx.service.name.keyword: reportexportservice OR\nnginx.service.name.keyword: notificationservice OR\nnginx.service.name.keyword: auditservice OR\nnginx.service.name.keyword: ejusticedocumentservice OR\nnginx.service.name.keyword: exportservice OR\nnginx.service.name.keyword: exportzipservice OR\nnginx.service.name.keyword: documentservice)\nAND source_service_name.keyword:\"\"",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Request's Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 54 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "bucketAggs": [
        {
         "fake": true,
         "field": "nginx.service.name.keyword",
         "id": "4",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1[95.0]", "size": "15" },
         "type": "terms"
        },
        { "field": "@timestamp", "id": "2", "settings": { "interval": "1h", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "expr": "type:nginx-access  AND  request_host:\"$namespace.synisys.com\" AND nginx.service.name:\"$kibana_service\"",
       "metrics": [
        {
         "field": "request_time",
         "id": "1",
         "meta": {},
         "settings": { "percents": [ "95" ] },
         "type": "percentiles"
        }
       ],
       "query": "type.keyword:nginx-access AND request_host.keyword:\"$nginx_host\" AND NOT (\nnginx.service.name.keyword: clientnotifierservice OR\nnginx.service.name.keyword: reportingservice OR\nnginx.service.name.keyword: reportexportservice OR\nnginx.service.name.keyword: notificationservice OR\nnginx.service.name.keyword: auditservice OR\nnginx.service.name.keyword: ejusticedocumentservice OR\nnginx.service.name.keyword: exportservice OR\nnginx.service.name.keyword: exportzipservice OR\nnginx.service.name.keyword: documentservice OR\nnginx.service.name.keyword: authservice) \nAND source_service_name.keyword:\"\"",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Request's Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 54 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "bucketAggs": [
        {
         "fake": true,
         "field": "nginx.service.name.keyword",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1[95.0]", "size": "20" },
         "type": "terms"
        },
        { "field": "@timestamp", "id": "2", "settings": { "interval": "1h", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "expr": "type:nginx-access  AND  request_host:\"$namespace.synisys.com\" AND nginx.service.name:\"$kibana_service\"",
       "metrics": [
        {
         "field": "request_time",
         "id": "1",
         "meta": {},
         "settings": { "percents": [ "95" ] },
         "type": "percentiles"
        }
       ],
       "query": "type.keyword:nginx-access AND request_host.keyword:\"$nginx_host\" AND (\nnginx.service.name.keyword: reportingservice OR\nnginx.service.name.keyword: reportexportservice OR\nnginx.service.name.keyword: notificationservice OR\nnginx.service.name.keyword: auditservice OR\nnginx.service.name.keyword: ejusticedocumentservice OR\nnginx.service.name.keyword: exportservice OR\nnginx.service.name.keyword: exportzipservice OR\nnginx.service.name.keyword: documentservice)\nAND source_service_name.keyword:\"\"",
       "timeField": "@timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "Resource Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "CPU Average Usage %",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "avg(rate(process_cpu_seconds_total[$__rate_interval]))*100",
       "legendFormat": "CPU Usage (%)"
      }
     ]
    },
    {
     "title": "Memory Average Usage %",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "avg(node_memory_Active_bytes / node_memory_MemTotal_bytes) * 100",
       "legendFormat": "Memory Usage (%)"
      }
     ]
    },
    {
     "title": "Bandwidth Usage",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "(sum(rate(node_network_receive_bytes_total[$__rate_interval])))",
       "legendFormat": "Data Received"
      },
      {
       "expr": "(sum(rate(node_network_transmit_bytes_total[1m])))",
       "legendFormat": "Data Sent"
      }
     ]
    }
   ]
  },
  {
   "title": "Database",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "PostgreSQL Connections per Instance",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 48 },
     "targets": [
      {
       "expr": "sum(dbmon_pg_user_connection_count) by (instance)",
       "legendFormat": "{{server}}"
      }
     ]
    },
    {
     "title": "Total Query Executions per DB Server",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(pg_query_execution_count{instance=~\"$db_server\"}) by (instance)",
       "legendFormat": "{{db_server}}"
      }
     ]
    },
    {
     "title": "Slowest 1% of PG Queries (>200ms) – Service Users",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "pg_query_execution_time_99{instance=~\"$db_server\", user_name=~\".*service.*\"} > 200",
       "legendFormat": "99th {{db_server}} {{db_name}} {{user_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "RabbitMQ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Queued Messages",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 49 },
     "targets": [
      {
       "expr": "sum(rabbitmq_queue_messages{kubernetes_namespace=\"$namespace\", queue!=\"messaging-upgraded-services\", queue!~\".*[-]gateway[-].*\"})",
       "legendFormat": "# of messages"
      }
     ]
    },
    {
     "title": "Messages Publish/Deliver Rates",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 49 },
     "targets": [
      {
       "expr": "sum(rabbitmq_queue_messages_publish_rate{kubernetes_namespace=\"$namespace\"})",
       "legendFormat": "publish rate"
      },
      {
       "expr": "-sum(rabbitmq_queue_messages_deliver_rate{kubernetes_namespace=\"$namespace\"})",
       "legendFormat": "deliver rate"
      }
     ]
    }
   ]
  },
  {
   "title": "ElasticSearch",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Total Operations  rate",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(elasticsearch_indices_indexing_index_total{instance=~\"$instance\",cluster=\"$cluster\"}[$__rate_interval])",
       "legendFormat": "{{name}}: indexing"
      },
      {
       "expr": "rate(elasticsearch_indices_search_query_total{instance=~\"$instance\",cluster=\"$cluster\"}[$__rate_interval])",
       "legendFormat": "{{name}}: query"
      },
      {
       "expr": "rate(elasticsearch_indices_search_fetch_total{instance=~\"$instance\",cluster=\"$cluster\"}[$__rate_interval])",
       "legendFormat": "{{name}}: fetch"
      },
      {
       "expr": "rate(elasticsearch_indices_merges_total{instance=~\"$instance\",cluster=\"$cluster\"}[$__rate_interval])",
       "legendFormat": "{{name}}: merges"
      },
      {
       "expr": "rate(elasticsearch_indices_refresh_total{instance=~\"$instance\",cluster=\"$cluster\"}[$__rate_interval])",
       "legendFormat": "{{name}}: refresh"
      },
      {
       "expr": "rate(elasticsearch_indices_flush_total{instance=~\"$instance\",cluster=\"$cluster\"}[$__rate_interval])",
       "legendFormat": "{{name}}: flush"
      },
      {
       "expr": "rate(elasticsearch_indices_get_exists_total{instance=~\"$instance\",cluster=\"$cluster\"}[$__rate_interval])",
       "legendFormat": "{{name}}: get_exists"
      },
      {
       "expr": "rate(elasticsearch_indices_get_missing_total{instance=~\"$instance\",cluster=\"$cluster\"}[$__rate_interval])",
       "legendFormat": "{{name}}: get_missing"
      },
      {
       "expr": "rate(elasticsearch_indices_get_tota{instance=~\"$instance\",cluster=\"$cluster\"}[$__rate_interval])",
       "legendFormat": "{{name}}: get"
      },
      {
       "expr": "rate(elasticsearch_indices_indexing_delete_total{instance=~\"$instance\",cluster=\"$cluster\"}[$__rate_interval])",
       "legendFormat": "{{name}}: indexing_delete"
      }
     ]
    },
    {
     "title": "Total Operations time",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "irate(elasticsearch_indices_indexing_index_time_seconds_total{instance=~\"$instance\",cluster=\"$cluster\"}[$__rate_interval])",
       "legendFormat": "{{name}}: indexing"
      },
      {
       "expr": "irate(elasticsearch_indices_search_query_time_seconds{instance=~\"$instance\",cluster=\"$cluster\"}[$__rate_interval])",
       "legendFormat": "{{name}}: query"
      },
      {
       "expr": "irate(elasticsearch_indices_search_fetch_time_seconds{instance=~\"$instance\",cluster=\"$cluster\"}[$__rate_interval])",
       "legendFormat": "{{name}}: fetch"
      },
      {
       "expr": "irate(elasticsearch_indices_merges_total_time_seconds_total{instance=~\"$instance\",cluster=\"$cluster\"}[$__rate_interval])",
       "legendFormat": "{{name}}: merges"
      },
      {
       "expr": "irate(elasticsearch_indices_refresh_time_seconds_total{instance=~\"$instance\",cluster=\"$cluster\"}[$__rate_interval])",
       "legendFormat": "{{name}}: refresh"
      },
      {
       "expr": "irate(elasticsearch_indices_flush_time_seconds{instance=~\"$instance\",cluster=\"$cluster\"}[$__rate_interval])",
       "legendFormat": "{{name}}: flush"
      },
      {
       "expr": "irate(elasticsearch_indices_get_exists_time_seconds{instance=~\"$instance\",cluster=\"$cluster\"}[$__rate_interval])",
       "legendFormat": "{{name}}: get_exists"
      },
      {
       "expr": "irate(elasticsearch_indices_get_time_seconds{instance=~\"$instance\",cluster=\"$cluster\"}[$__rate_interval])",
       "legendFormat": "{{name}}: get_time"
      },
      {
       "expr": "irate(elasticsearch_indices_get_missing_time_seconds{instance=~\"$instance\",cluster=\"$cluster\"}[$__rate_interval])",
       "legendFormat": "{{name}}: get_missing"
      },
      {
       "expr": "irate(elasticsearch_indices_indexing_delete_time_seconds_total{instance=~\"$instance\",cluster=\"$cluster\"}[$__rate_interval])",
       "legendFormat": "{{name}}: indexing_delete"
      },
      {
       "expr": "irate(elasticsearch_indices_get_time_seconds{instance=~\"$instance\",cluster=\"$cluster\"}[$__rate_interval])",
       "legendFormat": "{{name}}: get"
      }
     ]
    }
   ]
  },
  {
   "title": "Auctions Pages Loading",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Active Auction",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.90, sum(rate(ejustice_ecase_loading_duration_in_seconds_bucket{kubernetes_namespace=\"production\", app=\"rwa-iecms\", kubernetes_name=\"rwaiecmsui-v1\", location=\"/auction\"}[$__rate_interval])) by (le, networkSpeed))",
       "legendFormat": "{{headOrg}}"
      }
     ]
    },
    {
     "title": "Scheduled Auctions",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.90, sum(rate(ejustice_ecase_loading_duration_in_seconds_bucket{kubernetes_namespace=\"production\", app=\"rwa-iecms\", kubernetes_name=\"rwaiecmsui-v1\", location=\"/pages/435\"}[$__rate_interval])) by (le, networkSpeed))",
       "legendFormat": "{{headOrg}}"
      }
     ]
    },
    {
     "title": "All Bids",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.90, sum(rate(ejustice_ecase_loading_duration_in_seconds_bucket{kubernetes_namespace=\"production\", app=\"rwa-iecms\", kubernetes_name=\"rwaiecmsui-v1\", location=\"/workspace/all-auction-bids/ExecutionCaseAuction\"}[$__rate_interval])) by (le, networkSpeed))",
       "legendFormat": "{{headOrg}}"
      }
     ]
    },
    {
     "title": "Active Bids",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.90, sum(rate(ejustice_ecase_loading_duration_in_seconds_bucket{kubernetes_namespace=\"production\", app=\"rwa-iecms\", kubernetes_name=\"rwaiecmsui-v1\", location=\"/workspace/active-auction-bids/ExecutionCaseAuction\"}[$__rate_interval])) by (le, networkSpeed))",
       "legendFormat": "{{headOrg}}"
      }
     ]
    },
    {
     "title": "My Refundable Bids",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.90, sum(rate(ejustice_ecase_loading_duration_in_seconds_bucket{kubernetes_namespace=\"production\", app=\"rwa-iecms\", kubernetes_name=\"rwaiecmsui-v1\", location=\"/workspace/my-refundable-bids/ExecutionCasePartyAuctionBid\"}[$__rate_interval])) by (le, networkSpeed))",
       "legendFormat": "{{headOrg}}"
      }
     ]
    },
    {
     "title": "Completed Auctions",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.90, sum(rate(ejustice_ecase_loading_duration_in_seconds_bucket{kubernetes_namespace=\"production\", app=\"rwa-iecms\", kubernetes_name=\"rwaiecmsui-v1\", location=\"/pages/437\"}[$__rate_interval])) by (le, networkSpeed))",
       "legendFormat": "{{headOrg}}"
      }
     ]
    },
    {
     "title": "Adjourned Auctions",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.90, sum(rate(ejustice_ecase_loading_duration_in_seconds_bucket{kubernetes_namespace=\"production\", app=\"rwa-iecms\", kubernetes_name=\"rwaiecmsui-v1\", location=\"/pages/436\"}[$__rate_interval])) by (le, networkSpeed))",
       "legendFormat": "{{headOrg}}"
      }
     ]
    },
    {
     "title": "Cancelled/Nullified",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.90, sum(rate(ejustice_ecase_loading_duration_in_seconds_bucket{kubernetes_namespace=\"production\", app=\"rwa-iecms\", kubernetes_name=\"rwaiecmsui-v1\", location=\"/pages/438\"}[$__rate_interval])) by (le, networkSpeed))",
       "legendFormat": "{{headOrg}}"
      }
     ]
    }
   ]
  }
 ]
}