{
 "title": "Indexing",
 "time": { "from": "2025-11-25T12:50:59.000Z", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(database_pool_active_connections{service=\"lex-vue-service\"}, kubernetes_namespace)"
    }
   },
   {
    "name": "deployment",
    "label": "Deployment",
    "query": {
     "query": "label_values(database_pool_active_connections{service=\"lex-vue-service\", kubernetes_namespace=\"$namespace\"}, kubernetes_name)"
    }
   },
   {
    "name": "librarian_namespace",
    "label": "Librarian Namespace",
    "query": {
     "query": "label_values(container_cpu_usage_seconds_total{container=~\"librarian.*\"}, namespace)"
    }
   },
   {
    "name": "librarian_deployment",
    "label": "Librarian Deployment",
    "query": {
     "query": "label_values(container_cpu_usage_seconds_total{container=~\"librarian.*\", namespace=\"$librarian_namespace\"}, container)"
    }
   },
   {
    "name": "qdrant_namespace",
    "label": "Qdrant Namespace",
    "query": {
     "query": "label_values(container_cpu_usage_seconds_total{container=~\"qdrant.*\"}, namespace)"
    }
   },
   {
    "name": "qdrant_deployment",
    "label": "Qdrant Deployment",
    "query": {
     "query": "label_values(container_cpu_usage_seconds_total{container=~\"qdrant.*\", namespace=\"$qdrant_namespace\"}, container)"
    }
   },
   {
    "name": "server",
    "query": {
     "query": "label_values(DCGM_FI_DEV_GPU_TEMP,Hostname)"
    }
   }
  ]
 },
 "panels": [
  { "title": "LEXVUE - HTTP Client Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "HTTP Client Connections",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "max(http_client_active_connections{kubernetes_namespace=\"$namespace\",kubernetes_name=\"$deployment\"})",
     "legendFormat": "Active"
    },
    {
     "expr": "max(http_client_idle_connections{kubernetes_namespace=\"$namespace\",kubernetes_name=\"$deployment\"})",
     "legendFormat": "Idle"
    }
   ]
  },
  {
   "title": "HTTP Client Latency",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_client_response_time_ms_bucket{kubernetes_namespace=\"$namespace\",kubernetes_name=\"$deployment\"}[$__rate_interval])) by (le))",
     "legendFormat": "95P"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(http_client_response_time_ms_bucket{kubernetes_namespace=\"$namespace\",kubernetes_name=\"$deployment\"}[$__rate_interval])) by (le))",
     "legendFormat": "90P"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(http_client_response_time_ms_bucket{kubernetes_namespace=\"$namespace\",kubernetes_name=\"$deployment\"}[$__rate_interval])) by (le))",
     "legendFormat": "75P"
    }
   ]
  },
  {
   "title": "HTTP Client Total Requests Rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "rate(http_client_total_requests{kubernetes_namespace=\"$namespace\",kubernetes_name=\"$deployment\"}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "HTTP Client 4xx / 5xx Errors (rate)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 10, "y": 7 },
   "targets": [
    {
     "expr": "sum(rate(http_client_status_4xx_total{kubernetes_namespace=\"$namespace\",kubernetes_name=\"$deployment\"}[5m]))",
     "legendFormat": "4xx"
    },
    {
     "expr": "sum(rate(http_client_status_5xx_total{kubernetes_namespace=\"$namespace\",kubernetes_name=\"$deployment\"}[5m]))",
     "legendFormat": "5xx"
    }
   ]
  },
  { "title": "LEXVUE - CPU & Memory Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\",container=\"$deployment\"}[$__rate_interval])) by (pod)",
     "legendFormat": "cpu usage"
    }
   ]
  },
  {
   "title": "Pod Memory &  Swap",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 10, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{namespace=\"$namespace\", container=\"$deployment\"}",
     "legendFormat": "Memory"
    },
    {
     "expr": "container_memory_swap{namespace=\"$namespace\", container=\"$deployment\"}",
     "legendFormat": "Swap"
    }
   ]
  },
  {
   "title": "# of Restarts",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_pod_container_status_restarts_total{namespace=\"$namespace\", container=\"$deployment\"}",
     "legendFormat": "restarts count"
    }
   ]
  },
  {
   "title": "LIBRARIAN - CPU & GPU & Memory Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 }
  },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"$librarian_namespace\",container=\"$librarian_deployment\"}[$__rate_interval])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Pod Memory &  Swap",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 10, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{namespace=\"$librarian_namespace\",container=\"$librarian_deployment\"}",
     "legendFormat": "Memory"
    },
    {
     "expr": "rate(container_memory_usage_bytes{namespace=\"$librarian_namespace\",container=\"$librarian_deployment\"}[$__rate_interval])",
     "legendFormat": "Rate"
    }
   ]
  },
  {
   "title": "# of Restarts",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_pod_container_status_restarts_total{namespace=\"$librarian_namespace\",container=\"$librarian_deployment\"}",
     "legendFormat": "restarts count"
    }
   ]
  },
  {
   "title": "GPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "DCGM_FI_DEV_GPU_UTIL{Hostname=\"$server\", container=\"$librarian_deployment\"}",
     "legendFormat": "GPU {{gpu}} {{pod}}",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "GPU Memory Used",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 10, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "DCGM_FI_DEV_FB_USED{Hostname=\"$server\", container=\"$librarian_deployment\"}",
     "legendFormat": "GPU {{gpu}} {{pod}}",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "QDRANT - CPU & GPU & Memory Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 }
  },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"$qdrant_namespace\",container=\"$qdrant_deployment\"}[$__rate_interval])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Pod Memory &  Swap",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 10, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{namespace=\"$qdrant_namespace\",container=\"$qdrant_deployment\"}",
     "legendFormat": "Memory"
    },
    {
     "expr": "container_memory_swap{namespace=\"$qdrant_namespace\",container=\"$qdrant_deployment\"}",
     "legendFormat": "Swap"
    }
   ]
  },
  {
   "title": "# of Restarts",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_pod_container_status_restarts_total{namespace=\"$qdrant_namespace\",container=\"$qdrant_deployment\"}",
     "legendFormat": "restarts count"
    }
   ]
  },
  {
   "title": "GPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "DCGM_FI_DEV_GPU_UTIL{Hostname=\"$server\", container=\"$qdrant_deployment\"}",
     "legendFormat": "GPU {{gpu}}",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "GPU Memory Used",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 10, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "DCGM_FI_DEV_FB_USED{Hostname=\"$server\", container=\"$qdrant_deployment\"}",
     "legendFormat": "GPU {{gpu}}",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "timestamp"
    }
   ]
  }
 ]
}