filebeat.inputs:
- type: log
  paths:
    - /applogs/*/*/*/logs/*.log
  multiline.pattern: '^[0-9]{4}-[0-9]{2}-[0-9]{2}'
  multiline.negate: true
  multiline.match: after
max_procs: 2
output.logstash:
  hosts: ["logstash:5044"]



