{
 "title": "Microservice & Gateway Resource Usage",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(container_memory_usage_bytes,namespace)"
    }
   },
   {
    "name": "service",
    "query": {
     "query": "label_values(container_memory_usage_bytes{namespace=\"$namespace\"},container)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(container_memory_usage_bytes{namespace=\"$namespace\",container=~\"$service\"},pod)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU  Usage Rate (Service)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\",container!~\"service-gateway\",container=~\".+\", pod=~\"$pod\"}[$__rate_interval])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory Usage (Service)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{namespace=\"$namespace\", container!=\"service-gateway\", container=~\".+\", pod=~\"$pod\"}",
     "legendFormat": "{{pod}} "
    }
   ]
  },
  { "title": "Gateway", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "CPU  Usage Rate (Gateway)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\",container=\"service-gateway\",container=~\".+\", pod=~\"$pod\"}[$__rate_interval])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory Usage (Gateway)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{namespace=\"$namespace\", container=\"service-gateway\", container=~\".+\", pod=~\"$pod\"}",
     "legendFormat": "{{pod}} "
    }
   ]
  }
 ]
}