{
 "title": "Jetty – Full Statistics",
 "tags": [
  "jetty",
  "prometheus",
  "kubernetes"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(jetty_requests_total, kubernetes_namespace)"
    }
   },
   {
    "name": "service",
    "query": {
     "query": "label_values(jetty_requests_total{kubernetes_namespace=\"$namespace\"}, kubernetes_name)"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "label_values(jetty_requests_total{kubernetes_namespace=\"$namespace\", kubernetes_name=\"$service\"},instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overall", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Latencies (2xx)",
   "type": "table",
   "description": "Latency percentiles computed over the selected dashboard time range.\n\nEach percentile (P50–P99) represents the distribution of all successful requests (2xx) that occurred within the selected time window (e.g. last 3h), based on histogram bucket counts (increase).\n\nUse this table to understand overall user experience during the selected period, not real-time latency spikes.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum by (path) (\n  increase(http_server_request_duration_seconds_count{\n    kubernetes_namespace=\"$namespace\",\n    kubernetes_name=\"$service\",\n    status=\"2xx\"\n  }[$__range])\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(\n  0.50,\n  sum by (le, path) (\n    increase(http_server_request_duration_seconds_bucket{\n      kubernetes_namespace=\"$namespace\",\n      kubernetes_name=\"$service\",\n      status=\"2xx\"\n    }[$__range])\n  )\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(\n  0.75,\n  sum by (le, path) (\n    increase(http_server_request_duration_seconds_bucket{\n      kubernetes_namespace=\"$namespace\",\n      kubernetes_name=\"$service\",\n      status=\"2xx\"\n    }[$__range])\n  )\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(\n  0.90,\n  sum by (le, path) (\n    increase(http_server_request_duration_seconds_bucket{\n      kubernetes_namespace=\"$namespace\",\n      kubernetes_name=\"$service\",\n      status=\"2xx\"\n    }[$__range])\n  )\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(\n  0.95,\n  sum by (le, path) (\n    increase(http_server_request_duration_seconds_bucket{\n      kubernetes_namespace=\"$namespace\",\n      kubernetes_name=\"$service\",\n      status=\"2xx\"\n    }[$__range])\n  )\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(\n  0.99,\n  sum by (le, path) (\n    increase(http_server_request_duration_seconds_bucket{\n      kubernetes_namespace=\"$namespace\",\n      kubernetes_name=\"$service\",\n      status=\"2xx\"\n    }[$__range])\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Latency Percentiles",
   "type": "timeseries",
   "description": "NOTE! This panel considers only 2xx requests. It answers the question \"How fast are successful requests?\"\n\nPercentiles (P50–P99) are calculated from histogram bucket rates over a rolling window (5m), reflecting current request behavior.\n\nThis panel is sensitive to short-term spikes and low traffic and is intended for monitoring live latency changes, not historical summaries.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.50,\n  sum by (le) (\n    rate(http_server_request_duration_seconds_bucket{\n        kubernetes_namespace=\"$namespace\",\n        kubernetes_name=\"$service\",\n        status=\"2xx\"\n    }[5m])\n  )\n)",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(\n  0.75,\n  sum by (le) (\n    rate(http_server_request_duration_seconds_bucket{\n        kubernetes_namespace=\"$namespace\",\n        kubernetes_name=\"$service\",\n        status=\"2xx\"\n    }[5m])\n  )\n)",
     "legendFormat": "P75"
    },
    {
     "expr": "histogram_quantile(\n  0.90,\n  sum by (le) (\n    rate(http_server_request_duration_seconds_bucket{\n        kubernetes_namespace=\"$namespace\",\n        kubernetes_name=\"$service\",\n        status=\"2xx\"\n    }[5m])\n  )\n)",
     "legendFormat": "P90"
    },
    {
     "expr": "histogram_quantile(\n  0.95,\n  sum by (le) (\n    rate(http_server_request_duration_seconds_bucket{\n        kubernetes_namespace=\"$namespace\",\n        kubernetes_name=\"$service\",\n        status=\"2xx\"\n    }[5m])\n  )\n)",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(\n  0.99,\n  sum by (le) (\n    rate(http_server_request_duration_seconds_bucket{\n        kubernetes_namespace=\"$namespace\",\n        kubernetes_name=\"$service\",\n        status=\"2xx\"\n    }[5m])\n  )\n)",
     "legendFormat": "P99"
    }
   ]
  },
  {
   "title": "Thread Pool – Threads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum(jetty_thread_pool_size{kubernetes_namespace=\"$namespace\",kubernetes_name=\"$service\", instance=~\"$instance\"})",
     "legendFormat": "total"
    },
    {
     "expr": "sum(jetty_thread_pool_busy{kubernetes_namespace=\"$namespace\",kubernetes_name=\"$service\", instance=~\"$instance\"})",
     "legendFormat": "busy"
    },
    {
     "expr": "sum(jetty_thread_pool_idle{kubernetes_namespace=\"$namespace\",kubernetes_name=\"$service\", instance=~\"$instance\"})",
     "legendFormat": "idle"
    },
    {
     "expr": "sum(jetty_thread_pool_max_size{kubernetes_namespace=\"$namespace\",kubernetes_name=\"$service\", instance=~\"$instance\"})",
     "legendFormat": "max"
    },
    {
     "expr": "sum(jetty_thread_pool_min_size{kubernetes_namespace=\"$namespace\",kubernetes_name=\"$service\", instance=~\"$instance\"})",
     "legendFormat": "min"
    }
   ]
  },
  {
   "title": "Thread Pool – Queue Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "sum(jetty_thread_pool_queued{kubernetes_namespace=\"$namespace\",kubernetes_name=\"$service\", instance=~\"$instance\"})",
     "legendFormat": "queued jobs"
    }
   ]
  },
  {
   "title": "Responses by Status Code",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum(rate(jetty_responses_total{kubernetes_namespace=\"$namespace\",kubernetes_name=\"$service\"}[$__rate_interval])) by (code)",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "Active Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "sum(jetty_requests_active{kubernetes_namespace=\"$namespace\",kubernetes_name=\"$service\", instance=~\"$instance\"})",
     "legendFormat": "active"
    },
    {
     "expr": "sum(jetty_requests_active_max{kubernetes_namespace=\"$namespace\",kubernetes_name=\"$service\", instance=~\"$instance\"})",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "Requests – Total Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "sum(rate(jetty_requests_total{kubernetes_namespace=\"$namespace\",kubernetes_name=\"$service\",instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "req/s {{instance}}"
    }
   ]
  },
  {
   "title": "Request Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(jetty_request_time_seconds_total{kubernetes_namespace=\"$namespace\",kubernetes_name=\"$service\"}[$__rate_interval])",
     "legendFormat": "seconds/sec {{instance}}"
    },
    {
     "expr": "rate(jetty_request_time_seconds_total{\n    kubernetes_namespace=\"$namespace\",\n    kubernetes_name=\"$service\"\n  }[$__rate_interval])\n/\nrate(jetty_requests_total{\n    kubernetes_namespace=\"$namespace\",\n    kubernetes_name=\"$service\"\n  }[$__rate_interval])",
     "legendFormat": "avg latency {{instance}}"
    }
   ]
  },
  {
   "title": "Instance $instance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 },
   "repeat": "instance",
   "collapsed": true,
   "panels": [
    {
     "title": "Thread Pool – Threads",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
     "targets": [
      {
       "expr": "sum(jetty_thread_pool_size{kubernetes_namespace=\"$namespace\",kubernetes_name=\"$service\", instance=~\"$instance\"})",
       "legendFormat": "total"
      },
      {
       "expr": "sum(jetty_thread_pool_busy{kubernetes_namespace=\"$namespace\",kubernetes_name=\"$service\", instance=~\"$instance\"})",
       "legendFormat": "busy"
      },
      {
       "expr": "sum(jetty_thread_pool_idle{kubernetes_namespace=\"$namespace\",kubernetes_name=\"$service\", instance=~\"$instance\"})",
       "legendFormat": "idle"
      }
     ]
    },
    {
     "title": "Thread Pool – Queue Size",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
     "targets": [
      {
       "expr": "sum(jetty_thread_pool_queued{kubernetes_namespace=\"$namespace\",kubernetes_name=\"$service\", instance=~\"$instance\"})",
       "legendFormat": "queued jobs"
      }
     ]
    },
    {
     "title": "Requests – Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
     "targets": [
      {
       "expr": "rate(jetty_requests_total{kubernetes_namespace=\"$namespace\",kubernetes_name=\"$service\",instance=~\"$instance\"}[$__rate_interval])",
       "legendFormat": "req/s {{instance}}"
      }
     ]
    },
    {
     "title": "Responses by Status Code",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
     "targets": [
      {
       "expr": "sum(rate(jetty_responses_total{kubernetes_namespace=\"$namespace\",kubernetes_name=\"$service\", instance=~\"$instance\"}[$__rate_interval])) by (code)",
       "legendFormat": "{{code}}"
      }
     ]
    }
   ]
  }
 ]
}