{
 "title": "Microservices Performance Summary",
 "description": "CPU, memory, latency, error rates per service",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(up,kubernetes_namespace)"
    }
   },
   {
    "name": "service",
    "query": {
     "query": "label_values(up{kubernetes_namespace=\"$namespace\"},kubernetes_name)"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "label_values(up{kubernetes_namespace=\"$namespace\", kubernetes_name=\"$service\"},instance)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(container_memory_usage_bytes{namespace=\"$namespace\" , container=\"$service\"},pod)"
    }
   },
   {
    "name": "nginx_host",
    "query": "{\"find\": \"terms\", \"field\": \"request_host.keyword\"}"
   },
   {
    "name": "kibana_service",
    "query": {
     "query": "label_values(up{kubernetes_name=\"$service\"},kubernetes_name)"
    }
   },
   {
    "name": "kibana_service_version",
    "query": {
     "query": "label_values(up{kubernetes_name=\"$service\"},kubernetes_name)"
    }
   },
   { "name": "db_server", "query": { "query": "label_values(pg_up,instance)" } },
   {
    "name": "db_name",
    "query": {
     "query": "label_values(pg_query_execution_count{instance=~\"$db_server\"},db_name)  "
    }
   },
   {
    "name": "user_name",
    "query": {
     "query": "label_values(pg_query_execution_count{instance=~\"$db_server\", db_name=~\"$db_name\"}, user_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "# of 2xx requests",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "select field",
       "hide": false,
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "type:nginx-access AND request_host:\"$nginx_host\" AND nginx.service.name:\"$kibana_service\" AND status_code:2??",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "# of 3xx requests",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "select field",
       "hide": false,
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "type:nginx-access AND request_host:\"$nginx_host\" AND nginx.service.name:\"$kibana_service\" AND status_code:3??",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "# of 4xx requests",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "select field",
       "hide": false,
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "type:nginx-access AND request_host:\"$nginx_host\" AND nginx.service.name:\"$kibana_service\" AND status_code:4??",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "# of 5xx requests",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "select field",
       "hide": false,
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "type:nginx-access AND request_host:\"$nginx_host\" AND nginx.service.name:\"$kibana_service\" AND status_code:5??",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "# of INFO Logs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "select field",
       "hide": false,
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "type:log AND app.environment:\"$namespace\" AND app.service.name:\"$kibana_service\" AND app.service.version:\"$kibana_service_version\" AND app.loglevel:\"INFO\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "# of WARN Logs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "select field",
       "hide": false,
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "type:log AND app.environment:\"$namespace\" AND app.service.name:\"$kibana_service\" AND app.service.version:\"$kibana_service_version\" AND app.loglevel:\"WARN\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "# of ERROR Logs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "select field",
       "hide": false,
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "type:log AND app.environment:\"$namespace\" AND app.service.name:\"$kibana_service\" AND app.service.version:\"$kibana_service_version\" AND app.loglevel:\"ERROR\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "HTTP",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "RPS",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "1s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "expr": "type:nginx-access  AND  request_host:\"$namespace.synisys.com\" AND nginx.service.name:\"$kibana_service\"",
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "type:nginx-access AND request_host:\"$nginx_host\" AND nginx.service.name:\"$kibana_service\"",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Response time",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "expr": "type:nginx-access  AND  request_host:\"$namespace.synisys.com\" AND nginx.service.name:\"$kibana_service\"",
       "metrics": [
        {
         "field": "request_time",
         "id": "1",
         "meta": {},
         "settings": { "percents": [ "95" ] },
         "type": "percentiles"
        },
        {
         "field": "upstream_response_time",
         "hide": true,
         "id": "3",
         "meta": {},
         "settings": { "percents": [ "95" ] },
         "type": "percentiles"
        }
       ],
       "query": "type:nginx-access AND request_host:\"$nginx_host\" AND nginx.service.name:\"$kibana_service\"",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Error Rate",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "alias": "Total",
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "type.keyword:nginx-access AND request_host.keyword:\"$nginx_host\" AND status_code.keyword:[100 TO 599] AND nginx.service.name:\"$kibana_service\"",
       "timeField": "@timestamp"
      },
      {
       "alias": "Error",
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "type.keyword:nginx-access AND request_host.keyword:\"$nginx_host\" AND status_code.keyword:[499 TO 599] AND nginx.service.name:\"$kibana_service\"",
       "timeField": "@timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "HTTP Distribution",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Status Code Distribution",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "count" ] } },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "status_code.keyword",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "10" },
         "type": "terms"
        }
       ],
       "expr": "type:nginx-access  AND  request_host:\"$namespace.synisys.com\" AND nginx.service.name:\"$kibana_service\"",
       "metrics": [
        {
         "hide": false,
         "id": "1",
         "type": "count"
        }
       ],
       "query": "type:nginx-access AND request_host:\"$nginx_host\" AND nginx.service.name:\"$kibana_service\"",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Method Distribution",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "count" ] } },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "method.keyword",
         "id": "5",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "10" },
         "type": "terms"
        }
       ],
       "expr": "type:nginx-access  AND  request_host:\"$namespace.synisys.com\" AND nginx.service.name:\"$kibana_service\"",
       "metrics": [
        {
         "hide": false,
         "id": "1",
         "type": "count"
        }
       ],
       "query": "type:nginx-access AND request_host:\"$nginx_host\" AND nginx.service.name:\"$kibana_service\"",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Source Service Distribution",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "source_service_name.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "type:nginx-access AND request_host:\"$nginx_host\" AND nginx.service.name:\"$kibana_service\"",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Fail Requests (Server Errors)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
     "targets": [
      {
       "alias": "{{source_service_name.keyword}} -> {{nginx.service.name.keyword}} ({{status_code.keyword}})",
       "bucketAggs": [
        {
         "field": "nginx.service.name.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        {
         "field": "status_code.keyword",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        {
         "field": "source_service_name.keyword",
         "id": "5",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "type.keyword:nginx-access AND request_host.keyword:\"$nginx_host\" AND (source_service_name.keyword:\"$kibana_service\" OR nginx.service.name.keyword:\"$kibana_service\") AND status_code:5??",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Fail Requests (Client Errors)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
     "targets": [
      {
       "alias": "{{source_service_name.keyword}} -> {{nginx.service.name.keyword}} ({{status_code.keyword}})",
       "bucketAggs": [
        {
         "field": "nginx.service.name.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        {
         "field": "status_code.keyword",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        {
         "field": "source_service_name.keyword",
         "id": "5",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "type.keyword:nginx-access AND request_host.keyword:\"$nginx_host\" AND (source_service_name.keyword:\"$kibana_service\" OR nginx.service.name.keyword:\"$kibana_service\") AND status_code:4??",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Top 20 by 95th Percentile",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "request_uri.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "4[95.0]", "size": "20" },
         "type": "terms"
        }
       ],
       "metrics": [
        { "id": "1", "type": "count" },
        { "field": "request_time", "id": "4", "settings": { "percents": [ "95" ] }, "type": "percentiles" }
       ],
       "query": "type:nginx-access AND request_host:\"$nginx_host\" AND nginx.service.name:\"$kibana_service\"",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Top 20 by Count",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "request_uri.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "20" },
         "type": "terms"
        }
       ],
       "metrics": [
        { "id": "1", "type": "count" },
        { "field": "request_time", "id": "4", "settings": { "percents": [ "95" ] }, "type": "percentiles" }
       ],
       "query": "type:nginx-access AND request_host:\"$nginx_host\" AND nginx.service.name:\"$kibana_service\"",
       "timeField": "@timestamp"
      }
     ]
    }
   ]
  },
  { "title": "HTTP Server", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Number of requests queued waiting for a thread",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "sum(jetty_thread_pool_queued{kubernetes_namespace=\"$namespace\", kubernetes_name=\"$service\", instance=~\"$instance\"})",
     "legendFormat": "queued"
    }
   ]
  },
  {
   "title": "Thread Pool Utilization (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * jetty_thread_pool_busy{kubernetes_namespace=\"$namespace\", kubernetes_name=\"$service\"} / jetty_thread_pool_size{kubernetes_namespace=\"$namespace\", kubernetes_name=\"$service\"}",
     "legendFormat": "% busy"
    }
   ]
  },
  {
   "title": "HTTP Client",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "HTTP Connections Pool",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 21, "x": 0, "y": 15 },
     "targets": [
      {
       "expr": "http_client_pool_leased{kubernetes_namespace=\"$namespace\",kubernetes_name=\"$service\"}",
       "legendFormat": "leased"
      },
      {
       "expr": "http_client_pool_available{kubernetes_namespace=\"$namespace\",kubernetes_name=\"$service\"}",
       "legendFormat": "available"
      },
      {
       "expr": "http_client_pool_pending{kubernetes_namespace=\"$namespace\",kubernetes_name=\"$service\"}",
       "legendFormat": "pending"
      }
     ]
    },
    {
     "title": "Max Size",
     "type": "stat",
     "gridPos": { "h": 8, "w": 3, "x": 21, "y": 15 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "http_client_pool_max{kubernetes_namespace=\"$namespace\",kubernetes_name=\"$service\"}",
       "legendFormat": "max"
      }
     ]
    }
   ]
  },
  {
   "title": "Outgoing HTTP Requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "Outgoing Request's Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "bucketAggs": [
        {
         "fake": true,
         "field": "nginx.service.name.keyword",
         "id": "4",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1[95.0]", "size": "20" },
         "type": "terms"
        },
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "expr": "type:nginx-access  AND  request_host:\"$namespace.synisys.com\" AND nginx.service.name:\"$kibana_service\"",
       "metrics": [
        {
         "field": "request_time",
         "id": "1",
         "meta": {},
         "settings": { "percents": [ "95" ] },
         "type": "percentiles"
        }
       ],
       "query": "type.keyword:nginx-access AND request_host.keyword:\"$nginx_host\" AND source_service_name.keyword:\"$kibana_service\"",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Target Service Distribution",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "nginx.service.name.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "type:nginx-access AND request_host:\"$nginx_host\" AND source_service_name:\"$kibana_service\"",
       "timeField": "@timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Pod Memory &  Swap ($pod)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 17, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "container_memory_usage_bytes{namespace=\"$namespace\", container=\"$service\", pod=~\"$pod\"}",
       "legendFormat": "Memory (service)"
      },
      {
       "expr": "container_memory_swap{namespace=\"$namespace\", container=\"$service\", pod=~\"$pod\"}",
       "legendFormat": "Swap (service)"
      },
      {
       "expr": "container_memory_usage_bytes{namespace=\"$namespace\", container=\"service-gateway\", pod=~\"$pod\"}",
       "legendFormat": "Memory (gateway)"
      },
      {
       "expr": "container_memory_swap{namespace=\"$namespace\", container=\"service-gateway\", pod=~\"$pod\"}",
       "legendFormat": "Swap (gateway)"
      }
     ]
    },
    {
     "title": "Memory Max Size",
     "type": "stat",
     "gridPos": { "h": 6, "w": 7, "x": 17, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "jvm_memory_pool_bytes_max{kubernetes_name=\"$service\",kubernetes_namespace=\"$namespace\", instance=~\"$instance\"} > 0",
       "legendFormat": "{{pool}}"
      }
     ]
    },
    {
     "title": "Heap Memory Usage ($instance)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 17, "x": 0, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "jvm_memory_pool_bytes_used{kubernetes_name=\"$service\",kubernetes_namespace=\"$namespace\", instance=~\"$instance\", pool!~\"^(Metaspace|Compressed Class Space|Code Cache|CodeHeap.+)$\"}",
       "legendFormat": "{{pool}} ({{instance}})"
      },
      {
       "expr": "jvm_memory_used_bytes{kubernetes_name=\"$service\",kubernetes_namespace=\"$namespace\", area=\"heap\", instance=~\"$instance\"}",
       "legendFormat": "{{id}} ({{instance}})"
      }
     ]
    },
    {
     "title": "Non-Heap Memory Usage ($instance)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 7, "x": 17, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "jvm_memory_pool_bytes_used{kubernetes_name=\"$service\",kubernetes_namespace=\"$namespace\", instance=~\"$instance\", pool=~\"^(Metaspace|Compressed Class Space|Code Cache|CodeHeap.+)$\"}",
       "legendFormat": "{{pool}}"
      },
      {
       "expr": "jvm_memory_used_bytes{kubernetes_name=\"$service\",kubernetes_namespace=\"$namespace\", area=\"nonheap\", instance=~\"$instance\"}",
       "legendFormat": "{{id}}"
      }
     ]
    },
    {
     "title": "GC collection time",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 17, "x": 0, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(jvm_gc_collection_seconds_sum{instance=~\"$instance\",kubernetes_name=~\"$service\",kubernetes_namespace=~\"$namespace\"}[$__rate_interval])",
       "legendFormat": "{{gc}}"
      },
      {
       "expr": "rate(jvm_gc_pause_seconds_sum{instance=~\"$instance\",kubernetes_name=~\"$service\",kubernetes_namespace=~\"$namespace\"}[$__rate_interval])",
       "legendFormat": "{{gc}}"
      }
     ]
    }
   ]
  },
  {
   "title": "CPU Usage & Threads",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU usage ($pod)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 17, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{pod=~\"$pod\", image!~\"\",namespace=~\"$namespace\",container=~\"$service\",kubernetes_io_hostname=~\".+\"}[$__rate_interval])) by (pod)",
       "legendFormat": "cpu usage (service)"
      },
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{pod=~\"$pod\", image!~\"\",namespace=~\"$namespace\",container=\"service-gateway\",kubernetes_io_hostname=~\".+\"}[$__rate_interval])) by (pod)",
       "legendFormat": "cpu usage (gateway)"
      }
     ]
    },
    {
     "title": "Service Up Time",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 4, "x": 17, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "up{kubernetes_name=\"$service\",kubernetes_namespace=\"$namespace\", instance=~\"$instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "# of Restarts",
     "type": "stat",
     "gridPos": { "h": 7, "w": 3, "x": 21, "y": 6 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "kube_pod_container_status_restarts_total{namespace=\"$namespace\", container=\"$service\"}",
       "legendFormat": "restarts count"
      }
     ]
    },
    {
     "title": "threading",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 17, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "jvm_threads_current{instance=~\"$instance\",kubernetes_name=\"$service\",kubernetes_namespace=\"$namespace\"}",
       "legendFormat": "current"
      },
      {
       "expr": "jvm_threads_peak{instance=~\"$instance\",kubernetes_name=\"$service\",kubernetes_namespace=\"$namespace\"}",
       "legendFormat": "peak"
      },
      {
       "expr": "jvm_threads_daemon{instance=~\"$instance\",kubernetes_name=\"$service\",kubernetes_namespace=\"$namespace\"}",
       "legendFormat": "daemon"
      },
      {
       "expr": "jvm_threads_deadlocked{instance=~\"$instance\",kubernetes_name=\"$service\",kubernetes_namespace=\"$namespace\"}",
       "legendFormat": "deadlocked"
      }
     ]
    },
    {
     "title": "JVM Thread States",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 7, "x": 17, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "jvm_threads_state{instance=~\"$instance\",kubernetes_name=\"$service\",kubernetes_namespace=\"$namespace\"}",
       "legendFormat": "{{state}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Database",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "Execution Count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "pg_query_execution_count{db_name=~\"$db_name\",instance=~\"$db_server\", user_name=~\"$user_name\"}",
       "legendFormat": "{{user_name}}"
      }
     ]
    },
    {
     "title": "Execution Time Max",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "pg_query_execution_time_max{db_name=~\"$db_name\", instance=~\"$db_server\", user_name=~\"$user_name\"}",
       "legendFormat": "{{user_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Database Connections Pool",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "Connections Pool Max Size",
     "type": "piechart",
     "gridPos": { "h": 4, "w": 8, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max(hikaricp_max_connections{kubernetes_namespace=\"$namespace\", kubernetes_name=\"$service\"}) by (pool)",
       "legendFormat": "{{pool}}"
      }
     ]
    },
    {
     "title": "Total Available Connections",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 8, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(hikaricp_max_connections{kubernetes_namespace=\"$namespace\", kubernetes_name=\"$service\"})"
      }
     ]
    },
    {
     "title": "Total Active Connections",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 12, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(hikaricp_active_connections{kubernetes_namespace=\"$namespace\", kubernetes_name=\"$service\"})"
      },
      {
       "expr": "sum(vertx_pool_in_use{kubernetes_name=\"$service\",kubernetes_namespace=\"$namespace\", pool_type=\"sql\"})"
      }
     ]
    },
    {
     "title": "Total Idle Connections",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 16, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(hikaricp_idle_connections{kubernetes_namespace=\"$namespace\", kubernetes_name=\"$service\"})"
      }
     ]
    },
    {
     "title": "Total Pending Threads",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 20, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(hikaricp_pending_threads{kubernetes_namespace=\"$namespace\", kubernetes_name=\"$service\"})"
      },
      {
       "expr": "sum(vertx_pool_queue_pending{kubernetes_name=\"$service\",kubernetes_namespace=\"$namespace\", pool_type=\"sql\"})"
      }
     ]
    },
    {
     "title": "SQL Query Execution Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 28 },
     "targets": [
      {
       "expr": "sum(rate(multidatasource_query_execution_seconds_count{kubernetes_name=\"$service\", kubernetes_namespace=\"$namespace\"}[$__rate_interval] ) )by(app)",
       "legendFormat": "qps ({{app}})"
      },
      {
       "expr": "sum(rate(vertx_sql_processing_time_seconds_count{kubernetes_name=\"$service\", kubernetes_namespace=\"$namespace\"}[$__rate_interval]))",
       "legendFormat": "qps"
      }
     ]
    },
    {
     "title": "SQL Query Execution Duration Rate / 95th Percentile",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(multidatasource_query_execution_seconds_bucket{kubernetes_namespace=\"$namespace\", kubernetes_name=\"$service\"}[$__rate_interval])) by (le, app))",
       "legendFormat": "95th Percentile ({{app}})"
      },
      {
       "expr": "sum(rate(multidatasource_query_execution_seconds_sum{kubernetes_namespace=\"$namespace\", kubernetes_name=\"$service\"}[$__rate_interval]))",
       "legendFormat": "rate"
      },
      {
       "expr": "sum(rate(vertx_sql_processing_time_seconds_sum{kubernetes_name=\"$service\", kubernetes_namespace=\"$namespace\"}[$__rate_interval]))",
       "legendFormat": "rate"
      }
     ]
    },
    {
     "title": "Database Connections Pool",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "hikaricp_active_connections{kubernetes_namespace=\"$namespace\", kubernetes_name=\"$service\"} > 0",
       "legendFormat": "active ({{pool}})"
      },
      {
       "expr": "hikaricp_idle_connections{kubernetes_namespace=\"$namespace\", kubernetes_name=\"$service\"} > 0",
       "legendFormat": "idle ({{pool}})"
      },
      {
       "expr": "hikaricp_pending_threads{kubernetes_namespace=\"$namespace\", kubernetes_name=\"$service\"} > 0",
       "legendFormat": "pending ({{pool}})"
      },
      {
       "expr": "sum(vertx_pool_in_use{kubernetes_name=\"$service\",kubernetes_namespace=\"$namespace\", pool_type=\"sql\", instance=~\"$instance\"})",
       "legendFormat": "in use"
      },
      {
       "expr": "sum(vertx_pool_queue_pending{kubernetes_name=\"$service\",kubernetes_namespace=\"$namespace\", pool_type=\"sql\", instance=~\"$instance\"})",
       "legendFormat": "pending"
      }
     ]
    }
   ]
  }
 ]
}