{
 "title": "Microservice Performance Trends",
 "description": "This dashboard provides key performance metrics for the selected microservice, including RPS, latency, query rate, and query duration. It enables comparison of current values with historical data from 1 to 7 days ago, helping to identify performance regressions, improvements, or anomalies over time. ",
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(jvm_info,kubernetes_namespace)"
    }
   },
   {
    "name": "service",
    "query": {
     "query": "label_values(jvm_info{kubernetes_namespace=\"$namespace\"},kubernetes_name)"
    }
   },
   {
    "name": "nginx_host",
    "query": "{\"find\": \"terms\", \"field\": \"request_host.keyword\"}"
   },
   {
    "name": "kibana_service",
    "query": {
     "query": "label_values(jvm_info{kubernetes_name=\"$service\"}, kubernetes_name)"
    }
   },
   {
    "name": "kibana_service_version",
    "query": {
     "query": "label_values(jvm_info{kubernetes_name=\"$service\"}, kubernetes_name)"
    }
   },
   { "name": "db_server", "query": { "query": "label_values(pg_up,instance)" } },
   {
    "name": "db_name",
    "query": {
     "query": "label_values(pg_query_execution_count{instance=~\"$db_server\"},db_name)  "
    }
   },
   {
    "name": "user_name",
    "query": {
     "query": "label_values(pg_query_execution_count{instance=~\"$db_server\", db_name=~\"$db_name\"}, user_name)"
    }
   },
   { "name": "shift", "query": "0d,1d,2d,3d,4d,5d,6d,7d" }
  ]
 },
 "panels": [
  {
   "title": "Requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Requests Per 10 Minute",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
     "repeat": "shift",
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "10m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "expr": "type:nginx-access  AND  request_host:\"$namespace.synisys.com\" AND nginx.service.name:\"$kibana_service\"",
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "type.keyword:nginx-access AND request_host.keyword:\"$nginx_host\" AND nginx.service.name.keyword:\"$kibana_service\"",
       "timeField": "@timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "Response Time",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Response time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 2 },
     "repeat": "shift",
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "20m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "expr": "type:nginx-access  AND  request_host:\"$namespace.synisys.com\" AND nginx.service.name:\"$kibana_service\"",
       "metrics": [
        {
         "field": "request_time",
         "id": "1",
         "meta": {},
         "settings": { "percents": [ "99" ] },
         "type": "percentiles"
        }
       ],
       "query": "type.keyword:nginx-access AND request_host.keyword:\"$nginx_host\" AND nginx.service.name.keyword:\"$kibana_service\"",
       "timeField": "@timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "Query Executions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "SQL Query Execution Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 3 },
     "repeat": "shift",
     "targets": [
      {
       "expr": "pg_query_execution_count{db_name=\"$db_name\", user_name=\"$user_name\", instance=\"$db_server\"}",
       "legendFormat": "qps"
      }
     ]
    }
   ]
  },
  {
   "title": "Query Latency",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Execution Time Max",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 4 },
     "repeat": "shift",
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "max(pg_query_execution_time_max{db_name=~\"$db_name\", instance=~\"$db_server\", user_name=~\"$user_name\"}) by (user_name)",
       "legendFormat": "Duration"
      }
     ]
    }
   ]
  }
 ]
}