{
 "title": "Vert.x Performance & Pool Metrics",
 "description": "test",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(vertx_http_server_active_connections, kubernetes_namespace)"
    }
   },
   {
    "name": "service",
    "query": {
     "query": "label_values(vertx_http_server_active_connections{kubernetes_namespace=\"$namespace\"}, kubernetes_name)"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "label_values(vertx_http_server_active_connections{kubernetes_namespace=\"$namespace\",kubernetes_name=\"$service\"}, instance)"
    }
   },
   {
    "name": "pool",
    "query": {
     "query": "label_values(vertx_pool_in_use{kubernetes_namespace=\"$namespace\", kubernetes_name=\"$service\"},pool_type)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overall", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Active connections",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "vertx_http_server_active_connections{kubernetes_namespace=\"$namespace\", kubernetes_name=\"$service\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Global response time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(irate(vertx_http_server_response_time_seconds_sum{kubernetes_namespace=\"$namespace\", kubernetes_name=\"$service\", instance=~\"$instance\"}[$__rate_interval])) / sum(irate(vertx_http_server_response_time_seconds_count{kubernetes_namespace=\"$namespace\", kubernetes_name=\"$service\", instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "[avg]"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(vertx_http_server_response_time_seconds_bucket{kubernetes_namespace=\"$namespace\", kubernetes_name=\"$service\", instance=~\"$instance\"}[$__rate_interval])) by (le))",
     "legendFormat": "[med]"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(vertx_http_server_response_time_seconds_bucket{kubernetes_namespace=\"$namespace\", kubernetes_name=\"$service\", instance=~\"$instance\"}[$__rate_interval])) by (le))",
     "legendFormat": "[95p]"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(vertx_http_server_response_time_seconds_bucket{kubernetes_namespace=\"$namespace\", kubernetes_name=\"$service\", instance=~\"$instance\"}[$__rate_interval])) by (le))",
     "legendFormat": "[99p]"
    }
   ]
  },
  {
   "title": "Request count rate by error code",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "round(sum(rate(vertx_http_server_requests_total{kubernetes_namespace=\"$namespace\", kubernetes_name=\"$service\", instance=~\"$instance\"}[$__rate_interval])) by (code), 0.001)",
     "legendFormat": "{{code}}"
    }
   ]
  },
  { "title": "Routes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Request count rate by code and path",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "round(sum(rate(vertx_http_server_requests_total{kubernetes_namespace=\"$namespace\", kubernetes_name=\"$service\", instance=~\"$instance\"}[$__rate_interval])) by (code,method,route), 0.001)",
     "legendFormat": "{{code}} {{method}} {{route}}"
    }
   ]
  },
  {
   "title": "Response time by path",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(irate(vertx_http_server_response_time_seconds_sum{kubernetes_namespace=\"$namespace\", kubernetes_name=\"$service\", instance=~\"$instance\"}[$__rate_interval])) by (route) / sum(irate(vertx_http_server_response_time_seconds_count{kubernetes_namespace=\"$namespace\", kubernetes_name=\"$service\", instance=~\"$instance\"}[$__rate_interval])) by (route)",
     "legendFormat": "{{route}} [avg]"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(vertx_http_server_response_time_seconds_bucket{kubernetes_namespace=\"$namespace\", kubernetes_name=\"$service\", instance=~\"$instance\"}[$__rate_interval])) by (le,route))",
     "legendFormat": "{{route}} [med]"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(vertx_http_server_response_time_seconds_bucket{kubernetes_namespace=\"$namespace\", kubernetes_name=\"$service\", instance=~\"$instance\"}[$__rate_interval])) by (le,route))",
     "legendFormat": "{{route}} [99p]"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "HTTP Server bytes sent",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(vertx_http_server_response_bytes_sum{kubernetes_namespace=\"$namespace\", kubernetes_name=\"$service\", instance=~\"$instance\"}[$__rate_interval])) / sum(rate(vertx_http_server_response_bytes_count{kubernetes_namespace=\"$namespace\", kubernetes_name=\"$service\", instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "[avg]"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(vertx_http_server_response_bytes_bucket{kubernetes_namespace=\"$namespace\", kubernetes_name=\"$service\", instance=~\"$instance\"}[$__rate_interval])) by (le))",
     "legendFormat": "[med]"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(vertx_http_server_response_bytes_bucket{kubernetes_namespace=\"$namespace\", kubernetes_name=\"$service\", instance=~\"$instance\"}[$__rate_interval])) by (le))",
     "legendFormat": "[95p]"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(vertx_http_server_response_bytes_bucket{kubernetes_namespace=\"$namespace\", kubernetes_name=\"$service\", instance=~\"$instance\"}[$__rate_interval])) by (le))",
     "legendFormat": "[99p]"
    }
   ]
  },
  {
   "title": "HTTP Server bytes received",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(vertx_http_server_request_bytes_sum{kubernetes_namespace=\"$namespace\", kubernetes_name=\"$service\", instance=~\"$instance\"}[$__rate_interval])) / sum(rate(vertx_http_server_request_bytes_count{kubernetes_namespace=\"$namespace\", kubernetes_name=\"$service\", instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "[avg]"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(vertx_http_server_request_bytes_bucket{kubernetes_namespace=\"$namespace\", kubernetes_name=\"$service\", instance=~\"$instance\"}[$__rate_interval])) by (le))",
     "legendFormat": "[med]"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(vertx_http_server_request_bytes_bucket{kubernetes_namespace=\"$namespace\", kubernetes_name=\"$service\", instance=~\"$instance\"}[$__rate_interval])) by (le))",
     "legendFormat": "[95p]"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(vertx_http_server_request_bytes_bucket{kubernetes_namespace=\"$namespace\", kubernetes_name=\"$service\", instance=~\"$instance\"}[$__rate_interval])) by (le))",
     "legendFormat": "[99p]"
    }
   ]
  },
  {
   "title": "HTTP Client Pool",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "http_client_pool_max{kubernetes_namespace=\"$namespace\", kubernetes_name=\"$service\", instance=~\"$instance\"}",
     "legendFormat": "max"
    },
    {
     "expr": "http_client_pool_leased{kubernetes_namespace=\"$namespace\", kubernetes_name=\"$service\", instance=~\"$instance\"}",
     "legendFormat": "leased"
    },
    {
     "expr": "http_client_pool_available{kubernetes_namespace=\"$namespace\", kubernetes_name=\"$service\", instance=~\"$instance\"}",
     "legendFormat": "available"
    },
    {
     "expr": "http_client_pool_pending{kubernetes_namespace=\"$namespace\", kubernetes_name=\"$service\", instance=~\"$instance\"}",
     "legendFormat": "pending"
    }
   ]
  },
  {
   "title": "Event Bus",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 },
   "collapsed": true,
   "panels": [
    {
     "title": "Eventbus: handlers",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(vertx_eventbus_handlers{kubernetes_namespace=\"$namespace\", kubernetes_name=\"$service\", instance=~\"$instance\"}[$__rate_interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Eventbus: pending",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "vertx_eventbus_pending{kubernetes_namespace=\"$namespace\", kubernetes_name=\"$service\", instance=~\"$instance\"}",
       "legendFormat": "{{instance}} ({{side}})"
      }
     ]
    },
    {
     "title": "Eventbus: sent rate",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum(irate(vertx_eventbus_sent_total{kubernetes_namespace=\"$namespace\", kubernetes_name=\"$service\", instance=~\"$instance\"}[2m]))",
       "legendFormat": "2 minute instant rate"
      },
      {
       "expr": "sum(rate(vertx_eventbus_sent_total{kubernetes_namespace=\"$namespace\", kubernetes_name=\"$service\", instance=~\"$instance\"}[2m]))",
       "legendFormat": "2 minute rate"
      },
      {
       "expr": "sum(rate(vertx_eventbus_sent_total{kubernetes_namespace=\"$namespace\", kubernetes_name=\"$service\", instance=~\"$instance\"}[5m]))",
       "legendFormat": "5 minute rate"
      }
     ]
    },
    {
     "title": "Eventbus: received rate",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum(irate(vertx_eventbus_received_total{kubernetes_namespace=\"$namespace\", kubernetes_name=\"$service\", instance=~\"$instance\"}[2m]))",
       "legendFormat": "2 minute instant rate"
      },
      {
       "expr": "sum(rate(vertx_eventbus_received_total{kubernetes_namespace=\"$namespace\", kubernetes_name=\"$service\", instance=~\"$instance\"}[2m]))",
       "legendFormat": "2 minute rate"
      },
      {
       "expr": "sum(rate(vertx_eventbus_received_total{kubernetes_namespace=\"$namespace\", kubernetes_name=\"$service\", instance=~\"$instance\"}[5m]))",
       "legendFormat": "5 minute rate"
      }
     ]
    },
    {
     "title": "Eventbus: Processed",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(vertx_eventbus_processed_total{kubernetes_namespace=\"$namespace\", kubernetes_name=\"$service\", instance=~\"$instance\"}[$__rate_interval])) by (side)",
       "legendFormat": "Rate of messages processed"
      }
     ]
    },
    {
     "title": "Eventbus: Delivered",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(vertx_eventbus_delivered_total{kubernetes_namespace=\"$namespace\", kubernetes_name=\"$service\", instance=~\"$instance\"}[$__rate_interval])) by (side)",
       "legendFormat": "Rate of messages delivered"
      }
     ]
    },
    {
     "title": "Eventbus: Reply Failure Rates",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(vertx_eventbus_reply_failures_total{kubernetes_namespace=\"$namespace\", kubernetes_name=\"$service\", instance=~\"$instance\"}[$__rate_interval]))",
       "legendFormat": "Rate of reply failures"
      }
     ]
    }
   ]
  },
  { "title": "Pool Metrics ($pool)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 }, "repeat": "pool" },
  {
   "title": "Pool Usage Ratio (%)",
   "type": "timeseries",
   "description": "Shows how much of the pool is being used (0–100%). Helps spot overutilization or underuse.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "vertx_pool_ratio{kubernetes_name=\"$service\",kubernetes_namespace=\"$namespace\", pool_type=~\"$pool\", instance=~\"$instance\"}*100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Completed Tasks (rate)",
   "type": "timeseries",
   "description": "Total tasks completed per pool per second/minute. Useful for throughput.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(vertx_pool_completed_total{kubernetes_name=\"$service\",kubernetes_namespace=\"$namespace\", pool_type=~\"$pool\", instance=~\"$instance\"}[$__rate_interval])\n",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Resources in Use",
   "type": "timeseries",
   "description": "Number of resources currently in use. High sustained values may indicate saturation.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(vertx_pool_in_use{kubernetes_name=\"$service\",kubernetes_namespace=\"$namespace\", pool_type=~\"$pool\", instance=~\"$instance\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Queue Pending Requests",
   "type": "timeseries",
   "description": "If this value rises, your pool can't keep up with demand.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(vertx_pool_queue_pending{kubernetes_name=\"$service\",kubernetes_namespace=\"$namespace\", pool_type=~\"$pool\", instance=~\"$instance\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Avg Resource Usage Time (seconds)",
   "type": "timeseries",
   "description": "Shows how long, on average, a resource is held. Useful to detect slow operations.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(vertx_pool_usage_seconds_sum{kubernetes_name=\"$service\",kubernetes_namespace=\"$namespace\", pool_type=~\"$pool\", instance=~\"$instance\"}[$__rate_interval]) / rate(vertx_pool_usage_seconds_count{kubernetes_name=\"$service\",kubernetes_namespace=\"$namespace\", pool_type=~\"$pool\", instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Avg Queue Wait Time (seconds)",
   "type": "timeseries",
   "description": "How long items wait before execution — useful for tuning the pool size.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(vertx_pool_queue_time_seconds_sum{kubernetes_name=\"$service\",kubernetes_namespace=\"$namespace\", pool_type=~\"$pool\", instance=~\"$instance\"}[$__rate_interval]) / rate(vertx_pool_queue_time_seconds_count{kubernetes_name=\"$service\",kubernetes_namespace=\"$namespace\", pool_type=~\"$pool\", instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Max Resource Usage Time (seconds)",
   "type": "timeseries",
   "description": "Spikes indicate anomalies or blocking operations.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(vertx_pool_usage_seconds_max{kubernetes_name=\"$service\",kubernetes_namespace=\"$namespace\", pool_type=~\"$pool\", instance=~\"$instance\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Max Queue Wait Time (seconds)",
   "type": "timeseries",
   "description": "Useful for spotting spikes and delays.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(vertx_pool_queue_time_seconds_max{kubernetes_name=\"$service\",kubernetes_namespace=\"$namespace\", pool_type=~\"$pool\", instance=~\"$instance\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}