{
 "title": "Consume Template Changes",
 "description": "Provide a real-time summary of the entire system’s health",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(up, kubernetes_namespace)"
    }
   },
   {
    "name": "nginx_host",
    "query": "{\"find\": \"terms\", \"field\": \"request_host.keyword\"}"
   }
  ]
 },
 "panels": [
  {
   "title": "Publish Template Changes (export-template-service)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rabbitmq_queue_messages_publish_rate{kubernetes_namespace=\"$namespace\", queue=\"export-service-export-templates-service-template.delete\"}",
     "legendFormat": "delete queue"
    },
    {
     "expr": "rabbitmq_queue_messages_publish_rate{kubernetes_namespace=\"$namespace\", queue=\"export-service-export-template-service-template.update\"}",
     "legendFormat": "update queue"
    },
    {
     "expr": "rabbitmq_queue_messages_publish_rate{kubernetes_namespace=\"$namespace\", queue=\"export-service-export-template-service-template.create\"}",
     "legendFormat": "create queue"
    },
    {
     "expr": "rabbitmq_queue_messages_publish_rate{kubernetes_namespace=\"$namespace\", queue=\"export-service-export-templates-service-template.language\"}",
     "legendFormat": "language queue"
    }
   ]
  },
  {
   "title": "Queued Messages for Template Changes",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rabbitmq_queue_messages{kubernetes_namespace=\"$namespace\", queue=\"export-service-export-templates-service-template.delete\"}",
     "legendFormat": "delete queue"
    },
    {
     "expr": "rabbitmq_queue_messages{kubernetes_namespace=\"$namespace\", queue=\"export-service-export-template-service-template.update\"}",
     "legendFormat": "update queue"
    },
    {
     "expr": "rabbitmq_queue_messages{kubernetes_namespace=\"$namespace\", queue=\"export-service-export-template-service-template.create\"}",
     "legendFormat": "create queue"
    },
    {
     "expr": "rabbitmq_queue_messages{kubernetes_namespace=\"$namespace\", queue=\"export-service-export-templates-service-template.language\"}",
     "legendFormat": "language queue"
    }
   ]
  },
  {
   "title": "Write Errors While Saving Templates",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "alias": "write error",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "app.service.name.keyword:exportservice AND app.classname.keyword: \"com.synisys.idm.export.service.impl.ExportInternalServiceImpl\" AND app.logmessage : \"Error occurs while writing template.xml file in directory\"",
     "timeField": "@timestamp"
    },
    {
     "alias": "delete error",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "app.service.name.keyword:exportservice AND app.classname.keyword: \"com.synisys.idm.export.service.impl.ExportInternalServiceImpl\" AND app.logmessage : \"Can't delete folder\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Publish Template Changes (export-service)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "rabbitmq_queue_messages_publish_rate{kubernetes_namespace=\"$namespace\", queue=\"audit-service-idm-export-service-export.template.create.*\"}",
     "legendFormat": "create published"
    },
    {
     "expr": "rabbitmq_queue_messages_publish_rate{kubernetes_namespace=\"$namespace\", queue=\"audit-service-idm-export-service-export.template.update.*\"}",
     "legendFormat": "update published"
    },
    {
     "expr": "rabbitmq_queue_messages_publish_rate{kubernetes_namespace=\"$namespace\", queue=\"audit-service-idm-export-service-export.template.delete.*\"}",
     "legendFormat": "delete published"
    }
   ]
  }
 ]
}