{
 "title": "EBA Consumers",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(jvm_info,kubernetes_namespace)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(container_memory_usage_bytes{namespace=\"$namespace\", container=\"eventhandlerservice-v1\"},pod)"
    }
   },
   {
    "name": "application",
    "query": {
     "query": "label_values(hikaricp_connection_timeout_total{kubernetes_namespace=\"$namespace\", kubernetes_name=\"eventhandlerservice-v1\"},pool)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "# of Broker Accepted Messages ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "alias": "broker accepted",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "app.logmessage: \"Broker accepted\" AND app.classname.keyword: \"com.synisys.idm.eventhandler.internal.rule.action.ActionBroker\" AND app.name.keyword: \"$application\" AND app.environment.keyword: \"$namespace\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "# of Accepted Events",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "alias": "accepted event",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "app.logmessage: \"Accepted event\" AND app.classname.keyword: \"com.synisys.idm.eventhandler.internal.rule.action.ActionListener\" AND app.name.keyword: \"$application\" AND app.environment.keyword: \"$namespace\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "# of Consumed Entity Modifications",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "alias": "consumed entity modification",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "app.logmessage: \"Consumed entity modification\" AND app.name.keyword: \"$application\" AND app.environment.keyword: \"$namespace\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "$pod",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "repeat": "pod",
   "collapsed": true,
   "panels": [
    {
     "title": "# of Broker Accepted Messages ",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "targets": [
      {
       "alias": "broker accepted",
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "app.logmessage: \"Broker accepted\" AND app.hostname.keyword: \"$pod\" AND app.classname.keyword: \"com.synisys.idm.eventhandler.internal.rule.action.ActionBroker\" AND app.name.keyword: \"$application\" AND app.environment.keyword: \"$namespace\"",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "# of Accepted Events",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
     "targets": [
      {
       "alias": "accepted event",
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "app.logmessage: \"Accepted event\" AND app.hostname.keyword: \"$pod\" AND app.classname.keyword: \"com.synisys.idm.eventhandler.internal.rule.action.ActionListener\" AND app.name.keyword: \"$application\" AND app.environment.keyword: \"$namespace\"",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "# of Consumed Entity Modifications",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
     "targets": [
      {
       "alias": "consumed entity modification",
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "app.logmessage: \"Consumed entity modification\" AND app.hostname.keyword: \"$pod\" AND app.name.keyword: \"$application\" AND app.environment.keyword: \"$namespace\"",
       "timeField": "@timestamp"
      }
     ]
    }
   ]
  }
 ]
}