{
 "title": "EBA Pre-Processors",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(event_handler_service_preproc_msg_total,kubernetes_namespace)"
    }
   },
   {
    "name": "application",
    "query": {
     "query": "label_values(event_handler_service_preproc_msg_total{kubernetes_namespace=\"$namespace\"},app)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overall Rule Executions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "# of items preprocessed by normative check.",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(delta(event_handler_service_preproc_nrm_total{kubernetes_namespace=\"$namespace\"}[$__range]))"
    }
   ]
  },
  {
   "title": "# of items preprocessed by messaging event.",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(delta(event_handler_service_preproc_msg_total{kubernetes_namespace=\"$namespace\"}[$__range]))"
    }
   ]
  },
  {
   "title": "# of items triggered action.",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 10, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(delta(event_handler_service_items_trg_action_total{kubernetes_namespace=\"$namespace\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Messaging Event Preprocessing Rate by App",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "pp/sec" } },
   "targets": [
    {
     "expr": "sum(rate(event_handler_service_preproc_msg_total{kubernetes_namespace=\"$namespace\"}[$__rate_interval])) by (app)",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "Normative Preprocessing Rate by App",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "pp/sec" } },
   "targets": [
    {
     "expr": "sum(rate(event_handler_service_preproc_nrm_total{kubernetes_namespace=\"$namespace\"}[$__rate_interval])) by (app)",
     "legendFormat": "{{app}}"
    }
   ]
  },
  { "title": "Rule Executions ($application)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 }, "repeat": "application" },
  {
   "title": "# of items preprocessed by normative check.",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(delta(event_handler_service_preproc_nrm_total{kubernetes_namespace=\"$namespace\", app=\"$application\"}[$__range]))"
    }
   ]
  },
  {
   "title": "# of items preprocessed by messaging event.",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(delta(event_handler_service_preproc_msg_total{kubernetes_namespace=\"$namespace\", app=\"$application\"}[$__range]))"
    }
   ]
  },
  {
   "title": "# of items triggered action.",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 10, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(delta(event_handler_service_items_trg_action_total{kubernetes_namespace=\"$namespace\", app=\"$application\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Messaging Event Preprocessing Rate by Rule",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "pp/sec" } },
   "targets": [
    {
     "expr": "sum(rate(event_handler_service_preproc_msg_total{kubernetes_namespace=\"$namespace\", app=\"$application\"}[$__rate_interval])) by (ruleId)",
     "legendFormat": "Rule: {{ruleId}}"
    }
   ]
  },
  {
   "title": "Normative Preprocessing Rate by Rule",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "pp/sec" } },
   "targets": [
    {
     "expr": "sum(rate(event_handler_service_preproc_nrm_total{kubernetes_namespace=\"$namespace\", app=\"$application\"}[$__rate_interval])) by (ruleId)",
     "legendFormat": "Rule: {{ruleId}}"
    }
   ]
  }
 ]
}