{
 "title": "Notification Logs",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "environment",
    "query": {
     "query": "label_values(jvm_info, kubernetes_namespace)"
    }
   },
   {
    "name": "application",
    "query": {
     "query": "label_values(hikaricp_active_connections{kubernetes_namespace=\"$environment\"},pool)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Notification Logs Queues",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rabbitmq_queue_messages_ready{queue=\"ejustice-notification-service.notification.tracking.data.$application\", kubernetes_namespace=\"$environment\"}",
     "legendFormat": "tracking-data"
    },
    {
     "expr": "rabbitmq_queue_messages_ready{queue=\"ejustice-notification-service-de-service-*.workflow.$application\", kubernetes_namespace=\"$environment\"}",
     "legendFormat": "workflow-events"
    },
    {
     "expr": "rabbitmq_queue_messages_ready{queue=\"ejustice-notification-service-mail-service-notification.*.$application\", kubernetes_namespace=\"$environment\"}",
     "legendFormat": "mail-receipts"
    },
    {
     "expr": "rabbitmq_queue_messages_ready{queue=\"ejustice-notification-service-sms-service-sms.*.$application\", kubernetes_namespace=\"$environment\"}",
     "legendFormat": "sms-receipts"
    }
   ]
  },
  {
   "title": "Users Check",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(wf_notifications_sender_users_to_check_total{kubernetes_namespace=\"$environment\", kubernetes_name=\"ejusticenotificationservice-v1\", exported_app=\"$application\"}) by (category, state)",
     "legendFormat": "{{category}}, {{state}}"
    }
   ]
  },
  {
   "title": "Users Notify",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(wf_notifications_sender_users_to_notify_total{kubernetes_namespace=\"$environment\", kubernetes_name=\"ejusticenotificationservice-v1\", exported_app=\"$application\"}) by (category, state)",
     "legendFormat": "{{category}}, {{state}}"
    }
   ]
  },
  {
   "title": "Users Check & Notify",
   "type": "timeseries",
   "description": "Application independent",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "sum(increase(wf_notifications_sender_users_to_check_total{kubernetes_namespace=\"$environment\", kubernetes_name=\"ejusticenotificationservice-v1\", exported_app=\"$application\"}[2m])) by (exported_app)/2",
     "legendFormat": "Check"
    },
    {
     "expr": "sum(increase(wf_notifications_sender_users_to_notify_total{kubernetes_namespace=\"$environment\", kubernetes_name=\"ejusticenotificationservice-v1\", exported_app=\"$application\"}[2m])) by (exported_app)/2",
     "legendFormat": "Notify"
    }
   ]
  },
  {
   "title": "CMS -> DE (get permitted actions)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "type:\"nginx-access\" AND nginx.service.name:\"entityservice\" AND nginx.app.name:\"$application\" AND request_uri:\"/entityservice/v1/$application/workflow\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "DE -> Workflow (get actions with expression)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 35 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "type:\"nginx-access\" AND nginx.service.name:\"wfservice\" AND nginx.app.name:\"$application\" AND request_uri:\"/wfservice/v1/$application/actions/with-expression\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Workflow -> Authorization Cache",
   "type": "timeseries",
   "description": "Application independent",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 42 },
   "repeat": "cache",
   "targets": [
    {
     "expr": "sum(idelta(guava_cache_hit_total{cache=\"authorization-service-actions-permissions\", kubernetes_name=\"wfservice-v1\"}[2m]))",
     "legendFormat": "Hit"
    },
    {
     "expr": "sum(idelta(guava_cache_miss_total{cache=\"authorization-service-actions-permissions\", kubernetes_name=\"wfservice-v1\"}[2m]))",
     "legendFormat": "Miss"
    }
   ]
  }
 ]
}