{
 "title": "Track Emails Status (sent, fail)",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(mails_total,kubernetes_namespace)"
    }
   },
   {
    "name": "application",
    "query": {
     "query": "label_values(mails_total{kubernetes_namespace=\"$namespace\"},app)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Sent",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(delta(mails_total{kubernetes_namespace=\"$namespace\", app=\"$application\", status=\"OK\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Fail",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(delta(mails_total{kubernetes_namespace=\"$namespace\", app=\"$application\", status=\"Fail\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Published Messages",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "delta(rabbitmq_queue_messages_published_total{kubernetes_namespace=\"$namespace\", queue=\"mail-service.$application\"}[$__range])"
    }
   ]
  },
  {
   "title": "Consumed Messages",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "delta(rabbitmq_queue_messages_delivered_total{kubernetes_namespace=\"$namespace\", queue=\"mail-service.$application\"}[$__range])"
    }
   ]
  },
  {
   "title": "# of ERROR Logs",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "select field",
       "hide": false,
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "type.keyword:log AND app.environment.keyword:\"$namespace\" AND app.service.name.keyword:\"mailservice\" AND app.loglevel.keyword:\"ERROR\" AND app.name.keyword:\"$application\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Mail Send Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(mails_total{kubernetes_namespace=\"$namespace\", app=\"$application\"}[$__rate_interval])) by (status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Mail Send Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(mail_send_latency_bucket{kubernetes_namespace=\"$namespace\", app=\"$application\"}[$__rate_interval])) by (le))",
     "legendFormat": "95th Percentile"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(mail_send_latency_bucket{kubernetes_namespace=\"$namespace\", app=\"$application\"}[$__rate_interval])) by (le))",
     "legendFormat": "75th Percentile"
    }
   ]
  },
  {
   "title": "Error Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "Mail Connect Issues",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
     "targets": [
      {
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "(app.logmessage: com.sun.mail.util.MailConnectException OR app.logmessage:  javax.mail.MessagingException) AND app.service.name: mailservice",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Mail Invalid Addresses",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
     "targets": [
      {
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "app.logmessage: \"javax.mail.SendFailedException: Invalid Addresses\" AND app.service.name: mailservice",
       "timeField": "@timestamp"
      }
     ]
    }
   ]
  }
 ]
}