{
 "title": "user-data-service (Tracking Authentication Events)",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(hikaricp_active_connections,kubernetes_namespace)"
    }
   },
   {
    "name": "application",
    "query": {
     "query": "label_values(hikaricp_active_connections{kubernetes_namespace=\"$namespace\"},pool)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Login / Logout", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Login Requests (auth-service)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "alias": "success ",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "request_uri: \"/login\" AND nginx.service.name: \"authservice\" AND status_code: 200 AND nginx.app.name: \"$application\"",
     "timeField": "@timestamp"
    },
    {
     "alias": "fail",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "request_uri: \"/login\" AND nginx.service.name: \"authservice\" AND NOT status_code: 200 AND nginx.app.name: \"$application\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Logout Requests (auth-service)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "alias": "success ",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "request_uri: \"/logout\" AND nginx.service.name: \"authservice\" AND status_code: 200 AND nginx.app.name: \"$application\"",
     "timeField": "@timestamp"
    },
    {
     "alias": "fail",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "request_uri: \"/logout\" AND nginx.service.name: \"authservice\" AND NOT status_code: 200 AND nginx.app.name: \"$application\"",
     "timeField": "@timestamp"
    }
   ]
  },
  { "title": "Reset Password", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Password Reset Requests (user-data-service)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "alias": "success ",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "request_uri: \"/resetPassword\" AND nginx.service.name: \"userdataservice\" AND status_code: 200 AND nginx.app.name: \"$application\"",
     "timeField": "@timestamp"
    },
    {
     "alias": "fail",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "request_uri: \"/resetPassword\" AND nginx.service.name: \"userdataservice\" AND NOT status_code: 200 AND nginx.app.name: \"$application\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Password Reset Requests (um-service)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "alias": "success ",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "request_uri: \"/reset\" AND nginx.service.name: \"umservice\" AND status_code: 200 AND nginx.app.name: \"$application\"",
     "timeField": "@timestamp"
    },
    {
     "alias": "fail",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "request_uri: \"/reset\" AND nginx.service.name: \"umservice\" AND NOT status_code: 200 AND nginx.app.name: \"$application\"",
     "timeField": "@timestamp"
    }
   ]
  },
  { "title": "Registration", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Create Account Requests (user-data-service)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 21 },
   "targets": [
    {
     "alias": "success ",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "request_uri: \"/createAccount\" AND nginx.service.name: \"userdataservice\" AND status_code: 200 AND nginx.app.name: \"$application\"",
     "timeField": "@timestamp"
    },
    {
     "alias": "fail",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "request_uri: \"/createAccount\" AND nginx.service.name: \"userdataservice\" AND NOT status_code: 200 AND nginx.app.name: \"$application\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Confirm Account Requests (user-data-service)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 21 },
   "targets": [
    {
     "alias": "success ",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "request_uri: \"/confirmAccount\" AND nginx.service.name: \"userdataservice\" AND status_code: 200 AND nginx.app.name: \"$application\"",
     "timeField": "@timestamp"
    },
    {
     "alias": "fail",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "request_uri: \"/confirmAccount\" AND nginx.service.name: \"userdataservice\" AND NOT status_code: 200 AND nginx.app.name: \"$application\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Send Activation Requests (user-data-service)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 21 },
   "targets": [
    {
     "alias": "success ",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "request_uri: \"/sendActivation\" AND nginx.service.name: \"userdataservice\" AND status_code: 200 AND nginx.app.name: \"$application\"",
     "timeField": "@timestamp"
    },
    {
     "alias": "fail",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "request_uri: \"/sendActivation\" AND nginx.service.name: \"userdataservice\" AND NOT status_code: 200 AND nginx.app.name: \"$application\"",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}